// 78 cartes de tarot (Arcanes Majeurs 22 + Arcanes Mineurs 56)
const TAROT_CARDS = [
// ═══════════════════════════════════════
// Arcanes Majeurs (0~21)
// ═══════════════════════════════════════
{id:'m0',name:'Le Mat',en:'The Fool',emoji:'🃏',suit:'major',num:0,
up:'Un nouveau départ se présente devant vous. Posez vos peurs et faites un pas en avant. C\'est le moment de suivre votre instinct sans trop calculer. Plongez dans le monde avec un cœur pur. Une aventure inattendue vous attend. N\'ayez pas peur d\'échouer — le Mat saute du bord de la falaise en souriant.',
down:'Vous agissez trop impulsivement en ce moment. Foncer sans préparation peut mener à une grosse erreur. Réfléchissez encore, et écoutez les conseils de votre entourage. Liberté et imprudence sont deux choses différentes. Méfiez-vous des jugements hâtifs.'},
{id:'m1',name:'Le Magicien',en:'The Magician',emoji:'🪄',suit:'major',num:1,
up:'Tous les outils et talents dont vous avez besoin sont déjà en votre possession. C\'est le moment de vous concentrer et d\'agir. Avec volonté et créativité, vous pouvez accomplir ce que vous désirez. Comme le Magicien qui relie ciel et terre, transformez vos idées en réalité. Vos paroles et vos actes ont du pouvoir.',
down:'Vous gaspillez vos talents ou les utilisez à mauvais escient. Un manque de confiance vous fait passer à côté des opportunités. Ou bien vos paroles et vos actes ne sont pas en accord. Retrouvez votre authenticité.'},
{id:'m2',name:'La Papesse',en:'The High Priestess',emoji:'🌙',suit:'major',num:2,
up:'La réponse est déjà en vous. Faites confiance à votre intuition plutôt qu\'à la logique. En écoutant tranquillement votre voix intérieure, des vérités cachées se révèleront. C\'est une période d\'observation plutôt que d\'action. Lisez ce qui se trouve sous la surface. Une sagesse mystérieuse vous guide.',
down:'Vous ignorez votre intuition et vous fiez aux apparences. Ou bien il y a une vérité que vous connaissez mais que vous refusez de voir. Cherchez les motivations cachées. Vous devez regarder plus profondément.'},
{id:'m3',name:'L\'Impératrice',en:'The Empress',emoji:'🌺',suit:'major',num:3,
up:'C\'est une période d\'abondance et d\'amour. Prenez soin de vous et savourez vos sens. L\'énergie créatrice est à son sommet, propice à la création. La communion avec la nature rechargera vos batteries. Enveloppez votre entourage d\'un amour maternel. Chercher la beauté n\'est pas du luxe.',
down:'Vous négligez votre bien-être ou dépendez trop des autres. Si vous ressentez un blocage créatif, cherchez l\'inspiration dans la nature. Méfiez-vous de la jalousie et de la possessivité.'},
{id:'m4',name:'L\'Empereur',en:'The Emperor',emoji:'👑',suit:'major',num:4,
up:'Une approche systématique et déterminée est nécessaire. Établir de la discipline et de l\'ordre vous apportera de la stabilité. Exercez votre leadership et agissez avec responsabilité. Laissez la raison guider vos décisions plutôt que les émotions. Les règles que vous posez apportent aussi de la sécurité aux autres.',
down:'Vous êtes trop rigide ou trop contrôlant. Imposer des règles sans souplesse peut provoquer de la résistance. Demandez-vous si vous n\'abusez pas de votre autorité. Parfois, céder du terrain est une vraie force.'},
{id:'m5',name:'Le Hiérophante',en:'The Hierophant',emoji:'🙏',suit:'major',num:5,
up:'Vous pouvez trouver des réponses dans les valeurs traditionnelles ou auprès d\'un mentor. C\'est une période d\'apprentissage et de croissance spirituelle. Trouvez un sentiment d\'appartenance au sein d\'une communauté. Suivre des méthodes éprouvées vous mettra en sécurité. Donner et recevoir des enseignements fait grandir les deux parties.',
down:'Les méthodes existantes ne vous conviennent plus. Il est temps de sortir de la pensée conventionnelle et de trouver votre propre chemin. Jugez par vous-même plutôt que de suivre aveuglément. Une approche non conventionnelle pourrait être la réponse.'},
{id:'m6',name:'Les Amoureux',en:'The Lovers',emoji:'💕',suit:'major',num:6,
up:'L\'amour arrive, ou vous vous trouvez à un carrefour important. Choisissez selon ce que votre cœur vous dit. Une véritable union et harmonie se crée. La rencontre avec quelqu\'un qui partage vos valeurs peut changer votre vie. Soyez honnête dans l\'amour.',
down:'Il y a de la discorde dans la relation ou un conflit de valeurs. Si vous êtes tenté, demandez-vous ce que vous désirez vraiment. Prenez du recul avant de faire un mauvais choix.'},
{id:'m7',name:'Le Chariot',en:'The Chariot',emoji:'⚡',suit:'major',num:7,
up:'C\'est le moment de surmonter les obstacles avec une volonté de fer ! N\'arrêtez pas, avancez. La détermination et la concentration mènent à la victoire. En maîtrisant des forces opposées, vous pouvez atteindre votre objectif. Vous pouvez gagner.',
down:'Vous avez perdu votre direction et êtes ébranlé. Vous êtes emporté par vos émotions et perdez le contrôle, ou vous vous épuisez à vouloir tout faire en même temps. Faites une pause et recalibrez votre cap.'},
{id:'m8',name:'La Force',en:'Strength',emoji:'🦁',suit:'major',num:8,
up:'La force douce l\'emporte sur la force brute. Maîtrisez la situation avec patience et courage. Ne réprimez pas la colère ou la peur — enveloppez-les doucement. Apprivoiser la bête intérieure, c\'est avec amour, pas avec violence. Vous êtes bien plus fort que vous ne le pensez.',
down:'Vous avez perdu confiance en vous et vous sentez faible. Vous êtes submergé par les émotions ou noyé dans le doute. Réveillez à nouveau la force intérieure. N\'abandonnez pas — il y a un lion en vous.'},
{id:'m9',name:'L\'Hermite',en:'The Hermit',emoji:'🔦',suit:'major',num:9,
up:'Vous avez besoin de temps seul. Éloignez-vous du bruit et explorez votre intérieur. La réponse n\'est pas dehors, elle est en vous. C\'est une période propice à la méditation et à la réflexion pour obtenir une sagesse profonde. La solitude n\'est pas de la solitude — c\'est une découverte de soi.',
down:'Vous vous êtes isolé trop longtemps. Vous êtes enfermé dans vos propres pensées, coupé du monde. Il est temps de vous reconnecter aux autres. Demander de l\'aide n\'est pas une faiblesse.'},
{id:'m10',name:'La Roue de Fortune',en:'Wheel of Fortune',emoji:'🎡',suit:'major',num:10,
up:'La roue du destin tourne ! De grands changements et de la chance arrivent. Ne manquez pas cette opportunité. C\'est un tournant dans le cycle de votre vie. Laissez-vous porter par le courant. De bonnes choses peuvent arriver en chaîne.',
down:'La malchance frappe ou vous résistez au changement. Mais souvenez-vous — la roue tourne toujours. Les mauvaises périodes passent aussi. Faites confiance au flux et persévérez.'},
{id:'m11',name:'La Justice',en:'Justice',emoji:'⚖️',suit:'major',num:11,
up:'Un résultat juste arrive. Agir avec vérité et honnêteté vous apportera de bons résultats. Les problèmes légaux peuvent se résoudre favorablement. La loi de cause à effet est à l\'œuvre. Faites le bon choix.',
down:'Vous êtes dans une situation injuste ou vous évitez vos responsabilités. Une vérité pourrait être révélée, alors faites face à la réalité. Vérifiez si votre jugement n\'est pas biaisé.'},
{id:'m12',name:'Le Pendu',en:'The Hanged Man',emoji:'🙃',suit:'major',num:12,
up:'Vu d\'un autre angle, la réponse apparaît. C\'est une période d\'observation et d\'attente plutôt que d\'action. Ce n\'est pas un abandon, mais une pause pour gagner une nouvelle perspective. Paradoxalement, en lâchant prise, on peut obtenir. Le sacrifice finit par se transformer en grande récompense.',
down:'Vous êtes épuisé d\'une attente sans sens. Si la situation est bloquée, changez de perspective ou passez à l\'action. Arrêtez de jouer au martyr.'},
{id:'m13',name:'La Mort',en:'Death',emoji:'💀',suit:'major',num:13,
up:'La fin est un nouveau commencement. N\'ayez pas peur — ce n\'est pas une mort physique, c\'est une transformation. Il faut lâcher l\'ancien pour que le nouveau vienne. Une relation, un travail, une habitude prennent fin, mais c\'est un processus nécessaire. Pour devenir papillon, la chenille doit mourir.',
down:'Vous résistez aux changements nécessaires. Vous vous accrochez à ce qui doit se terminer. Lâchez prise. Plus vous refusez le changement, plus la souffrance dure.'},
{id:'m14',name:'La Tempérance',en:'Temperance',emoji:'🌊',suit:'major',num:14,
up:'C\'est une période d\'équilibre et d\'harmonie. Évitez les extrêmes et gardez le juste milieu. En progressant patiemment et lentement, de bons résultats viendront. Votre capacité à mélanger harmonieusement des éléments différents brille en ce moment. Prenez soin aussi de votre santé physique et mentale.',
down:'Vous avez perdu l\'équilibre et penchez d\'un côté. Attention aux excès — alcool, nourriture, surmenage. L\'impatience peut tout gâcher. Retrouvez l\'équilibre.'},
{id:'m15',name:'Le Diable',en:'The Devil',emoji:'😈',suit:'major',num:15,
up:'Vous êtes obsédé ou dépendant de quelque chose. Vous êtes lié à la matière, au plaisir, à une relation. Mais ces chaînes, c\'est vous qui les avez mises, et c\'est vous qui pouvez les briser. Regardez votre ombre en face. Il faut reconnaître pour se libérer.',
down:'Vous vous libérez de vos chaînes ! Vous êtes en train de vous affranchir de mauvaises habitudes ou de relations toxiques. Reprenez votre liberté. Vous n\'avez plus rien à craindre désormais.'},
{id:'m16',name:'La Tour',en:'The Tower',emoji:'🗼',suit:'major',num:16,
up:'Un changement ou un choc soudain peut arriver. Ce qui a été bâti peut s\'effondrer, mais c\'est ce qui était construit sur de mauvaises fondations qui s\'effondre. Après la destruction, vous pouvez construire quelque chose de plus solide. La vérité se révèle comme la foudre.',
down:'Vous tentez d\'éviter un effondrement inévitable. Mais si ce qui doit tomber ne tombe pas, une plus grande catastrophe arrive. Acceptez le changement.'},
{id:'m17',name:'L\'Étoile',en:'The Star',emoji:'⭐',suit:'major',num:17,
up:'C\'est la lumière des étoiles dans le calme après la tempête. L\'espoir revient. Les blessures se guérissent et l\'inspiration jaillit. L\'univers vous aide, alors ne renoncez pas à vos rêves. Montrez-vous tel que vous êtes vraiment. Vous brillez.',
down:'Vous avez perdu espoir et êtes découragé. Mais derrière les nuages, les étoiles sont toujours là. Retrouvez la confiance en vous-même. Il est trop tôt pour abandonner.'},
{id:'m18',name:'La Lune',en:'The Moon',emoji:'🌙',suit:'major',num:18,
up:'C\'est une période brumeuse où tout manque de clarté. Faites confiance à votre intuition mais ne vous perdez pas dans les illusions. Prêtez attention aux messages de votre inconscient. Vos rêves peuvent vous donner d\'importants indices. Affronter vos peurs les fera disparaître.',
down:'Le brouillard se lève et la vérité commence à apparaître. La confusion se dissipe, les choses deviennent claires. Ce qui était caché se révèle, tenez-vous prêt.'},
{id:'m19',name:'Le Soleil',en:'The Sun',emoji:'☀️',suit:'major',num:19,
up:'Une énergie lumineuse et chaleureuse déborde ! C\'est une période de succès, de joie et de vitalité. Brillez avec confiance. Savourez la joie avec la pureté d\'un enfant. L\'obscurité est passée, le soleil s\'est levé. Une célébration est proche !',
down:'Le succès vient, mais il peut y avoir un léger retard. Vous manquez de confiance ou ne ressentez pas suffisamment la joie. Maintenez un état d\'esprit positif. Le soleil se lève toujours.'},
{id:'m20',name:'Le Jugement',en:'Judgement',emoji:'📯',suit:'major',num:20,
up:'Vous êtes à un tournant de votre vie. Il est temps de faire le bilan du passé et de le mettre de l\'ordre. Découvrez votre vocation et renaissez. Le pardon et la libération sont à l\'œuvre. Répondez à l\'appel intérieur. Vous êtes prêt à vous élever à un niveau supérieur.',
down:'Vous êtes paralysé par le doute et ne parvenez pas à vous libérer du passé. Ne restez pas prisonnier des regrets. Pardonnez-vous et avancez. Une deuxième chance existe.'},
{id:'m21',name:'Le Monde',en:'The World',emoji:'🌍',suit:'major',num:21,
up:'Un immense cycle s\'est accompli ! Vous avez atteint votre objectif et atteint un état d\'intégration. Félicitations ! Voyages, expansion, de nouvelles possibilités s\'ouvrent. Un chapitre se ferme et un nouveau commence.',
down:'Vous y êtes presque, mais il manque encore un dernier pas. Il faut une conclusion pour achever l\'œuvre. Ne renoncez pas, la fin est en vue. Secouez le regret de l\'inachevé et faites de votre mieux.'},

// ═══════════════════════════════════════
// Arcanes Mineurs — Bâtons (feu)
// ═══════════════════════════════════════
{id:'wA',name:'As de Bâtons',en:'Ace of Wands',emoji:'🔥',suit:'wands',num:1,
up:'Une nouvelle passion et une nouvelle inspiration jaillissent ! L\'énergie créatrice explose. C\'est le moment idéal pour démarrer un nouveau projet.',
down:'Perte de motivation, incapacité à commencer. Vous avez des idées, mais vous n\'arrivez pas à passer à l\'action.'},
{id:'w2',name:'Deux de Bâtons',en:'Two of Wands',emoji:'🔥',suit:'wands',num:2,
up:'Il est temps de planifier l\'avenir et de voir les choses en grand. Le monde est entre vos mains. Un moment de décision.',
down:'Peur des projets, réticence à quitter ce qui est familier. Vous remettez les décisions à plus tard.'},
{id:'w3',name:'Trois de Bâtons',en:'Three of Wands',emoji:'🔥',suit:'wands',num:3,
up:'Les résultats de vos efforts commencent à apparaître. Opportunité d\'expansion et de croissance. De bonnes nouvelles arrivent de loin ou de l\'étranger.',
down:'Les résultats ne sont pas à la hauteur des attentes, déception. La patience est nécessaire.'},
{id:'w4',name:'Quatre de Bâtons',en:'Four of Wands',emoji:'🔥',suit:'wands',num:4,
up:'Une période de fête et de joie ! Mariage, fête, déménagement — de bonnes nouvelles sont au rendez-vous. Une base stable s\'est établie.',
down:'Environnement familial instable, célébrations retardées. Les fondations vacillent.'},
{id:'w5',name:'Cinq de Bâtons',en:'Five of Wands',emoji:'🔥',suit:'wands',num:5,
up:'Période de compétition et de conflits. Mais c\'est une compétition saine pour la croissance. Tenez votre position.',
down:'Évitez les querelles inutiles. La compromis et la coopération sont la réponse.'},
{id:'w6',name:'Six de Bâtons',en:'Six of Wands',emoji:'🔥',suit:'wands',num:6,
up:'Victoire et reconnaissance ! Vos efforts sont récompensés et les éloges pleuvent. Ayez confiance en vous.',
down:'Sentiment de ne pas être reconnu, attention à l\'arrogance. Restez humble.'},
{id:'w7',name:'Sept de Bâtons',en:'Seven of Wands',emoji:'🔥',suit:'wands',num:7,
up:'C\'est le moment de faire face aux défis. Tenez fermement votre position. Si vous ne renoncez pas, vous pouvez gagner.',
down:'Sentiment d\'être dépassé, envie d\'abandonner. Un repli stratégique peut aussi être une option.'},
{id:'w8',name:'Huit de Bâtons',en:'Eight of Wands',emoji:'🔥',suit:'wands',num:8,
up:'Les choses avancent rapidement ! Nouvelles, voyages, changements — tout se passe en un éclair. Surfez sur le courant.',
down:'Retards, frustrations, attente. Les choses avancent plus lentement que prévu.'},
{id:'w9',name:'Neuf de Bâtons',en:'Nine of Wands',emoji:'🔥',suit:'wands',num:9,
up:'C\'est difficile, mais vous y êtes presque. Surmontez ce dernier épreuve. Vous êtes suffisamment fort.',
down:'Épuisement, burn-out. Vous avez besoin de vous reposer. Forcer davantage vous fera craquer.'},
{id:'w10',name:'Dix de Bâtons',en:'Ten of Wands',emoji:'🔥',suit:'wands',num:10,
up:'Vous portez un fardeau trop lourd. Le sens des responsabilités est bien, mais vous n\'avez pas à tout faire seul. Demandez de l\'aide.',
down:'Il est temps de poser votre fardeau. Libérez-vous des responsabilités inutiles.'},
{id:'wP',name:'Valet de Bâtons',en:'Page of Wands',emoji:'🔥',suit:'wands',num:11,
up:'Des nouvelles passionnantes arrivent ! Le début d\'une nouvelle aventure. Suivez votre curiosité.',
down:'Les plans tombent à l\'eau ou les nouvelles sont retardées.'},
{id:'wN',name:'Cavalier de Bâtons',en:'Knight of Wands',emoji:'🔥',suit:'wands',num:12,
up:'C\'est le moment de foncer avec passion ! L\'esprit d\'aventure et le courage débordent. Agissez avec audace.',
down:'Précipitation, attention aux actes impulsifs. Vous courez sans direction.'},
{id:'wQ',name:'Reine de Bâtons',en:'Queen of Wands',emoji:'🔥',suit:'wands',num:13,
up:'Une énergie pleine de confiance et de charme ! Exercez un leadership chaleureux mais fort.',
down:'Jalousie, comportement égocentrique. Reconnaissez aussi la lumière des autres.'},
{id:'wK',name:'Roi de Bâtons',en:'King of Wands',emoji:'🔥',suit:'wands',num:14,
up:'Vision et leadership accompliront de grandes choses. Guidez les gens avec votre charisme.',
down:'Autoritaire, tyrannie. N\'abusez pas du pouvoir.'},

// ═══════════════════════════════════════
// Arcanes Mineurs — Coupes (eau)
// ═══════════════════════════════════════
{id:'cA',name:'As de Coupes',en:'Ace of Cups',emoji:'💧',suit:'cups',num:1,
up:'Un nouvel amour, le début d\'une émotion ! Période de plénitude du cœur. Vous êtes prêt à donner et recevoir de l\'amour.',
down:'Vide émotionnel, incapacité à recevoir de l\'amour.'},
{id:'c2',name:'Deux de Coupes',en:'Two of Cups',emoji:'💧',suit:'cups',num:2,
up:'Un lien profond et un partenariat. Un véritable amour ou une amitié s\'épanouit. Une relation de respect mutuel.',
down:'Déséquilibre dans la relation, signe de séparation.'},
{id:'c3',name:'Trois de Coupes',en:'Three of Cups',emoji:'💧',suit:'cups',num:3,
up:'Célébration, amitié, rassemblements ! Des moments agréables entre amis. Les activités sociales apportent de la chance.',
down:'Excès d\'alcool, débauche. Vous ratez des choses importantes en vous laissant emporter par le plaisir.'},
{id:'c4',name:'Quatre de Coupes',en:'Four of Cups',emoji:'💧',suit:'cups',num:4,
up:'Ennui, indifférence. Vous ne voyez pas les opportunités devant vous. Tournez votre regard et découvrez de nouvelles possibilités.',
down:'Vous commencez à accepter de nouvelles opportunités. Sortez de l\'apathie.'},
{id:'c5',name:'Cinq de Coupes',en:'Five of Cups',emoji:'💧',suit:'cups',num:5,
up:'Tristesse et sentiment de perte. Ne vous fixez pas sur ce qui est renversé. En regardant en arrière, il reste encore quelque chose.',
down:'En voie de guérison après la tristesse. Lâchez le passé et avancez.'},
{id:'c6',name:'Six de Coupes',en:'Six of Cups',emoji:'💧',suit:'cups',num:6,
up:'Nostalgie, souvenirs d\'enfance, pureté. D\'anciennes connaissances peuvent revenir. Les bons souvenirs du passé apportent une guérison.',
down:'S\'accrocher au passé, incapacité à vivre le présent. Avancez.'},
{id:'c7',name:'Sept de Coupes',en:'Seven of Cups',emoji:'💧',suit:'cups',num:7,
up:'Illusions et une multitude de choix. Mais tout n\'est pas réel. Jugez de façon réaliste.',
down:'Vous vous réveillez des illusions et faites des choix réalistes.'},
{id:'c8',name:'Huit de Coupes',en:'Eight of Cups',emoji:'💧',suit:'cups',num:8,
up:'Il est temps de quitter ce qui ne vous comble plus. Un abandon courageux. Partez à la recherche d\'un sens plus profond.',
down:'Vous restez là où vous devriez partir. Abandonnez vos regrets.'},
{id:'c9',name:'Neuf de Coupes',en:'Nine of Cups',emoji:'💧',suit:'cups',num:9,
up:'Vœu exaucé ! Satisfaction et bonheur débordent. Savourez la joie avec gratitude. Les rêves se réalisent.',
down:'Vide intérieur malgré l\'abondance matérielle. Le vrai bonheur est en vous.'},
{id:'c10',name:'Dix de Coupes',en:'Ten of Cups',emoji:'💧',suit:'cups',num:10,
up:'Bonheur parfait ! Famille, amour, harmonie. Un état de plénitude émotionnelle. Un foyer heureux sous l\'arc-en-ciel.',
down:'Discordes familiales, relation en dessous des attentes. Ne courez pas après la perfection.'},
{id:'cP',name:'Valet de Coupes',en:'Page of Cups',emoji:'💧',suit:'cups',num:11,
up:'Un message ou une proposition émotionnelle arrive. Faites confiance à votre intuition. Le début d\'un nouveau sentiment.',
down:'Immaturité émotionnelle. Attentes irréalistes.'},
{id:'cN',name:'Cavalier de Coupes',en:'Knight of Cups',emoji:'💧',suit:'cups',num:12,
up:'Une proposition romantique s\'approche ! Inspiration artistique. Soyez fidèle à vos émotions.',
down:'Illusions irréalistes, attention à la manipulation émotionnelle.'},
{id:'cQ',name:'Reine de Coupes',en:'Queen of Cups',emoji:'💧',suit:'cups',num:13,
up:'Empathie profonde et intuition. La reine qui maîtrise l\'océan des émotions. Guérissez avec amour.',
down:'Submergé par les émotions, dépendance affective.'},
{id:'cK',name:'Roi de Coupes',en:'King of Cups',emoji:'💧',suit:'cups',num:14,
up:'Sagesse et équilibre émotionnel. Un leadership calme et bienveillant. L\'harmonie entre les émotions et la raison.',
down:'Froideur émotionnelle, refoulement des émotions.'},

// ═══════════════════════════════════════
// Arcanes Mineurs — Épées (air)
// ═══════════════════════════════════════
{id:'sA',name:'As d\'Épées',en:'Ace of Swords',emoji:'⚔️',suit:'swords',num:1,
up:'Une vérité claire, une percée ! De nouvelles idées jaillissent comme l\'éclair. L\'heure de la décision.',
down:'Confusion, fausses informations. Éliminez ce qui trouble votre jugement.'},
{id:'s2',name:'Deux d\'Épées',en:'Two of Swords',emoji:'⚔️',suit:'swords',num:2,
up:'Impasse dans la prise de décision. Ne vous couvrez pas les yeux — regardez la vérité en face.',
down:'Des informations se révèlent et permettent de prendre une décision.'},
{id:'s3',name:'Trois d\'Épées',en:'Three of Swords',emoji:'⚔️',suit:'swords',num:3,
up:'Blessures du cœur, trahison, séparation. Douloureux, mais cette souffrance vous fait grandir. N\'étouffez pas vos émotions.',
down:'En voie de guérison. La douleur disparaît peu à peu.'},
{id:'s4',name:'Quatre d\'Épées',en:'Four of Swords',emoji:'⚔️',suit:'swords',num:4,
up:'Vous avez besoin de repos. Retirez-vous momentanément du combat pour vous ressourcer. La méditation et le repos sont la réponse.',
down:'Vous vous surminez sans vous reposer. Risque de burn-out.'},
{id:'s5',name:'Cinq d\'Épées',en:'Five of Swords',emoji:'⚔️',suit:'swords',num:5,
up:'Même en gagnant, le coût est élevé. Réfléchissez si la victoire en vaut la peine. Recourir à des moyens déloyaux vous mènera au regret.',
down:'Le moment d\'admettre la défaite et d\'en tirer les leçons. Mettez votre orgueil de côté.'},
{id:'s6',name:'Six d\'Épées',en:'Six of Swords',emoji:'⚔️',suit:'swords',num:6,
up:'Vous traversez une période difficile vers un endroit meilleur. La douleur de la transition va bientôt se terminer.',
down:'Vous n\'arrivez pas à partir et vous restez. Acceptez le changement.'},
{id:'s7',name:'Sept d\'Épées',en:'Seven of Swords',emoji:'⚔️',suit:'swords',num:7,
up:'La stratégie est nécessaire. Approchez-vous avec sagesse plutôt que de foncer. Mais la tromperie finit toujours par être découverte.',
down:'La tromperie est démasquée. L\'honnêteté est la meilleure stratégie.'},
{id:'s8',name:'Huit d\'Épées',en:'Eight of Swords',emoji:'⚔️',suit:'swords',num:8,
up:'Vous vous sentez emprisonné, mais ces chaînes sont celles que vous vous êtes imposées. En ôtant le bandeau, vous pouvez vous échapper.',
down:'Vous commencez à vous libérer de vos limites. Avancez vers la liberté.'},
{id:'s9',name:'Neuf d\'Épées',en:'Nine of Swords',emoji:'⚔️',suit:'swords',num:9,
up:'Anxiété, cauchemars, inquiétudes. La souffrance de ne pas trouver le sommeil la nuit. Mais la plupart des peurs ne sont pas la réalité.',
down:'La pire période passe. Posez vos inquiétudes.'},
{id:'s10',name:'Dix d\'Épées',en:'Ten of Swords',emoji:'⚔️',suit:'swords',num:10,
up:'Vous avez touché le fond. Ça ne peut plus aller plus mal. Mais c\'est une fin et un nouveau départ. Le soleil se lève.',
down:'Vous passez le pire, des signes de rétablissement. La force de se relever revient.'},
{id:'sP',name:'Valet d\'Épées',en:'Page of Swords',emoji:'⚔️',suit:'swords',num:11,
up:'Curiosité et observation aiguisée. Nouvelles informations ou nouvelles. Creusez la vérité.',
down:'Commérages, médisances, communication immature.'},
{id:'sN',name:'Cavalier d\'Épées',en:'Knight of Swords',emoji:'⚔️',suit:'swords',num:12,
up:'Une action rapide et décisive ! Avancez sans relâche. Battez-vous pour la justice.',
down:'Précipitation, charge imprudente. Réfléchissez avant d\'agir.'},
{id:'sQ',name:'Reine d\'Épées',en:'Queen of Swords',emoji:'⚔️',suit:'swords',num:13,
up:'Jugement clair et indépendance. Sagesse qui ne cède pas aux émotions. Regardez la vérité en face.',
down:'La froideur devient trop froide, impression glaciale. L\'empathie est aussi nécessaire.'},
{id:'sK',name:'Roi d\'Épées',en:'King of Swords',emoji:'⚔️',suit:'swords',num:14,
up:'Autorité intellectuelle et jugement équitable. Prenez vos décisions avec logique et éthique.',
down:'Jugement dogmatique, inhumain. Il faut aussi utiliser son cœur, pas seulement sa tête.'},

// ═══════════════════════════════════════
// Arcanes Mineurs — Pentacles (terre)
// ═══════════════════════════════════════
{id:'pA',name:'As de Pentacles',en:'Ace of Pentacles',emoji:'💰',suit:'pentacles',num:1,
up:'Une nouvelle opportunité financière ! Investissement, emploi, graine d\'entreprise. Le début de l\'abondance matérielle.',
down:'Attention à ne pas laisser passer une opportunité ou à subir une perte financière.'},
{id:'p2',name:'Deux de Pentacles',en:'Two of Pentacles',emoji:'💰',suit:'pentacles',num:2,
up:'Jongler pour trouver l\'équilibre. Vous gérez plusieurs choses en même temps. Adaptez-vous avec souplesse.',
down:'Sur le point de perdre l\'équilibre. Définissez vos priorités.'},
{id:'p3',name:'Trois de Pentacles',en:'Three of Pentacles',emoji:'💰',suit:'pentacles',num:3,
up:'Le travail d\'équipe et la coopération produisent des résultats. L\'expertise est reconnue. Travailler ensemble donne de meilleurs résultats.',
down:'Échec à vouloir tout faire seul. Prenez conscience de la valeur de la coopération.'},
{id:'p4',name:'Quatre de Pentacles',en:'Four of Pentacles',emoji:'💰',suit:'pentacles',num:4,
up:'Stabilité et sécurité. Vous êtes financièrement en sécurité, mais trop s\'accrocher vous fait rater de nouvelles opportunités.',
down:'Avarice, attachement excessif à la matière. En partageant, vous recevrez davantage.'},
{id:'p5',name:'Cinq de Pentacles',en:'Five of Pentacles',emoji:'💰',suit:'pentacles',num:5,
up:'Difficultés financières, sentiment d\'isolement. C\'est une période difficile, mais l\'aide est proche. Levez les yeux.',
down:'La pire situation est en train de passer. La lumière du rétablissement apparaît.'},
{id:'p6',name:'Six de Pentacles',en:'Six of Pentacles',emoji:'💰',suit:'pentacles',num:6,
up:'Équilibre du donner et du recevoir. La générosité apporte de la chance. C\'est le moment de donner ou de recevoir de l\'aide.',
down:'Déséquilibre du donner et du recevoir. Attention à la relation déséquilibrée.'},
{id:'p7',name:'Sept de Pentacles',en:'Seven of Pentacles',emoji:'💰',suit:'pentacles',num:7,
up:'Vous avez planté les graines et attendez les résultats. La patience est nécessaire. Les efforts porteront toujours leurs fruits.',
down:'Impatience, frustration de ne pas voir les résultats. Ne renoncez pas, vous y êtes presque.'},
{id:'p8',name:'Huit de Pentacles',en:'Eight of Pentacles',emoji:'💰',suit:'pentacles',num:8,
up:'Esprit artisan ! Période d\'affinement de vos compétences. L\'effort constant fait le professionnel.',
down:'Épuisé par la répétition, perte de motivation. Rappelez-vous votre objectif.'},
{id:'p9',name:'Neuf de Pentacles',en:'Nine of Pentacles',emoji:'💰',suit:'pentacles',num:9,
up:'Indépendance et abondance ! Savourez les fruits de votre réussite personnelle. Une vie de qualité. Vous le méritez pleinement.',
down:'Anxiété face à l\'indépendance, dépendance aux autres.'},
{id:'p10',name:'Dix de Pentacles',en:'Ten of Pentacles',emoji:'💰',suit:'pentacles',num:10,
up:'Accomplissement matériel ! Prospérité familiale, héritage, stabilité à long terme. Richesse et bonheur qui traversent les générations.',
down:'Conflits financiers familiaux, problèmes d\'héritage. Les relations sont plus importantes que la matière.'},
{id:'pP',name:'Valet de Pentacles',en:'Page of Pentacles',emoji:'💰',suit:'pentacles',num:11,
up:'Nouvelles d\'un apprentissage ou d\'une opportunité financière. Un travail sérieux donnera des résultats.',
down:'Plans irréalistes, paresse.'},
{id:'pN',name:'Cavalier de Pentacles',en:'Knight of Pentacles',emoji:'💰',suit:'pentacles',num:12,
up:'Progression fiable et sérieuse. Avancement lent mais certain. La régularité gagne.',
down:'Trop lent, trop conservateur. Parfois, l\'audace est aussi nécessaire.'},
{id:'pQ',name:'Reine de Pentacles',en:'Queen of Pentacles',emoji:'💰',suit:'pentacles',num:13,
up:'Sagesse pratique et abondance chaleureuse. Une énergie pratique mais généreuse. L\'équilibre entre foyer et finances.',
down:'Manque de soin de soi, bourreau de travail.'},
{id:'pK',name:'Roi de Pentacles',en:'King of Pentacles',emoji:'💰',suit:'pentacles',num:14,
up:'Succès financier et stabilité ! Sens des affaires et leadership pratique. Récolte de fruits abondants.',
down:'Avarice, matérialisme. L\'argent n\'est pas tout.'}
];
