// 78 cartas de tarot (22 Arcanos Mayores + 56 Arcanos Menores)
const TAROT_CARDS = [
// ═══════════════════════════════════════
// Arcanos Mayores (0~21)
// ═══════════════════════════════════════
{id:'m0',name:'El Loco',en:'The Fool',emoji:'🃏',suit:'major',num:0,
up:'Un nuevo comienzo está frente a ti. Suelta el miedo y da el primer paso. Ahora es momento de seguir tu instinto, no de calcular. Lánzate al mundo con el corazón puro. Una aventura inesperada te espera. No temas al fracaso — el Loco salta al abismo con una sonrisa en los labios.',
down:'Estás actuando de forma demasiado impulsiva. Lanzarte sin preparación puede llevarte a un gran error. Piénsalo una vez más y escucha los consejos de quienes te rodean. Libertad y temeridad no son lo mismo. Cuídate de los juicios apresurados.'},
{id:'m1',name:'El Mago',en:'The Magician',emoji:'🪄',suit:'major',num:1,
up:'Ya tienes todas las herramientas y talentos que necesitas. Es momento de concentrarte y actuar. Con fuerza de voluntad y creatividad, lograrás lo que deseas. Como el Mago que une cielo y tierra, convierte tus ideas en realidad. Tus palabras y acciones tienen poder.',
down:'Estás desperdiciando tu talento o usándolo de manera equivocada. La falta de confianza puede hacerte perder oportunidades. O quizás tus palabras y acciones no son coherentes. Recupera tu autenticidad.'},
{id:'m2',name:'La Suma Sacerdotisa',en:'The High Priestess',emoji:'🌙',suit:'major',num:2,
up:'La respuesta ya está dentro de ti. Confía en tu intuición más que en la lógica. Si escuchas en silencio la voz de tu interior, la verdad oculta se revelará. Ahora es tiempo de observar, no de actuar. Lee lo que está debajo de la superficie. Una sabiduría misteriosa te guía.',
down:'Estás ignorando tu intuición y dependiendo solo de las apariencias. O hay una verdad que conoces pero que prefieres no ver. Descubre las motivaciones ocultas. Necesitas mirar más profundo.'},
{id:'m3',name:'La Emperatriz',en:'The Empress',emoji:'🌺',suit:'major',num:3,
up:'Es una época de abundancia y amor. Disfruta de tus sentidos y cuídate. Tu energía creativa está en auge, perfecto para crear cosas nuevas. Conectarte con la naturaleza recargará tu energía. Envuelve a quienes te rodean con amor maternal. Buscar la belleza no es un lujo.',
down:'Estás descuidando tu autocuidado o dependiendo demasiado de los demás. Si sientes un bloqueo creativo, busca inspiración en la naturaleza. Ten cuidado con los celos y el deseo de posesión.'},
{id:'m4',name:'El Emperador',en:'The Emperor',emoji:'👑',suit:'major',num:4,
up:'Es momento de un enfoque sistemático y firme. Establecer disciplina y orden te dará estabilidad. Ejerce liderazgo y actúa con responsabilidad. Debes juzgar con la razón, no con las emociones. Las reglas que estableces también brindan seguridad a los demás.',
down:'Eres demasiado rígido o controlador. Imponer reglas sin flexibilidad puede generar resistencia. Reflexiona si estás abusando de tu autoridad. A veces, dar un paso atrás es la verdadera fortaleza.'},
{id:'m5',name:'El Hierofante',en:'The Hierophant',emoji:'🙏',suit:'major',num:5,
up:'Puedes encontrar respuestas en los valores tradicionales o en un mentor. Es tiempo de aprendizaje y crecimiento espiritual. Encuentra un sentido de pertenencia en tu comunidad. Seguir métodos probados es seguro. El intercambio de enseñanzas hace crecer a todos.',
down:'La forma tradicional ya no te funciona. Es tiempo de salir del pensamiento rígido y encontrar tu propio camino. Juzga por ti mismo en vez de seguir ciegamente. Un enfoque no convencional puede ser la respuesta.'},
{id:'m6',name:'Los Amantes',en:'The Lovers',emoji:'💕',suit:'major',num:6,
up:'El amor llega, o estás ante una elección importante. Elige siguiendo lo que te dicta el corazón. Se está creando un verdadero vínculo y armonía. El encuentro con alguien que comparte tus valores puede cambiar tu vida. Sé honesto en el amor.',
down:'Hay discordia en la relación o un conflicto de valores. Si estás cediendo ante la tentación, piensa en qué es lo que realmente quieres. Da un paso atrás antes de tomar una decisión equivocada.'},
{id:'m7',name:'El Carro',en:'The Chariot',emoji:'⚡',suit:'major',num:7,
up:'¡Es momento de superar los obstáculos con una voluntad firme! No te detengas, sigue avanzando. La determinación y la concentración traen la victoria. Si dominas las fuerzas opuestas en armonía, alcanzarás tu objetivo. Puedes ganar.',
down:'Estás perdiendo el rumbo y vacilando. Las emociones te controlan y pierdes el dominio, o intentas hacer demasiado a la vez y te agota. Detente un momento y reorienta tu dirección.'},
{id:'m8',name:'La Fuerza',en:'Strength',emoji:'🦁',suit:'major',num:8,
up:'La fuerza suave vence a la fuerza bruta. Domina la situación con paciencia y coraje. No reprimas la ira o el miedo, envuélvelos con suavidad. Domar a la bestia interior no es violencia, es amor. Eres mucho más fuerte de lo que crees.',
down:'Has perdido la confianza y te has vuelto débil. Las emociones te abruman o caes en la autoduda. Despierta tu fuerza interior de nuevo. No te rindas — hay un león dentro de ti.'},
{id:'m9',name:'El Ermitaño',en:'The Hermit',emoji:'🔦',suit:'major',num:9,
up:'Necesitas tiempo a solas. Aléjate del ruido y explora tu interior. La respuesta no está afuera, sino adentro. Es un período en que puedes obtener una sabiduría profunda a través de la meditación y la reflexión. La soledad no es soledad, es autodescubrimiento.',
down:'Has estado aislado durante demasiado tiempo. Estás encerrado en tus propios pensamientos, desconectado del mundo. Es momento de volver a conectar con las personas. Pedir ayuda no es debilidad.'},
{id:'m10',name:'La Rueda de la Fortuna',en:'Wheel of Fortune',emoji:'🎡',suit:'major',num:10,
up:'¡La rueda del destino gira! Se acercan grandes cambios y buena fortuna. No dejes pasar la oportunidad. Es un punto de inflexión donde el ciclo de la vida cambia. Déjate llevar por la corriente. Las cosas buenas pueden suceder en cadena.',
down:'La mala suerte llega o te resistes al cambio. Pero recuerda — la rueda siempre gira. Los malos momentos también pasan. Déjate llevar y ten paciencia.'},
{id:'m11',name:'La Justicia',en:'Justice',emoji:'⚖️',suit:'major',num:11,
up:'Llega un resultado justo. Actuar con verdad y honestidad trae buenos resultados. Si hay problemas legales, pueden resolverse favorablemente. La ley de causa y efecto está en acción. Toma la decisión correcta.',
down:'Estás en una situación injusta o evadiendo responsabilidades. La mentira puede salir a la luz, así que enfrenta la verdad. Reflexiona si estás tomando decisiones sesgadas.'},
{id:'m12',name:'El Colgado',en:'The Hanged Man',emoji:'🙃',suit:'major',num:12,
up:'Si lo ves desde otro ángulo, verás la respuesta. Ahora es tiempo de observar y esperar, no de actuar. No es una renuncia, sino una pausa para obtener una nueva perspectiva. Paradójicamente, al soltar se puede ganar. El sacrificio eventualmente trae una gran recompensa.',
down:'Estás agotado de una espera sin sentido. Si la situación está estancada, necesitas cambiar de perspectiva o tomar acción. Deja de hacer el mártir.'},
{id:'m13',name:'La Muerte',en:'Death',emoji:'💀',suit:'major',num:13,
up:'El fin es un nuevo comienzo. No temas — esto no es una muerte física, sino una transformación. Debes soltar lo viejo para que llegue lo nuevo. Una relación, trabajo o hábito está terminando, pero es un proceso necesario. La mariposa debe morir como oruga para nacer.',
down:'Te resistes a un cambio necesario. No puedes terminar lo que debe terminar y te aferras a ello. Suéltalo. Cuanto más rechaces el cambio, más se prolonga el dolor.'},
{id:'m14',name:'La Templanza',en:'Temperance',emoji:'🌊',suit:'major',num:14,
up:'Es tiempo de equilibrio y armonía. Evita los extremos y mantén la moderación. La paciencia y un avance lento traen buenos resultados. Es el momento en que brilla tu capacidad de mezclar elementos diferentes de forma armoniosa. Cuida también tu salud física y mental.',
down:'Has perdido el equilibrio y te has inclinado hacia un lado. Ten cuidado con el exceso: beber, comer, trabajar en demasía. La impaciencia puede arruinar las cosas. Recupera el equilibrio.'},
{id:'m15',name:'El Diablo',en:'The Devil',emoji:'😈',suit:'major',num:15,
up:'Estás obsesionado o adicto a algo. Estás atado a lo material, al placer o a una relación. Pero esas cadenas las forjaste tú mismo, y tú mismo puedes romperlas. Mira de frente a tu sombra. Solo reconociéndola podrás liberarte.',
down:'¡Estás escapando de la esclavitud! Te estás liberando de malos hábitos o relaciones tóxicas. Recupera tu libertad. Ya no hay nada que temer.'},
{id:'m16',name:'La Torre',en:'The Tower',emoji:'🗼',suit:'major',num:16,
up:'Pueden venir cambios repentinos o conmociones. Lo que habías construido puede derrumbarse, pero es lo que estaba edificado sobre bases falsas lo que cae. Tras la destrucción puedes construir algo más sólido. La verdad se revela como un rayo.',
down:'Intentas evitar un colapso inevitable. Pero si lo que debe caer no cae, vendrá un desastre mayor. Acepta el cambio.'},
{id:'m17',name:'La Estrella',en:'The Star',emoji:'⭐',suit:'major',num:17,
up:'Es la luz tranquila de las estrellas tras la tormenta. La esperanza regresa. Las heridas sanan y surge la inspiración. El universo te apoya, así que no abandones tus sueños. Muéstrate tal como eres en verdad. Estás brillando.',
down:'Has perdido la esperanza y estás desanimado. Pero las estrellas siempre están ahí, aunque las nubes las cubran. Recupera la fe en ti mismo. Aún es pronto para rendirse.'},
{id:'m18',name:'La Luna',en:'The Moon',emoji:'🌙',suit:'major',num:18,
up:'Es una época de niebla en la que nada es del todo claro. Confía en tu intuición, pero no caigas en ilusiones. Presta atención a los mensajes de tu inconsciente. Los sueños pueden darte pistas importantes. Si enfrentas tus miedos, desaparecerán.',
down:'La niebla se disipa y la verdad comienza a verse. La confusión se resuelve y las cosas se aclaran. Lo oculto saldrá a la luz, prepárate.'},
{id:'m19',name:'El Sol',en:'The Sun',emoji:'☀️',suit:'major',num:19,
up:'¡Rebosas de energía brillante y cálida! Es época de éxito, alegría y vitalidad. Brilla con confianza. Disfruta de la alegría con la pureza de un niño. La oscuridad ha pasado y el sol ha salido. ¡Pronto habrá algo que celebrar!',
down:'El éxito llega, pero puede retrasarse un poco. Te falta confianza o no estás sintiendo suficiente alegría. Mantén una actitud positiva. El sol siempre sale.'},
{id:'m20',name:'El Juicio',en:'Judgement',emoji:'📯',suit:'major',num:20,
up:'Estás en un punto de inflexión de tu vida. Es momento de mirar atrás y hacer las paces con el pasado. Descubre tu vocación y renace. El perdón y la liberación están ocurriendo. Responde al llamado de tu interior. Estás listo para ascender a un nivel superior.',
down:'Estás atrapado en la autoduda y no puedes liberarte del pasado. No te quedes encadenado al arrepentimiento. Perdónate a ti mismo y sigue adelante. Hay una segunda oportunidad.'},
{id:'m21',name:'El Mundo',en:'The World',emoji:'🌍',suit:'major',num:21,
up:'¡Un gran ciclo se ha completado! Has alcanzado tu objetivo y llegado a la plenitud. ¡Felicitaciones! Los viajes, la expansión y nuevas posibilidades se abren. Un capítulo termina y uno nuevo comienza.',
down:'Casi has llegado, pero falta el último paso. Necesitas terminar de completar el ciclo. No te rindas, el final está a la vista. Sacúdete la insatisfacción por lo incompleto y da lo mejor de ti.'},

// ═══════════════════════════════════════
// Arcanos Menores — Bastos (fuego)
// ═══════════════════════════════════════
{id:'wA',name:'As de Bastos',en:'Ace of Wands',emoji:'🔥',suit:'wands',num:1,
up:'¡Surge una nueva pasión e inspiración! Época de explosión de energía creativa. El momento óptimo para iniciar nuevos proyectos.',
down:'Pérdida de motivación, incapacidad para comenzar. Tienes ideas pero no puedes convertirlas en acción.'},
{id:'w2',name:'Dos de Bastos',en:'Two of Wands',emoji:'🔥',suit:'wands',num:2,
up:'Es momento de planificar el futuro y ver el panorama general. El mundo está en tus manos. El momento de la decisión.',
down:'Miedo a los planes, resistencia a salir de la zona conocida. Estás postergando la decisión.'},
{id:'w3',name:'Tres de Bastos',en:'Three of Wands',emoji:'🔥',suit:'wands',num:3,
up:'Los resultados de tu esfuerzo empiezan a verse. Oportunidades de expansión y crecimiento. Llegan buenas noticias desde lejos o del extranjero.',
down:'Decepción porque los resultados no son los esperados. Se necesita paciencia.'},
{id:'w4',name:'Cuatro de Bastos',en:'Four of Wands',emoji:'🔥',suit:'wands',num:4,
up:'¡Época de celebración y alegría! Hay motivos de festejo: bodas, fiestas, mudanzas. Se ha creado una base estable.',
down:'Entorno doméstico inestable, celebraciones retrasadas. Los cimientos se tambalean.'},
{id:'w5',name:'Cinco de Bastos',en:'Five of Wands',emoji:'🔥',suit:'wands',num:5,
up:'Época de competencia y conflictos. Pero es una competencia sana para el crecimiento. Mantén tu posición.',
down:'Evita las peleas sin sentido. El compromiso y la cooperación son la respuesta.'},
{id:'w6',name:'Seis de Bastos',en:'Six of Wands',emoji:'🔥',suit:'wands',num:6,
up:'¡Victoria y reconocimiento! El esfuerzo es recompensado y los elogios llueven. Ten confianza en ti mismo.',
down:'Sensación de no ser reconocido, cuidado con la arrogancia. Mantén la humildad.'},
{id:'w7',name:'Siete de Bastos',en:'Seven of Wands',emoji:'🔥',suit:'wands',num:7,
up:'Es momento de enfrentar el desafío. Mantén firme tu posición. Si no te rindes, puedes ganar.',
down:'Sensación de estar abrumado, impulso de rendirse. La retirada estratégica también es una opción.'},
{id:'w8',name:'Ocho de Bastos',en:'Eight of Wands',emoji:'🔥',suit:'wands',num:8,
up:'¡Las cosas avanzan rápido! Noticias, viajes, cambios que ocurren de repente. Súbete a la corriente.',
down:'Retrasos, frustraciones, espera. Las cosas avanzan más lento de lo esperado.'},
{id:'w9',name:'Nueve de Bastos',en:'Nine of Wands',emoji:'🔥',suit:'wands',num:9,
up:'Es difícil, pero casi has llegado. Aguanta la última prueba. Eres suficientemente fuerte.',
down:'Agotamiento, burnout. Necesitas descansar. Forzar las cosas puede llevarte al colapso.'},
{id:'w10',name:'Diez de Bastos',en:'Ten of Wands',emoji:'🔥',suit:'wands',num:10,
up:'Llevas demasiadas cargas. La responsabilidad es buena, pero no necesitas hacerlo todo solo. Pide ayuda.',
down:'Es momento de dejar la carga. Libérate de responsabilidades innecesarias.'},
{id:'wP',name:'Paje de Bastos',en:'Page of Wands',emoji:'🔥',suit:'wands',num:11,
up:'¡Llegan noticias emocionantes! El comienzo de una nueva aventura. Sigue tu curiosidad.',
down:'Los planes se desbaratan o las noticias se retrasan.'},
{id:'wN',name:'Caballero de Bastos',en:'Knight of Wands',emoji:'🔥',suit:'wands',num:12,
up:'¡Es momento de lanzarse con pasión! Rebosas de espíritu aventurero y valentía. Actúa con audacia.',
down:'Precipitación, cuidado con las acciones temerarias. Corres sin dirección.'},
{id:'wQ',name:'Reina de Bastos',en:'Queen of Wands',emoji:'🔥',suit:'wands',num:13,
up:'¡Energía llena de confianza y atractivo! Ejerce un liderazgo cálido pero fuerte.',
down:'Celos, comportamiento egocéntrico. Reconoce también la luz de los demás.'},
{id:'wK',name:'Rey de Bastos',en:'King of Wands',emoji:'🔥',suit:'wands',num:14,
up:'Con visión y liderazgo lograrás grandes cosas. Guía a las personas con tu carisma.',
down:'Autoritario, déspota. No abuses del poder.'},

// ═══════════════════════════════════════
// Arcanos Menores — Copas (agua)
// ═══════════════════════════════════════
{id:'cA',name:'As de Copas',en:'Ace of Cups',emoji:'💧',suit:'cups',num:1,
up:'¡Comienza un nuevo amor, el inicio de las emociones! Época en que el corazón se llena. Estás listo para dar y recibir amor.',
down:'Vacío emocional, incapacidad para aceptar el amor.'},
{id:'c2',name:'Dos de Copas',en:'Two of Cups',emoji:'💧',suit:'cups',num:2,
up:'Profundo vínculo y compañerismo. El amor verdadero o la amistad florecen. Una relación de respeto mutuo.',
down:'Desequilibrio en la relación, indicios de separación.'},
{id:'c3',name:'Tres de Copas',en:'Three of Cups',emoji:'💧',suit:'cups',num:3,
up:'¡Celebración, amistad, reuniones! Tiempo agradable con amigos. Las actividades sociales traen buena suerte.',
down:'Exceso de alcohol, libertinaje. Te estás perdiendo cosas importantes por los placeres.'},
{id:'c4',name:'Cuatro de Copas',en:'Four of Cups',emoji:'💧',suit:'cups',num:4,
up:'Aburrimiento, indiferencia. No estás viendo las oportunidades frente a ti. Voltea la mirada y descubre nuevas posibilidades.',
down:'Comienzas a aceptar nuevas oportunidades. Sal de la apatía.'},
{id:'c5',name:'Cinco de Copas',en:'Five of Cups',emoji:'💧',suit:'cups',num:5,
up:'Tristeza y pérdida. No te obsesiones con lo derramado. Si miras atrás, todavía queda algo.',
down:'En recuperación de la tristeza. Suelta el pasado y avanza.'},
{id:'c6',name:'Seis de Copas',en:'Six of Cups',emoji:'💧',suit:'cups',num:6,
up:'Nostalgia, recuerdos de la infancia, inocencia. Un antiguo vínculo puede regresar. Los buenos recuerdos del pasado traen sanación.',
down:'Apegado al pasado, incapaz de vivir el presente. Sigue adelante.'},
{id:'c7',name:'Siete de Copas',en:'Seven of Cups',emoji:'💧',suit:'cups',num:7,
up:'Abundan las ilusiones y las opciones. Pero no todo es real. Juzga de forma realista.',
down:'Despiertas de las ilusiones y tomas decisiones realistas.'},
{id:'c8',name:'Ocho de Copas',en:'Eight of Cups',emoji:'💧',suit:'cups',num:8,
up:'Es momento de abandonar lo que ya no te llena. Una renuncia valiente. Parte en busca de un significado más profundo.',
down:'Permaneces donde deberías irte. Suelta el apego.'},
{id:'c9',name:'Nueve de Copas',en:'Nine of Cups',emoji:'💧',suit:'cups',num:9,
up:'¡El deseo se cumple! Abundan la satisfacción y la felicidad. Agradece y disfruta la alegría. Los sueños se hacen realidad.',
down:'Vacío a pesar de la abundancia material. La verdadera felicidad está dentro de ti.'},
{id:'c10',name:'Diez de Copas',en:'Ten of Cups',emoji:'💧',suit:'cups',num:10,
up:'¡Felicidad perfecta! Familia, amor, armonía. Estado de plenitud emocional. El hogar feliz bajo el arcoíris.',
down:'Discordia familiar, relaciones que no cumplen las expectativas. No persigas la perfección.'},
{id:'cP',name:'Paje de Copas',en:'Page of Cups',emoji:'💧',suit:'cups',num:11,
up:'Llega un mensaje o propuesta emotiva. Confía en tu intuición. El inicio de nuevas emociones.',
down:'Inmadurez emocional. Expectativas poco realistas.'},
{id:'cN',name:'Caballero de Copas',en:'Knight of Cups',emoji:'💧',suit:'cups',num:12,
up:'¡Se acerca una propuesta romántica! Inspiración artística. Sé fiel a tus emociones.',
down:'Ilusiones poco realistas, cuidado con la manipulación emocional.'},
{id:'cQ',name:'Reina de Copas',en:'Queen of Cups',emoji:'💧',suit:'cups',num:13,
up:'Profunda empatía e intuición. La reina que gobierna el mar de las emociones. Sana con amor.',
down:'Abrumada por las emociones, dependencia emocional.'},
{id:'cK',name:'Rey de Copas',en:'King of Cups',emoji:'💧',suit:'cups',num:14,
up:'Sabiduría y equilibrio emocional. Liderazgo sereno y compasivo. Armonía entre emoción y razón.',
down:'Frialdad emocional, represión de sentimientos.'},

// ═══════════════════════════════════════
// Arcanos Menores — Espadas (viento)
// ═══════════════════════════════════════
{id:'sA',name:'As de Espadas',en:'Ace of Swords',emoji:'⚔️',suit:'swords',num:1,
up:'¡Verdad clara, un avance! Nuevas ideas surgen como un rayo. El momento de decidir.',
down:'Confusión, información errónea. Elimina lo que nubla tu juicio.'},
{id:'s2',name:'Dos de Espadas',en:'Two of Swords',emoji:'⚔️',suit:'swords',num:2,
up:'Estado de punto muerto sin poder tomar una decisión. No te vendas los ojos y mira la verdad de frente.',
down:'Con la información que sale a la luz, la decisión se vuelve posible.'},
{id:'s3',name:'Tres de Espadas',en:'Three of Swords',emoji:'⚔️',suit:'swords',num:3,
up:'Herida emocional, traición, separación. Duele, pero a través de este dolor creces. No reprimas tus sentimientos.',
down:'En recuperación de la herida. El dolor desaparece poco a poco.'},
{id:'s4',name:'Cuatro de Espadas',en:'Four of Swords',emoji:'⚔️',suit:'swords',num:4,
up:'Necesitas descanso. Retírate un momento de la batalla y recarga energías. La meditación y el descanso son la respuesta.',
down:'Estás esforzándote demasiado sin descansar. Riesgo de burnout.'},
{id:'s5',name:'Cinco de Espadas',en:'Five of Swords',emoji:'⚔️',suit:'swords',num:5,
up:'Ganar tiene un alto costo. Piensa si la victoria vale la pena. Usar métodos sucios trae arrepentimiento.',
down:'Momento de reconocer la derrota y aprender la lección. Baja la guardia del orgullo.'},
{id:'s6',name:'Seis de Espadas',en:'Six of Swords',emoji:'⚔️',suit:'swords',num:6,
up:'Pasas por un período difícil hacia un lugar mejor. El dolor de la transición pronto terminará.',
down:'No puedes irte y permaneces. Acepta el cambio.'},
{id:'s7',name:'Siete de Espadas',en:'Seven of Swords',emoji:'⚔️',suit:'swords',num:7,
up:'Necesitas estrategia. Aborda las cosas con sabiduría en vez de atacar de frente. Pero el engaño siempre acaba descubriéndose.',
down:'El engaño es descubierto. La honestidad es la mejor estrategia.'},
{id:'s8',name:'Ocho de Espadas',en:'Eight of Swords',emoji:'⚔️',suit:'swords',num:8,
up:'Sientes que estás atrapado, pero en realidad esas ataduras las creaste tú mismo. Si te quitas la venda, puedes escapar.',
down:'Comienzas a liberarte de las restricciones. Avanza hacia la libertad.'},
{id:'s9',name:'Nueve de Espadas',en:'Nine of Swords',emoji:'⚔️',suit:'swords',num:9,
up:'Ansiedad, pesadillas, preocupaciones. El tormento de no poder dormir por la noche. Pero la mayoría de los miedos no son reales.',
down:'Lo peor está pasando. Suelta las preocupaciones.'},
{id:'s10',name:'Diez de Espadas',en:'Ten of Swords',emoji:'⚔️',suit:'swords',num:10,
up:'Has tocado fondo. Ya no puede empeorar. Pero esto es el fin y también un nuevo comienzo. El sol está saliendo.',
down:'Indicios de recuperación tras lo peor. La fuerza para levantarte de nuevo está surgiendo.'},
{id:'sP',name:'Paje de Espadas',en:'Page of Swords',emoji:'⚔️',suit:'swords',num:11,
up:'Curiosidad y aguda capacidad de observación. Nueva información o noticias. Desvela la verdad.',
down:'Chismes, habladurías, comunicación inmadura.'},
{id:'sN',name:'Caballero de Espadas',en:'Knight of Swords',emoji:'⚔️',suit:'swords',num:12,
up:'¡Acción rápida y decidida! Avanza sin vacilar. Lucha por la justicia.',
down:'Precipitación, arremetida temeraria. Piensa antes de actuar.'},
{id:'sQ',name:'Reina de Espadas',en:'Queen of Swords',emoji:'⚔️',suit:'swords',num:13,
up:'Juicio claro e independencia. Sabiduría que no se deja llevar por las emociones. Mira la verdad de frente.',
down:'Demasiada frialdad, impresión de ser glacial. La empatía también es necesaria.'},
{id:'sK',name:'Rey de Espadas',en:'King of Swords',emoji:'⚔️',suit:'swords',num:14,
up:'Autoridad intelectual y juicio justo. Toma decisiones con lógica y ética.',
down:'Juicio autoritario, inhumano. No solo uses la cabeza, usa también el corazón.'},

// ═══════════════════════════════════════
// Arcanos Menores — Oros (tierra)
// ═══════════════════════════════════════
{id:'pA',name:'As de Oros',en:'Ace of Pentacles',emoji:'💰',suit:'pentacles',num:1,
up:'¡Nueva oportunidad financiera! La semilla de la inversión, el empleo o el negocio. El inicio de la abundancia material.',
down:'Perder una oportunidad o cuidado con pérdidas financieras.'},
{id:'p2',name:'Dos de Oros',en:'Two of Pentacles',emoji:'💰',suit:'pentacles',num:2,
up:'Mantener el equilibrio. Gestionando múltiples cosas a la vez. Responde con flexibilidad.',
down:'A punto de perder el equilibrio y desmoronarte. Establece prioridades.'},
{id:'p3',name:'Tres de Oros',en:'Three of Pentacles',emoji:'💰',suit:'pentacles',num:3,
up:'El trabajo en equipo y la cooperación producen resultados. Tu especialidad es reconocida. Trabajar juntos da mejores frutos.',
down:'Intentas hacerlo solo y fracasas. Comprende el valor de la cooperación.'},
{id:'p4',name:'Cuatro de Oros',en:'Four of Pentacles',emoji:'💰',suit:'pentacles',num:4,
up:'Estabilidad y seguridad. Estás financieramente seguro, pero aferrarte demasiado te hace perder nuevas oportunidades.',
down:'Tacañería, apego excesivo a lo material. Compartir trae más de vuelta.'},
{id:'p5',name:'Cinco de Oros',en:'Five of Pentacles',emoji:'💰',suit:'pentacles',num:5,
up:'Dificultades económicas, sensación de aislamiento. Es un período duro, pero la ayuda está cerca. Levanta la cabeza.',
down:'Lo peor está pasando. La luz de la recuperación se asoma.'},
{id:'p6',name:'Seis de Oros',en:'Six of Pentacles',emoji:'💰',suit:'pentacles',num:6,
up:'Equilibrio en el dar y recibir. La generosidad trae bendiciones. Es momento de dar o recibir ayuda.',
down:'Desequilibrio en el dar y recibir. Cuidado con las relaciones que se inclinan hacia un solo lado.'},
{id:'p7',name:'Siete de Oros',en:'Seven of Pentacles',emoji:'💰',suit:'pentacles',num:7,
up:'Sembrando y esperando resultados. Se necesita paciencia. El esfuerzo siempre da frutos.',
down:'Impaciencia, frustración por no ver resultados. No te rindas, ya casi llegas.'},
{id:'p8',name:'Ocho de Oros',en:'Eight of Pentacles',emoji:'💰',suit:'pentacles',num:8,
up:'¡Espíritu artesanal! Época de pulir habilidades. El esfuerzo constante forma al experto.',
down:'Agotamiento por la repetición, pérdida de motivación. Recuerda tu objetivo.'},
{id:'p9',name:'Nueve de Oros',en:'Nine of Pentacles',emoji:'💰',suit:'pentacles',num:9,
up:'¡Independencia y abundancia! Disfruta el resultado de tu esfuerzo propio. Una vida con clase. Te lo has ganado.',
down:'Ansiedad ante la independencia, dependiendo de otros.'},
{id:'p10',name:'Diez de Oros',en:'Ten of Pentacles',emoji:'💰',suit:'pentacles',num:10,
up:'¡Plenitud material! Abundancia familiar, herencia, estabilidad a largo plazo. Riqueza y felicidad que se transmiten de generación en generación.',
down:'Conflictos financieros familiares, problemas de herencia. Las relaciones importan más que lo material.'},
{id:'pP',name:'Paje de Oros',en:'Page of Pentacles',emoji:'💰',suit:'pentacles',num:11,
up:'Noticias de un nuevo aprendizaje u oportunidad financiera. El estudio diligente trae resultados.',
down:'Planes poco realistas, pereza.'},
{id:'pN',name:'Caballero de Oros',en:'Knight of Pentacles',emoji:'💰',suit:'pentacles',num:12,
up:'Avance firme y diligente. Progreso lento pero seguro. La constancia vence.',
down:'Demasiado lento, conservador. A veces también hace falta audacia.'},
{id:'pQ',name:'Reina de Oros',en:'Queen of Pentacles',emoji:'💰',suit:'pentacles',num:13,
up:'Sabiduría práctica y abundancia cálida. Energía pragmática y generosa. Equilibrio entre hogar y finanzas.',
down:'Falta de autocuidado, adicción al trabajo.'},
{id:'pK',name:'Rey de Oros',en:'King of Pentacles',emoji:'💰',suit:'pentacles',num:14,
up:'¡Éxito financiero y estabilidad! Habilidad para los negocios y liderazgo práctico. Cosechas una abundante recompensa.',
down:'Avaricia, materialismo. El dinero no lo es todo.'}
];

// ═══════════════════════════════════════
// UI Textos (modificar solo esta sección al traducir)
// ═══════════════════════════════════════
const TAROT_UI = {
    pageTitle: "🃏 Tarot",
    pageSubtitle: "Saca una carta y lee tu destino",
    modeNormal: "🃏 Tarot Normal",
    modeOshi: "💜 Tarot Oshi",
    spreadOne: "💫 <strong>Una carta</strong> <span style=\"font-size:12px;color:#888;margin-left:8px;\">Respuesta rápida · 1 carta</span>",
    spreadThree: "⏳ <strong>Pasado · Presente · Futuro</strong> <span style=\"font-size:12px;color:#888;margin-left:8px;\">Flujo del tiempo · 3 cartas</span>",
    spreadFive: "⭐ <strong>Lectura Profunda</strong> <span style=\"font-size:12px;color:#888;margin-left:8px;\">Análisis detallado · 5 cartas</span>",
    questionText: "✨ Piensa en lo que quieres saber<br>y elige una carta ✨",
    questionSub: "Las cartas las elige tu inconsciente",
    oshiTitle: "💜 Escribe el nombre de tu oshi",
    oshiPlaceholder: "Ej: Gojo Satoru, Levi, Kamina...",
    oshiHint: "¡Cualquiera de anime, manga, juego o idol está bien!",
    oshiQuestionText: "✨ Piensa en esa persona<br>y elige una carta ✨",
    oshiQuestionSub: "Las cartas revelan los sentimientos ocultos de tu oshi",
    btnShuffle: "🃏 Barajar cartas",
    btnShuffleOshi: "💜 Barajar cartas",
    btnReshuffle: "🔄 Barajar de nuevo",
    pickInstruction: "Elige <strong>{n} carta(s)</strong>",
    pickMore: "Elige <strong>{n} más</strong>",
    pickDone: "✨ ¡Has elegido todas las cartas!",
    disclaimer: "🃏 El tarot es una herramienta de entretenimiento y reflexión personal. Para decisiones importantes, consulta a un profesional.",
    positions3: ["Pasado", "Presente", "Futuro"],
    positions5: ["Situación actual", "Desafío/Obstáculo", "Influencia del pasado", "Futuro cercano", "Resultado final"],
    oshiPositions3: ["Cuando te vio por primera vez", "Lo que piensa de ti ahora", "Lo que te deparará en el futuro"],
    oshiPositions5: ["Primera impresión", "Lo que está ocultando", "Sus verdaderos sentimientos", "Lo que desea de ti", "El futuro de los dos"],
    todayCard: "La carta del día",
    oshiOneCard: "Lo que dice {name}",
    reversed: "Invertida ↓",
    upright: "Derecha ↑",
    summaryTitle: "🃏 Interpretación general",
    oshiSummaryTitle: "💜 Los sentimientos de {name} en conjunto",
    summaryPositive: "Predomina la energía positiva. Ten confianza en ti mismo.",
    summaryChallenge: "Es un período de desafíos, pero las cartas invertidas también indican crecimiento interior.",
    summaryMainCard: "La carta clave de esta lectura es <strong>{emoji} {card}</strong>.",
    summaryReversed: "Salió invertida, así que ten cuidado con {text}.",
    summaryUpright: "La energía de {text} es fuerte.",
    summaryOverall: "En total, {up} cartas están en posición normal y {down} en posición invertida.",
    oshiMainCard: "La carta clave es <strong>{emoji} {card}</strong>.",
    oshiCount: "{up} en posición normal, {down} invertidas.",
    oshiPositive: "Según {name}, en general tiene sentimientos positivos hacia ti. Dice que puedes abrirle tu corazón y acercarte.",
    oshiChallenge: "Según {name}, está en medio de sentimientos complejos. Pero en lo más profundo de su corazón te valora. Dice que solo necesita tiempo.",
    defaultOshiName: "esa persona",
    suitLabels: {major:"Mayor", wands:"Bastos", cups:"Copas", swords:"Espadas", pentacles:"Oros"},
    share: "Compartir:",
    copyUrl: "Copiar URL",
};

// ═══════════════════════════════════════
// Modo Oshi — Arcanos Mayores
// ═══════════════════════════════════════
const OSHI_READINGS = {
    0: {up:"Según {name}, contigo se lanzaría a cualquier aventura. Siente una curiosidad pura hacia ti y se está acercando sin miedo.",down:"Según {name}, quiere acercarse pero todavía no está listo. Tiene ganas, pero está esperando el momento."},
    1: {up:"Según {name}, sintió algo especial en ti desde el principio. Tu sola presencia le inspira.",down:"Según {name}, quiere mostrarte su corazón sincero pero no sabe cómo."},
    2: {up:"Según {name}, aunque no lo dice, piensa mucho en ti. Te está observando en silencio.",down:"Según {name}, tiene sentimientos que te oculta. Solo es que aún no está listo para mostrarlos."},
    3: {up:"Según {name}, se siente más a gusto cuando está contigo. Eres como un refugio para él.",down:"Según {name}, quiere apoyarse en ti pero el orgullo le impide hablar primero."},
    4: {up:"Según {name}, quiere protegerte. Detrás de su imagen fuerte esconde un corazón cálido hacia ti.",down:"Según {name}, se arrepiente de haber sido demasiado duro contigo."},
    5: {up:"Según {name}, te apoya de verdad en tu crecimiento.",down:"Según {name}, se ha dado cuenta de que la manera tradicional no llega hasta ti."},
    6: {up:"Según {name}, siente algo especial por ti. Una atracción distinta a cualquier otra.",down:"Según {name}, siente un conflicto interno en la relación contigo. Pero en lo más profundo te desea."},
    7: {up:"Según {name}, haría cualquier cosa por ti. Eres su motivación para seguir adelante.",down:"Según {name}, ha perdido el rumbo. Una sola palabra tuya podría ser de gran ayuda."},
    8: {up:"Según {name}, le atraes por tu lado fuerte pero a la vez suave.",down:"Según {name}, le da miedo mostrarse débil ante ti."},
    9: {up:"Según {name}, en sus momentos de soledad piensa en ti. Siente una profunda nostalgia.",down:"Según {name}, se está alejando a propósito, pero no es porque no le gustes. Solo necesita tiempo para ordenar sus sentimientos."},
    10: {up:"Según {name}, siente que conocerte fue el destino.",down:"Según {name}, siente que el momento aún no es el correcto. Pero el hilo del destino no se ha roto."},
    11: {up:"Según {name}, los sentimientos que tiene hacia ti son genuinos y sin mentiras.",down:"Según {name}, lamenta no haber sido justo contigo en el pasado."},
    12: {up:"Según {name}, estaría dispuesto a sacrificarse por ti. Eres alguien tan valioso para él.",down:"Según {name}, está esperando a que seas tú quien tienda la mano primero."},
    13: {up:"Según {name}, la relación contigo está pasando a una nueva etapa.",down:"Según {name}, quiere cerrar la relación anterior. Es un cambio para construir algo mejor."},
    14: {up:"Según {name}, cuando está contigo su corazón se serena. Siente el equilibrio perfecto entre los dos.",down:"Según {name}, está intentando encontrar el equilibrio emocional."},
    15: {up:"Según {name}, se siente fuertemente atraído hacia ti. Un atractivo al que no puede resistirse.",down:"Según {name}, intentó ordenar sus sentimientos hacia ti, pero no es fácil."},
    16: {up:"Según {name}, tú cambiaste su visión del mundo.",down:"Según {name}, se ha dado cuenta de que los sentimientos que tiene por ti son completamente distintos a lo que esperaba."},
    17: {up:"Según {name}, para él eres como una estrella en la oscuridad.",down:"Según {name}, perdió la esperanza por un momento, pero pensar en ti le da fuerzas para seguir."},
    18: {up:"Según {name}, siente algo hacia ti que no puede expresar con palabras.",down:"Según {name}, los sentimientos que estaban confusos empiezan a ordenarse. Ha comprendido su verdadero corazón hacia ti."},
    19: {up:"Según {name}, es más feliz cuando está contigo. Para él eres como el sol.",down:"Según {name}, quiere darte felicidad pero le cuesta expresarlo."},
    20: {up:"Según {name}, siente que todo lo que vivió antes fue el camino para encontrarte.",down:"Según {name}, se arrepiente de no haberte tratado mejor en el pasado."},
    21: {up:"Según {name}, siente que la relación contigo es perfecta. Son lo mejor el uno para el otro.",down:"Según {name}, siente que aún falta algo en la relación. Pero dice que están casi completos."}
};

// ═══════════════════════════════════════
// Modo Oshi — Arcanos Menores (por palo)
// ═══════════════════════════════════════
const OSHI_MINOR = {
    wands: {
        up: [
            "Según {name}, ha empezado a arder una nueva pasión hacia ti.",
            "Según {name}, está pensando en serio en un futuro contigo.",
            "Según {name}, el tiempo compartido contigo está dando frutos.",
            "Según {name}, estar contigo es como estar en una fiesta.",
            "Según {name}, quiere ser mejor persona por ti.",
            "Según {name}, quiere ser reconocido por ti.",
            "Según {name}, aceptaría cualquier desafío si es por ti.",
            "Según {name}, sus sentimientos hacia ti se están profundizando rápidamente.",
            "Según {name}, está agotado de proteger sus sentimientos hacia ti, pero no se rendirá.",
            "Según {name}, está cargando mucho por ti, pero no le importa porque eres tú.",
            "Según {name}, quiere contarte una noticia emocionante sobre ti.",
            "Según {name}, quiere confesarle sus sentimientos con valentía.",
            "Según {name}, se siente lleno de confianza cuando está frente a ti.",
            "Según {name}, quiere alcanzar grandes sueños contigo.",
        ],
        down: [
            "Según {name}, la pasión no se ha apagado, solo no sabe cómo expresarla.",
            "Según {name}, le da miedo el futuro contigo. Le asusta perderte.",
            "Según {name}, está inquieto porque los resultados no son los esperados, pero no tiene intención de rendirse.",
            "Según {name}, siente inestabilidad en la relación contigo.",
            "Según {name}, quiere evitar conflictos innecesarios.",
            "Según {name}, le duele sentir que no está siendo reconocido por ti.",
            "Según {name}, está cansado y necesita descansar un momento. Sus sentimientos no cambian.",
            "Según {name}, le frustra que las cosas avancen despacio.",
            "Según {name}, está al borde del agotamiento. Necesita una palabra tuya.",
            "Según {name}, le cuesta llevarlo solo. Quiere apoyarse en ti.",
            "Según {name}, tiene algo que decirte pero todavía no es el momento.",
            "Según {name}, se arrepiente de haber actuado de forma precipitada.",
            "Según {name}, perdió la confianza ante ti. Quiere recuperarla.",
            "Según {name}, quiere acercarse a ti con suavidad.",
        ]
    },
    cups: {
        up: [
            "Según {name}, están floreciendo nuevas emociones hacia ti.",
            "Según {name}, siente un profundo vínculo contigo.",
            "Según {name}, el tiempo que pasa contigo es el que más disfruta.",
            "Según {name}, acaba de darse cuenta de lo valioso que eres para él.",
            "Según {name}, sufrió por tu causa, pero eso le hizo ver cuánto te aprecia.",
            "Según {name}, guarda con cariño los recuerdos que tiene contigo.",
            "Según {name}, el tú real le gusta más que cualquier fantasía.",
            "Según {name}, quiere avanzar hacia una relación más profunda.",
            "Según {name}, siente que su deseo de estar contigo se está cumpliendo.",
            "Según {name}, estar contigo es la felicidad perfecta.",
            "Según {name}, quiere hacerte una confesión sincera.",
            "Según {name}, quiere acercarse a ti de forma romántica.",
            "Según {name}, conoce tus sentimientos sin que lo digas.",
            "Según {name}, quiere crecer contigo.",
        ],
        down: [
            "Según {name}, se siente emocionalmente vacío. Dice que tú puedes llenarlo.",
            "Según {name}, siente que el equilibrio de la relación se ha roto.",
            "Según {name}, estaba dejando escapar lo importante por los placeres.",
            "Según {name}, ha empezado a aceptar nuevas oportunidades.",
            "Según {name}, está saliendo de la tristeza del pasado. Dice que tú le has sanado.",
            "Según {name}, reconoce que estaba aferrado al pasado. Ahora mirará al frente.",
            "Según {name}, ha despertado de las ilusiones y ha empezado a verte tal como eres.",
            "Según {name}, sabe que debería irse pero le queda nostalgia.",
            "Según {name}, se ha dado cuenta de que tu corazón importa más que lo material.",
            "Según {name}, estuvo a punto de perderte por buscar la perfección.",
            "Según {name}, reflexiona sobre su inmadurez emocional.",
            "Según {name}, quiere verte tal como eres.",
            "Según {name}, le cuesta estar abrumado por las emociones. Necesita tu serenidad.",
            "Según {name}, quiere ser honesto contigo.",
        ]
    },
    swords: {
        up: [
            "Según {name}, ha llegado a una conclusión clara sobre ti.",
            "Según {name}, pronto tendrá una respuesta.",
            "Según {name}, sufrió por ti, pero ese dolor se convirtió en crecimiento.",
            "Según {name}, descansa pensando en ti.",
            "Según {name}, no quiere tener peleas innecesarias contigo.",
            "Según {name}, está pasando por un período difícil para acercarse a ti.",
            "Según {name}, a partir de ahora se acercará con honestidad.",
            "Según {name}, está intentando derribar el muro que él mismo construyó para acercarse a ti.",
            "Según {name}, no puede dormir de preocupación por ti.",
            "Según {name}, tocó fondo pero está levantándose. Dice que tú eres la razón.",
            "Según {name}, quiere conocerte más.",
            "Según {name}, ya no va a dudar más.",
            "Según {name}, está reconociendo tu verdadero valor.",
            "Según {name}, quiere guiar la relación contigo con sabiduría.",
        ],
        down: [
            "Según {name}, está confundido.",
            "Según {name}, ha empezado a ver la respuesta.",
            "Según {name}, está recuperándose de una herida.",
            "Según {name}, desearía que le dejaras descansar.",
            "Según {name}, está bien mostrarse débil ante ti.",
            "Según {name}, aceptará el cambio si estás tú a su lado.",
            "Según {name}, a partir de ahora se acercará con honestidad.",
            "Según {name}, ha empezado a liberarse de los límites que él mismo se impuso.",
            "Según {name}, ha empezado a soltar las preocupaciones. Dice que es gracias a ti.",
            "Según {name}, lo peor ya está pasando.",
            "Según {name}, dice que no hagas caso a los rumores sin importancia.",
            "Según {name}, irá poco a poco.",
            "Según {name}, quiere sentir calor.",
            "Según {name}, también quiere escuchar tu opinión.",
        ]
    },
    pentacles: {
        up: [
            "Según {name}, quiere invertir en serio en la relación contigo.",
            "Según {name}, aunque está ocupado, tú eres la prioridad.",
            "Según {name}, trabajar contigo produce los mejores resultados.",
            "Según {name}, quiere proteger la relación contigo de forma segura.",
            "Según {name}, en este período difícil le consuela que estés cerca.",
            "Según {name}, quiere darte todo sin escatimar.",
            "Según {name}, seguro que vendrán buenos resultados.",
            "Según {name}, está esforzándose por ser mejor persona para ti.",
            "Según {name}, quiere construir una relación próspera contigo.",
            "Según {name}, quiere estar contigo por mucho tiempo.",
            "Según {name}, quiere conocerte poco a poco.",
            "Según {name}, se está acercando lento pero seguro.",
            "Según {name}, quiere encontrar un equilibrio a la vez práctico y cálido.",
            "Según {name}, quiere alcanzar un gran éxito contigo.",
        ],
        down: [
            "Según {name}, lamenta haber perdido la oportunidad.",
            "Según {name}, dice que tú le detuviste cuando iba a caer.",
            "Según {name}, dice que estará contigo.",
            "Según {name}, aprenderá a soltar.",
            "Según {name}, ve la luz de la recuperación.",
            "Según {name}, quiere volver a encontrar el equilibrio.",
            "Según {name}, ya casi han llegado. Dice que no te rindas.",
            "Según {name}, tú le has dado un nuevo impulso.",
            "Según {name}, si estás a su lado, estará bien.",
            "Según {name}, la relación contigo importa más que lo material.",
            "Según {name}, pondrá los pies en la tierra.",
            "Según {name}, lo siente por ir lento, pero sus sentimientos son seguros.",
            "Según {name}, se recuperará y volverá a ti.",
            "Según {name}, se acercará a ti de corazón.",
        ]
    }
};

function convertToOshi(card, name) {
    const suitData = OSHI_MINOR[card.suit];
    if (!suitData) return card.reversed ? card.down : card.up;
    const idx = Math.min(card.num - 1, 13);
    const texts = card.reversed ? suitData.down : suitData.up;
    return (texts[idx] || texts[0]).replace(/\{name\}/g, name);
}
