// 78 cartas de tarô (22 Arcanos Maiores + 56 Arcanos Menores)
const TAROT_CARDS = [
// ═══════════════════════════════════════
// Arcanos Maiores (0~21)
// ═══════════════════════════════════════
{id:'m0',name:'O Louco',en:'The Fool',emoji:'🃏',suit:'major',num:0,
up:'Um novo começo está diante de você. Deixe o medo de lado e dê o primeiro passo. Agora não é hora de calcular — siga sua intuição. Mergulhe no mundo com o coração puro. Uma aventura inesperada espera por você. Não tema o fracasso — o Louco ri enquanto pula à beira do abismo.',
down:'Você está agindo de forma imprudente demais. Agir sem preparo pode levar a grandes erros. Pense mais uma vez e ouça os conselhos de quem está ao seu redor. Liberdade não é o mesmo que imprudência. Cuidado com julgamentos precipitados.'},
{id:'m1',name:'O Mago',en:'The Magician',emoji:'🪄',suit:'major',num:1,
up:'Todas as ferramentas e talentos de que você precisa já estão em você. Agora é hora de se concentrar e agir. Com força de vontade e criatividade, você pode realizar o que deseja. Como o Mago que une o céu e a terra, transforme ideias em realidade. Suas palavras e ações têm poder.',
down:'Você está desperdiçando seu talento ou usando suas habilidades no lugar errado. A falta de confiança pode estar fazendo você perder oportunidades. Ou suas palavras e ações não estão alinhadas. Reconecte-se com sua autenticidade.'},
{id:'m2',name:'A Sacerdotisa',en:'The High Priestess',emoji:'🌙',suit:'major',num:2,
up:'A resposta já está dentro de você. Confie na intuição, não na lógica. Se você ouvir em silêncio sua voz interior, verdades ocultas se revelarão. Este é o momento da observação, não da ação. Leia o que está abaixo da superfície. Uma sabedoria misteriosa está guiando você.',
down:'Você está ignorando sua intuição e dependendo apenas das aparências. Ou há uma verdade que você conhece mas está evitando. Identifique as motivações ocultas. É preciso olhar mais fundo.'},
{id:'m3',name:'A Imperatriz',en:'The Empress',emoji:'🌺',suit:'major',num:3,
up:'É uma época de abundância e amor. Cuide-se e desfrute dos seus sentidos. A energia criativa está alta — é um ótimo momento para criar coisas novas. A natureza recarrega sua energia. Envolva as pessoas ao seu redor com amor maternal. Buscar beleza não é luxo.',
down:'Você está negligenciando o autocuidado ou dependendo demais dos outros. Se sentir um bloqueio criativo, busque inspiração na natureza. Tome cuidado com ciúme ou possessividade.'},
{id:'m4',name:'O Imperador',en:'The Emperor',emoji:'👑',suit:'major',num:4,
up:'É hora de uma abordagem sistemática e resoluta. Estabeleça disciplina e ordem para alcançar estabilidade. Exerça liderança e aja com responsabilidade. Julgue com a razão, não com a emoção. As regras que você estabelece também oferecem segurança aos outros.',
down:'Você está sendo rígido demais ou controlador. Impor regras sem flexibilidade pode gerar resistência. Reflita se está abusando de sua autoridade. Às vezes, recuar é a verdadeira força.'},
{id:'m5',name:'O Hierofante',en:'The Hierophant',emoji:'🙏',suit:'major',num:5,
up:'A resposta pode estar nos valores tradicionais ou em um mentor. É uma época de aprendizado e crescimento espiritual. Encontre um senso de pertencimento na comunidade. Seguir métodos comprovados é seguro. O ensino mútuo promove o crescimento de todos.',
down:'O modo tradicional de fazer as coisas já não funciona para você. É hora de sair do pensamento engessado e encontrar seu próprio caminho. Em vez de seguir cegamente, julgue por si mesmo. Uma abordagem não convencional pode ser a resposta.'},
{id:'m6',name:'Os Amantes',en:'The Lovers',emoji:'💕',suit:'major',num:6,
up:'O amor chega, ou você está diante de uma escolha importante. Siga o que seu coração diz. Está se formando um vínculo e uma harmonia genuínos. Um encontro com alguém que compartilha seus valores pode mudar sua vida. Seja honesto com o amor.',
down:'Há conflito no relacionamento ou choque de valores. Se estiver sendo tentado, pense no que realmente deseja. Dê um passo atrás antes de fazer a escolha errada.'},
{id:'m7',name:'O Carro',en:'The Chariot',emoji:'⚡',suit:'major',num:7,
up:'É hora de superar os obstáculos com forte determinação! Não pare — avance. A decisão e o foco trazem a vitória. Se você harmonizar forças opostas, alcançará seu objetivo. Você pode vencer.',
down:'Você está perdendo o rumo e vacilando. Está sendo controlado pelas emoções, perdendo o controle, ou tentando fazer coisas demais de uma vez e se esgotando. Pare por um momento e redefina sua direção.'},
{id:'m8',name:'A Força',en:'Strength',emoji:'🦁',suit:'major',num:8,
up:'A força suave supera a força bruta. Domine a situação com paciência e coragem. Não suprima a raiva ou o medo — envolva-os com suavidade. Domar a besta interior não é violência, é amor. Você é muito mais forte do que pensa.',
down:'Você perdeu a confiança e está se sentindo fraco. Está sendo dominado pelas emoções ou está em dúvida sobre si mesmo. Desperte sua força interior. Não desista — há um leão dentro de você.'},
{id:'m9',name:'O Eremita',en:'The Hermit',emoji:'🔦',suit:'major',num:9,
up:'Você precisa de um tempo a sós. Afaste-se do ruído e explore seu interior. A resposta está dentro, não fora. Este é o momento de obter sabedoria profunda por meio da meditação e reflexão. A solidão não é solidão — é autodescoberta.',
down:'Você está isolado há tempo demais. Preso nos seus próprios pensamentos, desconectado do mundo. É hora de se reconectar com as pessoas. Pedir ajuda não é fraqueza.'},
{id:'m10',name:'A Roda da Fortuna',en:'Wheel of Fortune',emoji:'🎡',suit:'major',num:10,
up:'A roda do destino está girando! Grandes mudanças e boa sorte se aproximam. Não perca a oportunidade. É um ponto de virada em que o ciclo da vida muda. Entregue-se ao fluxo. Coisas boas podem acontecer em cadeia.',
down:'O azar está chegando ou você está resistindo à mudança. Mas lembre-se — a roda sempre gira. Os tempos ruins também passam. Entregue-se ao fluxo e tenha paciência.'},
{id:'m11',name:'A Justiça',en:'Justice',emoji:'⚖️',suit:'major',num:11,
up:'Resultados justos chegam. Agir com honestidade e integridade traz bons resultados. Questões legais podem ser resolvidas favoravelmente. A lei de causa e efeito está em ação. Faça a escolha certa.',
down:'Você está em uma situação injusta ou evitando responsabilidades. Mentiras podem ser expostas — enfrente a verdade. Reflita se está fazendo julgamentos tendenciosos.'},
{id:'m12',name:'O Enforcado',en:'The Hanged Man',emoji:'🙃',suit:'major',num:12,
up:'Se você olhar de outro ângulo, a resposta aparece. Agora é hora de observar e esperar, não de agir. Esta pausa não é desistência — é para ganhar uma nova perspectiva. Paradoxalmente, ao soltar, você ganha. O sacrifício acaba recompensando grandemente.',
down:'Você está cansado de uma espera sem sentido. Se a situação está paralisada, mude sua perspectiva ou tome uma atitude. Pare de se fazer de mártir.'},
{id:'m13',name:'A Morte',en:'Death',emoji:'💀',suit:'major',num:13,
up:'O fim é um novo começo. Não tenha medo — isso não é morte física, é transformação. O velho deve ir embora para o novo chegar. Um relacionamento, emprego ou hábito está terminando, mas é um processo necessário. A borboleta só nasce quando a lagarta morre.',
down:'Você está resistindo a uma mudança necessária. Está se agarrando ao que deveria ter acabado. Deixe ir. Quanto mais você resistir à mudança, mais longa será a dor.'},
{id:'m14',name:'A Temperança',en:'Temperance',emoji:'🌊',suit:'major',num:14,
up:'É uma época de equilíbrio e harmonia. Evite os extremos e mantenha o meio-termo. A paciência e o progresso lento trazem bons resultados. É um momento em que sua capacidade de misturar diferentes elementos harmoniosamente brilha. Cuide também da saúde do corpo e da mente.',
down:'Você perdeu o equilíbrio e está se inclinando para um lado. Cuidado com excessos — beber demais, comer demais, trabalhar demais. A pressa pode estragar tudo. Recupere o equilíbrio.'},
{id:'m15',name:'O Diabo',en:'The Devil',emoji:'😈',suit:'major',num:15,
up:'Você está obcecado ou viciado em algo. Está preso por coisas materiais, prazer ou relacionamentos. Mas essas correntes foram você mesmo que colocou, e você mesmo pode quebrá-las. Encare sua sombra. Só reconhecendo é que você pode se libertar.',
down:'Você está se libertando de suas amarras! Está se libertando de maus hábitos ou relacionamentos tóxicos. Recupere sua liberdade. Não há mais nada a temer.'},
{id:'m16',name:'A Torre',en:'The Tower',emoji:'🗼',suit:'major',num:16,
up:'Mudanças súbitas ou choques podem estar chegando. O que você construiu pode desmoronar, mas é o que foi construído sobre bases erradas que está caindo. Após a destruição, você pode construir algo mais sólido. A verdade se revela como um raio.',
down:'Você está tentando evitar um colapso inevitável. Mas se o que deve cair não cair, um desastre maior virá. Aceite a mudança.'},
{id:'m17',name:'A Estrela',en:'The Star',emoji:'⭐',suit:'major',num:17,
up:'É a luz das estrelas após a tempestade. A esperança está voltando. As feridas estão se curando e a inspiração brota. O universo está te ajudando — não desista dos seus sonhos. Mostre seu verdadeiro eu como ele é. Você está brilhando.',
down:'Você está sem esperança e desanimado. Mas mesmo atrás das nuvens, as estrelas sempre estão lá. Recupere a confiança em si mesmo. Ainda é cedo demais para desistir.'},
{id:'m18',name:'A Lua',en:'The Moon',emoji:'🌙',suit:'major',num:18,
up:'É uma época de névoa onde nem tudo está claro. Confie na intuição, mas não se perca em ilusões. Preste atenção às mensagens do inconsciente. Os sonhos podem oferecer pistas importantes. Ao encarar os medos, eles desaparecem.',
down:'A névoa está se dissipando e a verdade começa a aparecer. A confusão se resolve e as coisas ficam claras. O que estava oculto será revelado — prepare-se.'},
{id:'m19',name:'O Sol',en:'The Sun',emoji:'☀️',suit:'major',num:19,
up:'Uma energia brilhante e calorosa transborda! É uma época de sucesso, alegria e vitalidade. Brilhe com confiança. Desfrute da alegria com pureza de criança. A escuridão passou e o sol nasceu. Em breve haverá algo para celebrar!',
down:'O sucesso está chegando, mas pode demorar um pouco. A confiança está baixa ou você não está sentindo alegria suficiente. Mantenha uma mentalidade positiva. O sol sempre nasce.'},
{id:'m20',name:'O Julgamento',en:'Judgement',emoji:'📯',suit:'major',num:20,
up:'Você está em uma virada da vida. É hora de olhar para o passado e fazer as pazes com ele. Descubra seu chamado e renasça. O perdão e a libertação estão acontecendo. Responda ao chamado interior. Você está pronto para subir a um nível mais elevado.',
down:'Você está preso na dúvida e não consegue se soltar do passado. Não fique preso ao arrependimento. Perdoe-se e siga em frente. Há uma segunda chance.'},
{id:'m21',name:'O Mundo',en:'The World',emoji:'🌍',suit:'major',num:21,
up:'Um grande ciclo foi completado! Você alcançou seus objetivos e chegou à integração. Parabéns! Viagens, expansão e novas possibilidades estão se abrindo. Um capítulo termina e um novo começa.',
down:'Você está quase lá, mas o último passo está faltando. É necessário concluir para que a conclusão aconteça. Não desista — o fim está à vista. Sacuda a insatisfação da incompletude e dê o seu melhor.'},

// ═══════════════════════════════════════
// Arcanos Menores — Paus (Fogo)
// ═══════════════════════════════════════
{id:'wA',name:'Ás de Paus',en:'Ace of Wands',emoji:'🔥',suit:'wands',num:1,
up:'Uma nova paixão e inspiração surgem! A energia criativa está explodindo. É o momento ideal para começar um novo projeto.',
down:'Perda de motivação, incapacidade de começar. Você tem as ideias mas não consegue colocá-las em ação.'},
{id:'w2',name:'Dois de Paus',en:'Two of Wands',emoji:'🔥',suit:'wands',num:2,
up:'É hora de planejar o futuro e traçar o grande quadro. O mundo está nas suas mãos. O momento da decisão.',
down:'Medo de planos, relutância em sair da zona de conforto. Você está adiando decisões.'},
{id:'w3',name:'Três de Paus',en:'Three of Wands',emoji:'🔥',suit:'wands',num:3,
up:'Os resultados dos seus esforços começam a aparecer. Oportunidade de expansão e crescimento. Boas notícias chegam de longe.',
down:'Os resultados não são o que se esperava, causando decepção. É preciso paciência.'},
{id:'w4',name:'Quatro de Paus',en:'Four of Wands',emoji:'🔥',suit:'wands',num:4,
up:'Uma época de celebração e alegria! Casamento, festa, mudança — há motivos para comemorar. Uma base estável foi estabelecida.',
down:'Instabilidade doméstica, celebrações adiadas. A base está abalada.'},
{id:'w5',name:'Cinco de Paus',en:'Five of Wands',emoji:'🔥',suit:'wands',num:5,
up:'Uma época de competição e conflito. Mas isso é uma competição saudável para o crescimento. Mantenha sua posição.',
down:'Evite brigas desnecessárias. A conciliação e a cooperação são a resposta.'},
{id:'w6',name:'Seis de Paus',en:'Six of Wands',emoji:'🔥',suit:'wands',num:6,
up:'Vitória e reconhecimento! O esforço é recompensado e elogios chegam de todos os lados. Tenha confiança.',
down:'Sentimento de não ser reconhecido, cuidado com arrogância. Mantenha a humildade.'},
{id:'w7',name:'Sete de Paus',en:'Seven of Wands',emoji:'🔥',suit:'wands',num:7,
up:'É hora de enfrentar os desafios. Mantenha firme sua posição. Se não desistir, você pode vencer.',
down:'Sensação de ser dominado, impulso de desistir. Uma retirada estratégica também é uma opção.'},
{id:'w8',name:'Oito de Paus',en:'Eight of Wands',emoji:'🔥',suit:'wands',num:8,
up:'As coisas estão progredindo rapidamente! Notícias, viagens, mudanças acontecem de repente. Suba na onda.',
down:'Atrasos, frustrações, espera. As coisas estão avançando mais devagar do que o esperado.'},
{id:'w9',name:'Nove de Paus',en:'Nine of Wands',emoji:'🔥',suit:'wands',num:9,
up:'Está difícil, mas você já chegou quase lá. Aguentem a última provação. Você é forte o suficiente.',
down:'Cansaço, esgotamento. Você precisa descansar. Forçar demais vai te derrubar.'},
{id:'w10',name:'Dez de Paus',en:'Ten of Wands',emoji:'🔥',suit:'wands',num:10,
up:'Você está carregando fardos demais. A responsabilidade é boa, mas não precisa fazer tudo sozinho. Peça ajuda.',
down:'É hora de largar o fardo. Liberte-se de responsabilidades desnecessárias.'},
{id:'wP',name:'Valete de Paus',en:'Page of Wands',emoji:'🔥',suit:'wands',num:11,
up:'Notícias empolgantes chegam! O início de uma nova aventura. Siga sua curiosidade.',
down:'Planos desmoronam ou notícias se atrasam.'},
{id:'wN',name:'Cavaleiro de Paus',en:'Knight of Wands',emoji:'🔥',suit:'wands',num:12,
up:'Hora de avançar com paixão! Transborda espírito aventureiro e coragem. Aja com ousadia.',
down:'Impaciência, cuidado com ações imprudentes. Você está correndo sem direção.'},
{id:'wQ',name:'Rainha de Paus',en:'Queen of Wands',emoji:'🔥',suit:'wands',num:13,
up:'Uma energia confiante e carismática! Exerça uma liderança calorosa e forte.',
down:'Ciúme, comportamento egocêntrico. Reconheça também a luz dos outros.'},
{id:'wK',name:'Rei de Paus',en:'King of Wands',emoji:'🔥',suit:'wands',num:14,
up:'Com visão e liderança, você realiza grandes coisas. Lidere as pessoas com carisma.',
down:'Autoritário, tirano. Não abuse do poder.'},

// ═══════════════════════════════════════
// Arcanos Menores — Copas (Água)
// ═══════════════════════════════════════
{id:'cA',name:'Ás de Copas',en:'Ace of Cups',emoji:'💧',suit:'cups',num:1,
up:'Um novo amor, o começo de uma emoção! O coração está pleno. Você está pronto para dar e receber amor.',
down:'Vazio emocional, incapacidade de aceitar o amor.'},
{id:'c2',name:'Dois de Copas',en:'Two of Cups',emoji:'💧',suit:'cups',num:2,
up:'Vínculo profundo e parceria. O amor verdadeiro ou a amizade floresce. Um relacionamento de respeito mútuo.',
down:'Desequilíbrio no relacionamento, sinais de separação.'},
{id:'c3',name:'Três de Copas',en:'Three of Cups',emoji:'💧',suit:'cups',num:3,
up:'Celebração, amizade, reunião! Um tempo agradável com amigos. Atividades sociais trazem boa sorte.',
down:'Excesso, devassidão. Você está perdendo coisas importantes em meio à diversão.'},
{id:'c4',name:'Quatro de Copas',en:'Four of Cups',emoji:'💧',suit:'cups',num:4,
up:'Tédio, indiferença. Você não está vendo as oportunidades à sua frente. Mude o foco e descubra novas possibilidades.',
down:'Você começa a aceitar novas oportunidades. Saia da apatia.'},
{id:'c5',name:'Cinco de Copas',en:'Five of Cups',emoji:'💧',suit:'cups',num:5,
up:'Tristeza e sensação de perda. Não se fixe no que foi derramado. Se você olhar para trás, ainda há algo sobrando.',
down:'Em recuperação da tristeza. Deixe o passado ir e siga em frente.'},
{id:'c6',name:'Seis de Copas',en:'Six of Cups',emoji:'💧',suit:'cups',num:6,
up:'Nostalgia, memórias da infância, pureza. Velhos laços podem retornar. Boas lembranças do passado trazem cura.',
down:'Preso no passado, sem viver o presente. Siga em frente.'},
{id:'c7',name:'Sete de Copas',en:'Seven of Cups',emoji:'💧',suit:'cups',num:7,
up:'Ilusões e opções abundam. Mas nem tudo é real. Julgue com realismo.',
down:'Desperta das ilusões e faz escolhas realistas.'},
{id:'c8',name:'Oito de Copas',en:'Eight of Cups',emoji:'💧',suit:'cups',num:8,
up:'É hora de partir do que não te preenche mais. Uma desistência corajosa. Parta em busca de um significado mais profundo.',
down:'Você fica onde deveria partir. Abandone os apegos.'},
{id:'c9',name:'Nove de Copas',en:'Nine of Cups',emoji:'💧',suit:'cups',num:9,
up:'Realização de desejos! Satisfação e felicidade transbordam. Aprecie a alegria com gratidão. Os sonhos se realizam.',
down:'Vazio apesar da abundância material. A verdadeira felicidade está dentro.'},
{id:'c10',name:'Dez de Copas',en:'Ten of Cups',emoji:'💧',suit:'cups',num:10,
up:'Felicidade perfeita! Família, amor, harmonia. Estado de plenitude emocional. Um lar feliz sob o arco-íris.',
down:'Conflito familiar, relacionamento que fica aquém das expectativas. Não corra atrás da perfeição.'},
{id:'cP',name:'Valete de Copas',en:'Page of Cups',emoji:'💧',suit:'cups',num:11,
up:'Uma mensagem ou proposta emotiva chega. Confie na sua intuição. O início de uma nova emoção.',
down:'Imaturidade emocional. Expectativas irrealistas.'},
{id:'cN',name:'Cavaleiro de Copas',en:'Knight of Cups',emoji:'💧',suit:'cups',num:12,
up:'Uma proposta romântica se aproxima! Inspiração artística. Seja fiel às suas emoções.',
down:'Ilusões irreais, cuidado com manipulação emocional.'},
{id:'cQ',name:'Rainha de Copas',en:'Queen of Cups',emoji:'💧',suit:'cups',num:13,
up:'Empatia profunda e intuição. A rainha que governa o mar das emoções. Cure com amor.',
down:'Dominada pelas emoções, dependência emocional.'},
{id:'cK',name:'Rei de Copas',en:'King of Cups',emoji:'💧',suit:'cups',num:14,
up:'Sabedoria e equilíbrio emocional. Liderança calma e compassiva. Harmonia entre emoção e razão.',
down:'Frieza emocional, repressão dos sentimentos.'},

// ═══════════════════════════════════════
// Arcanos Menores — Espadas (Ar)
// ═══════════════════════════════════════
{id:'sA',name:'Ás de Espadas',en:'Ace of Swords',emoji:'⚔️',suit:'swords',num:1,
up:'A verdade clara, um avanço! Uma nova ideia surge como um raio. A hora da decisão.',
down:'Confusão, informações erradas. Elimine o que está nublando seu julgamento.'},
{id:'s2',name:'Dois de Espadas',en:'Two of Swords',emoji:'⚔️',suit:'swords',num:2,
up:'Um impasse de indecisão. Pare de se tapar os olhos e enfrente a verdade de frente.',
down:'As informações se revelam, tornando a decisão possível.'},
{id:'s3',name:'Três de Espadas',en:'Three of Swords',emoji:'⚔️',suit:'swords',num:3,
up:'Feridas no coração, traição, separação. Dói, mas você cresce através dessa dor. Não suprima as emoções.',
down:'Em recuperação de feridas. A dor está gradualmente desaparecendo.'},
{id:'s4',name:'Quatro de Espadas',en:'Four of Swords',emoji:'⚔️',suit:'swords',num:4,
up:'Você precisa descansar. Recue da batalha por um momento e recarregue. A meditação e o repouso são a resposta.',
down:'Você está forçando sem descansar. Risco de esgotamento.'},
{id:'s5',name:'Cinco de Espadas',en:'Five of Swords',emoji:'⚔️',suit:'swords',num:5,
up:'Mesmo ao vencer, o custo é alto. Pense se a vitória vale a pena. Jogar sujo leva ao arrependimento.',
down:'Hora de admitir a derrota e aprender a lição. Abandone o orgulho.'},
{id:'s6',name:'Seis de Espadas',en:'Six of Swords',emoji:'⚔️',suit:'swords',num:6,
up:'Você está passando por um período difícil e se movendo para um lugar melhor. A dor da transição logo termina.',
down:'Você não consegue partir e fica parado. Aceite a mudança.'},
{id:'s7',name:'Sete de Espadas',en:'Seven of Swords',emoji:'⚔️',suit:'swords',num:7,
up:'Você precisa de estratégia. Aborde com sabedoria em vez de confronto direto. Mas o engano acaba sendo descoberto.',
down:'O engano é revelado. A honestidade é a melhor estratégia.'},
{id:'s8',name:'Oito de Espadas',en:'Eight of Swords',emoji:'⚔️',suit:'swords',num:8,
up:'Você se sente preso, mas na verdade essas amarras foram você mesmo que criou. Tire a venda e poderá escapar.',
down:'Você começa a se libertar das restrições. Avance em direção à liberdade.'},
{id:'s9',name:'Nove de Espadas',en:'Nine of Swords',emoji:'⚔️',suit:'swords',num:9,
up:'Ansiedade, pesadelos, preocupações. A agonia de não conseguir dormir à noite. Mas a maioria dos medos não é real.',
down:'O pior período está passando. Deixe as preocupações ir.'},
{id:'s10',name:'Dez de Espadas',en:'Ten of Swords',emoji:'⚔️',suit:'swords',num:10,
up:'Você tocou o fundo. As coisas não podem piorar mais. Mas este é o fim e um novo começo. O sol está nascendo.',
down:'Sinais de recuperação após o pior. A força para se levantar de novo está surgindo.'},
{id:'sP',name:'Valete de Espadas',en:'Page of Swords',emoji:'⚔️',suit:'swords',num:11,
up:'Curiosidade e observação aguçada. Novas informações ou notícias. Desvende a verdade.',
down:'Fofoca, maledicência, comunicação imatura.'},
{id:'sN',name:'Cavaleiro de Espadas',en:'Knight of Swords',emoji:'⚔️',suit:'swords',num:12,
up:'Ação rápida e decisiva! Avance sem hesitação. Lute pela justiça.',
down:'Impaciência, avanço imprudente. Pense antes de agir.'},
{id:'sQ',name:'Rainha de Espadas',en:'Queen of Swords',emoji:'⚔️',suit:'swords',num:13,
up:'Julgamento claro e independência. Sabedoria que não é governada pelas emoções. Enfrente a verdade de frente.',
down:'Frieza excessiva, causando uma impressão fria. A empatia também é necessária.'},
{id:'sK',name:'Rei de Espadas',en:'King of Swords',emoji:'⚔️',suit:'swords',num:14,
up:'Autoridade intelectual e julgamento justo. Tome decisões com lógica e ética.',
down:'Julgamento dogmático e desumano. Você precisa usar não só a cabeça, mas também o coração.'},

// ═══════════════════════════════════════
// Arcanos Menores — Ouros (Terra)
// ═══════════════════════════════════════
{id:'pA',name:'Ás de Ouros',en:'Ace of Pentacles',emoji:'💰',suit:'pentacles',num:1,
up:'Uma nova oportunidade financeira! A semente de um investimento, emprego ou negócio. O início da prosperidade material.',
down:'Perder oportunidades ou tomar cuidado com perdas financeiras.'},
{id:'p2',name:'Dois de Ouros',en:'Two of Pentacles',emoji:'💰',suit:'pentacles',num:2,
up:'Manter o equilíbrio. Lidando com várias coisas ao mesmo tempo. Adapte-se com flexibilidade.',
down:'Prestes a perder o equilíbrio e desmoronar. Defina prioridades.'},
{id:'p3',name:'Três de Ouros',en:'Three of Pentacles',emoji:'💰',suit:'pentacles',num:3,
up:'Resultados com trabalho em equipe e cooperação. Especialização é reconhecida. Trabalhar junto dá resultados melhores.',
down:'Falhou tentando fazer tudo sozinho. Perceba o valor da cooperação.'},
{id:'p4',name:'Quatro de Ouros',en:'Four of Pentacles',emoji:'💰',suit:'pentacles',num:4,
up:'Estabilidade e segurança. Financeiramente seguro, mas segurar demais faz você perder novas oportunidades.',
down:'Avareza, apego excessivo ao material. Compartilhar traz mais de volta.'},
{id:'p5',name:'Cinco de Ouros',en:'Five of Pentacles',emoji:'💰',suit:'pentacles',num:5,
up:'Dificuldades financeiras, isolamento. É um período difícil, mas a ajuda está perto. Levante a cabeça.',
down:'O pior está passando. A luz da recuperação está visível.'},
{id:'p6',name:'Seis de Ouros',en:'Six of Pentacles',emoji:'💰',suit:'pentacles',num:6,
up:'O equilíbrio do dar e receber. A generosidade traz bênçãos. É hora de dar ou receber ajuda.',
down:'Desequilíbrio no dar e receber. Cuidado com relacionamentos que penderam para um lado.'},
{id:'p7',name:'Sete de Ouros',en:'Seven of Pentacles',emoji:'💰',suit:'pentacles',num:7,
up:'Plantando sementes e esperando os resultados. É preciso paciência. O esforço certamente dará frutos.',
down:'Impaciência, frustração com resultados invisíveis. Não desista, você já está quase lá.'},
{id:'p8',name:'Oito de Ouros',en:'Eight of Pentacles',emoji:'💰',suit:'pentacles',num:8,
up:'Espírito de artesão! Época de aprimorar habilidades. O esforço consistente faz o especialista.',
down:'Cansado da repetição, perda de motivação. Lembre-se do seu objetivo.'},
{id:'p9',name:'Nove de Ouros',en:'Nine of Pentacles',emoji:'💰',suit:'pentacles',num:9,
up:'Independência e abundância! Desfrute dos resultados de um esforço próprio. Uma vida com classe. Você merece.',
down:'Ansiedade sobre independência, dependendo dos outros.'},
{id:'p10',name:'Dez de Ouros',en:'Ten of Pentacles',emoji:'💰',suit:'pentacles',num:10,
up:'Realização material! Prosperidade familiar, herança, estabilidade de longo prazo. Riqueza e felicidade que atravessam gerações.',
down:'Conflito financeiro familiar, problemas de herança. As relações são mais importantes que o material.'},
{id:'pP',name:'Valete de Ouros',en:'Page of Pentacles',emoji:'💰',suit:'pentacles',num:11,
up:'Notícia de nova aprendizagem ou oportunidade financeira. O estudo diligente traz resultados.',
down:'Plano pouco realista, preguiça.'},
{id:'pN',name:'Cavaleiro de Ouros',en:'Knight of Pentacles',emoji:'💰',suit:'pentacles',num:12,
up:'Avanço firme e diligente. Progresso lento mas certo. A constância vence.',
down:'Muito lento, conservador. Às vezes, a ousadia também é necessária.'},
{id:'pQ',name:'Rainha de Ouros',en:'Queen of Pentacles',emoji:'💰',suit:'pentacles',num:13,
up:'Sabedoria prática e abundância calorosa. Uma energia prática e generosa. Equilíbrio entre o lar e as finanças.',
down:'Falta de autocuidado, workaholic.'},
{id:'pK',name:'Rei de Ouros',en:'King of Pentacles',emoji:'💰',suit:'pentacles',num:14,
up:'Sucesso e estabilidade financeira! Aptidão para negócios e liderança prática. Colhendo frutos abundantes.',
down:'Ganância, materialismo. O dinheiro não é tudo.'}
];
