// 78 Tarot-Karten (22 Große Arkana + 56 Kleine Arkana)
const TAROT_CARDS = [
// ═══════════════════════════════════════
// Große Arkana (0–21)
// ═══════════════════════════════════════
{id:'m0',name:'Der Narr',en:'The Fool',emoji:'🃏',suit:'major',num:0,
up:'Ein neuer Anfang liegt direkt vor dir. Leg die Angst ab und wage den ersten Schritt. Jetzt ist nicht die Zeit zu kalkulieren – folge deiner Intuition. Tritt mit reinem Herzen in die Welt hinaus. Ein unerwartetes Abenteuer wartet auf dich. Fürchte dich nicht vor dem Scheitern — der Narr springt sogar am Rand der Klippe lachend ins Unbekannte.',
down:'Du handelst gerade zu unbesonnen. Ohne Vorbereitung vorzupreschen kann zu großen Fehlern führen. Denk noch einmal nach und höre auf den Rat deiner Umgebung. Freiheit und Leichtsinn sind nicht dasselbe. Hüte dich vor voreiligen Entscheidungen.'},
{id:'m1',name:'Der Magier',en:'The Magician',emoji:'🪄',suit:'major',num:1,
up:'Alle Werkzeuge und Talente, die du brauchst, sind bereits in dir. Jetzt ist die Zeit, dich zu fokussieren und zu handeln. Mit Willenskraft und Kreativität kannst du alles erreichen, was du dir wünschst. Wie der Magier, der Himmel und Erde verbindet, mach deine Ideen zur Realität. Deine Worte und Taten haben Kraft.',
down:'Du verschwendest dein Talent oder setzt deine Fähigkeiten am falschen Ort ein. Mangelndes Selbstvertrauen lässt dich Chancen verpassen. Oder Worte und Taten stimmen nicht überein. Finde deine Aufrichtigkeit zurück.'},
{id:'m2',name:'Die Hohepriesterin',en:'The High Priestess',emoji:'🌙',suit:'major',num:2,
up:'Die Antwort liegt bereits in dir. Vertraue der Intuition mehr als der Logik. Wenn du still auf deine innere Stimme hörst, offenbart sich die verborgene Wahrheit. Jetzt ist die Zeit der Beobachtung, nicht des Handelns. Lies, was unter der Oberfläche liegt. Geheimnisvolle Weisheit leitet dich.',
down:'Du ignorierst deine Intuition und verlässt dich nur auf den äußeren Schein. Oder es gibt eine Wahrheit, die du kennst, aber verdrängen willst. Erkenne die verborgenen Motive. Du musst tiefer hineinschauen.'},
{id:'m3',name:'Die Herrscherin',en:'The Empress',emoji:'🌺',suit:'major',num:3,
up:'Eine Zeit voller Fülle und Liebe. Genieße deine Sinne und kümmere dich um dich selbst. Kreative Energie ist hochaktiv – ideal, um Neues zu erschaffen. Der Kontakt mit der Natur lädt deine Energie auf. Umhülle deine Umgebung mit mütterlicher Liebe. Schönheit zu suchen ist kein Luxus.',
down:'Du vernachlässigst die Selbstfürsorge oder bist zu sehr von anderen abhängig. Wenn du eine kreative Blockade spürst, suche Inspiration in der Natur. Hüte dich vor Eifersucht und Besitzdenken.'},
{id:'m4',name:'Der Herrscher',en:'The Emperor',emoji:'👑',suit:'major',num:4,
up:'Eine systematische und entschlossene Herangehensweise ist gefragt. Durch Disziplin und Ordnung erreichst du Stabilität. Zeige Führungsstärke und handle verantwortungsbewusst. Urteile mit dem Verstand statt mit Gefühlen. Die Regeln, die du aufstellst, geben auch anderen Sicherheit.',
down:'Du bist zu starr oder zu kontrollierend. Wenn du Regeln ohne Flexibilität durchsetzt, erntst du Widerstand. Frage dich, ob du Autorität missbrauchst. Manchmal ist Nachgeben die wahre Stärke.'},
{id:'m5',name:'Der Hierophant',en:'The Hierophant',emoji:'🙏',suit:'major',num:5,
up:'In traditionellen Werten oder einem Mentor findest du Antworten. Es ist eine Zeit des Lernens und des spirituellen Wachstums. Finde Zugehörigkeit in der Gemeinschaft. Bewährten Methoden zu folgen ist sicher. Das Geben und Nehmen von Wissen lässt beide wachsen.',
down:'Die alten Wege passen nicht mehr. Es ist Zeit, aus eingefahrenem Denken auszubrechen und deinen eigenen Weg zu gehen. Urteile selbst, anstatt blind zu folgen. Ein unkonventioneller Ansatz könnte die Antwort sein.'},
{id:'m6',name:'Die Liebenden',en:'The Lovers',emoji:'💕',suit:'major',num:6,
up:'Liebe kommt auf dich zu, oder du stehst vor einer wichtigen Entscheidung. Wähle, wohin dein Herz dich führt. Eine echte Verbindung und Harmonie entstehen gerade. Eine Begegnung mit jemandem, der deine Werte teilt, kann dein Leben verändern. Sei ehrlich in der Liebe.',
down:'In einer Beziehung gibt es Disharmonie oder einen Wertekonflikt. Wenn du verführt wirst, denk darüber nach, was du wirklich willst. Tritt einen Schritt zurück, bevor du eine falsche Wahl triffst.'},
{id:'m7',name:'Der Wagen',en:'The Chariot',emoji:'⚡',suit:'major',num:7,
up:'Jetzt ist die Zeit, Hindernisse mit starkem Willen zu durchbrechen! Halte nicht an – geh voran. Entschlossenheit und Fokus führen zum Sieg. Wenn du gegensätzliche Kräfte harmonisch lenkst, erreichst du dein Ziel. Du kannst gewinnen.',
down:'Du hast die Orientierung verloren und schwankst. Emotionen reißen dich mit, oder du versuchst zu viel auf einmal und bist erschöpft. Halte inne und setze deinen Kurs neu.'},
{id:'m8',name:'Die Kraft',en:'Strength',emoji:'🦁',suit:'major',num:8,
up:'Sanfte Kraft besiegt rohe Gewalt. Bewältige die Situation mit Geduld und Mut. Unterdrücke Wut oder Angst nicht – halte sie sanft im Griff. Die innere Bestie zu zähmen geschieht nicht durch Gewalt, sondern durch Liebe. Du bist viel stärker als du denkst.',
down:'Du hast das Vertrauen in dich verloren und bist schwach geworden. Du wirst von Emotionen überwältigt oder zweifelst an dir selbst. Wecke deine innere Kraft wieder. Gib nicht auf — in dir steckt ein Löwe.'},
{id:'m9',name:'Der Einsiedler',en:'The Hermit',emoji:'🔦',suit:'major',num:9,
up:'Du brauchst Zeit für dich allein. Entferne dich vom Lärm und erforsche dein Inneres. Die Antwort liegt nicht außen, sondern in dir. Durch Meditation oder Reflexion gewinnst du tiefe Weisheit. Einsamkeit ist keine Isolation, sondern Selbstentdeckung.',
down:'Du bist schon zu lange isoliert. Du bist gefangen in deinen eigenen Gedanken, abgeschnitten von der Welt. Es ist Zeit, wieder mit anderen in Verbindung zu treten. Um Hilfe zu bitten ist keine Schwäche.'},
{id:'m10',name:'Das Rad des Schicksals',en:'Wheel of Fortune',emoji:'🎡',suit:'major',num:10,
up:'Das Schicksalsrad dreht sich! Große Veränderungen und Glück nahen. Lass die Chance nicht entgleiten. Es ist ein Wendepunkt im Lebenszyklus. Lass dich vom Fluss tragen. Gute Dinge können sich aneinanderreihen.',
down:'Pech trifft dich, oder du widersetzt dich dem Wandel. Aber denk daran — das Rad dreht sich immer. Auch schlechte Zeiten gehen vorbei. Lass los und habe Geduld.'},
{id:'m11',name:'Die Gerechtigkeit',en:'Justice',emoji:'⚖️',suit:'major',num:11,
up:'Ein faires Ergebnis steht bevor. Ehrliches und aufrichtiges Handeln führt zu guten Ergebnissen. Bei rechtlichen Problemen könnte die Lösung zu deinen Gunsten ausfallen. Das Gesetz von Ursache und Wirkung ist am Werk. Triff die richtige Wahl.',
down:'Du befindest dich in einer ungerechten Situation oder weichst der Verantwortung aus. Lügen können auffliegen – stell dich der Wahrheit. Frage dich, ob du voreingenommen urteilst.'},
{id:'m12',name:'Der Gehängte',en:'The Hanged Man',emoji:'🙃',suit:'major',num:12,
up:'Aus einem anderen Blickwinkel betrachtet wird die Antwort sichtbar. Jetzt ist die Zeit der Beobachtung und des Wartens, nicht des Handelns. Kein Aufgeben, sondern ein Innehalten, um eine neue Perspektive zu gewinnen. Paradoxerweise bekommst du, wenn du loslässt. Das Opfer lohnt sich schließlich.',
down:'Du bist des sinnlosen Wartens müde. Wenn die Situation feststeckt, ändere die Perspektive oder handle. Hör auf, den Märtyrer zu spielen.'},
{id:'m13',name:'Der Tod',en:'Death',emoji:'💀',suit:'major',num:13,
up:'Ein Ende ist ein neuer Anfang. Fürchte dich nicht — das ist kein physischer Tod, sondern eine Transformation. Das Alte muss losgelassen werden, damit Neues kommen kann. Eine Beziehung, ein Job oder eine Gewohnheit endet gerade, aber das ist ein notwendiger Prozess. Der Schmetterling muss als Raupe sterben.',
down:'Du widersetzt dich dem notwendigen Wandel. Du hältst fest, was du loslassen müsstest. Lass los. Je mehr du dich dem Wandel widersetzt, desto länger dauert der Schmerz.'},
{id:'m14',name:'Die Mäßigkeit',en:'Temperance',emoji:'🌊',suit:'major',num:14,
up:'Eine Zeit der Balance und Harmonie. Meide Extreme und halte die Mitte. Mit Geduld und Besonnenheit kommen gute Ergebnisse. Jetzt glänzt die Fähigkeit, verschiedene Elemente harmonisch zu verbinden. Achte auch auf Körper und Geist.',
down:'Du hast das Gleichgewicht verloren und neigst zu einer Seite. Hüte dich vor Übermaß – zu viel Trinken, Essen, Arbeiten. Ungeduld kann die Dinge verderben. Finde dein Gleichgewicht zurück.'},
{id:'m15',name:'Der Teufel',en:'The Devil',emoji:'😈',suit:'major',num:15,
up:'Du bist an etwas besessen oder süchtig. Du bist gebunden an Materielles, Vergnügen oder eine Beziehung. Aber die Ketten hast du dir selbst angelegt – du kannst sie auch selbst lösen. Schau deinen Schatten direkt an. Erst wenn du es anerkennst, kannst du dich befreien.',
down:'Du befreist dich aus der Gefangenschaft! Du löst dich aus einer schlechten Gewohnheit oder einer toxischen Beziehung. Hole dir deine Freiheit zurück. Es gibt nichts mehr zu fürchten.'},
{id:'m16',name:'Der Turm',en:'The Tower',emoji:'🗼',suit:'major',num:16,
up:'Ein plötzlicher Wandel oder Schock kann kommen. Was du aufgebaut hast, könnte einstürzen – aber das ist das Einstürzen von Dingen, die auf falschem Fundament standen. Nach dem Zerfall kannst du etwas Stärkeres aufbauen. Die Wahrheit enthüllt sich wie ein Blitz.',
down:'Du versuchst den unvermeidlichen Zusammenbruch zu vermeiden. Aber wenn das, was fallen muss, nicht fällt, kommt eine noch größere Katastrophe. Nimm den Wandel an.'},
{id:'m17',name:'Der Stern',en:'The Star',emoji:'⭐',suit:'major',num:17,
up:'Das stille Sternenlicht nach dem Sturm. Die Hoffnung kehrt zurück. Wunden heilen und Inspiration strömt. Das Universum hilft dir – gib deinen Traum nicht auf. Zeige dich, wie du wirklich bist. Du strahlst.',
down:'Du hast die Hoffnung verloren und bist entmutigt. Aber hinter den Wolken sind die Sterne immer noch da. Finde wieder Glauben an dich selbst. Es ist noch zu früh, aufzugeben.'},
{id:'m18',name:'Der Mond',en:'The Moon',emoji:'🌙',suit:'major',num:18,
up:'Eine neblige Zeit, in der nichts klar ist. Vertraue deiner Intuition, aber verfalle nicht in Illusionen. Achte auf Botschaften aus dem Unbewussten. Träume können wichtige Hinweise geben. Wenn du dich deinen Ängsten stellst, verschwinden sie.',
down:'Der Nebel lichtet sich und die Wahrheit wird sichtbar. Verwirrung löst sich auf und Klarheit kommt. Verborgenes tritt ans Licht – sei bereit.'},
{id:'m19',name:'Die Sonne',en:'The Sun',emoji:'☀️',suit:'major',num:19,
up:'Helle und warme Energie erfüllt alles! Eine Zeit des Erfolgs, der Freude und der Vitalität. Strahle mit Selbstvertrauen. Genieße die Freude mit der Reinheit eines Kindes. Die Dunkelheit ist vorbei – die Sonne ist aufgegangen. Bald gibt es etwas zu feiern!',
down:'Der Erfolg kommt, könnte aber etwas verzögert sein. Dir fehlt das Selbstvertrauen, oder du kannst die Freude nicht vollständig spüren. Behalte eine positive Einstellung. Die Sonne geht immer auf.'},
{id:'m20',name:'Das Gericht',en:'Judgement',emoji:'📯',suit:'major',num:20,
up:'Du stehst an einem Wendepunkt deines Lebens. Blicke zurück und räume auf. Entdecke deine Berufung und werde neu geboren. Vergebung und Befreiung sind am Werk. Antworte auf den inneren Ruf. Du bist bereit, auf eine höhere Ebene aufzusteigen.',
down:'Du zweifelst an dir und kannst die Vergangenheit nicht loslassen. Bleib nicht in der Reue verhaftet. Vergib dir selbst und gehe vorwärts. Eine zweite Chance gibt es.'},
{id:'m21',name:'Die Welt',en:'The World',emoji:'🌍',suit:'major',num:21,
up:'Ein großer Kreislauf ist vollendet! Du hast dein Ziel erreicht und bist zur Integration gelangt. Herzlichen Glückwunsch! Reisen, Erweiterung und neue Möglichkeiten öffnen sich. Ein Kapitel endet und ein neues beginnt.',
down:'Du bist fast am Ziel, aber der letzte Schritt fehlt noch. Das Abschließen zur Vollendung ist notwendig. Gib nicht auf – das Ende ist in Sicht. Schüttle den Frust über das Unvollendete ab und gib dein Bestes.'},

// ═══════════════════════════════════════
// Kleine Arkana — Stäbe (Feuer)
// ═══════════════════════════════════════
{id:'wA',name:'Ass der Stäbe',en:'Ace of Wands',emoji:'🔥',suit:'wands',num:1,
up:'Neue Leidenschaft und Inspiration brechen auf! Kreative Energie explodiert gerade. Der perfekte Moment, um ein neues Projekt zu beginnen.',
down:'Motivationsverlust, Unfähigkeit zu beginnen. Ideen sind vorhanden, aber die Umsetzung fehlt.'},
{id:'w2',name:'Zwei der Stäbe',en:'Two of Wands',emoji:'🔥',suit:'wands',num:2,
up:'Zeit, die Zukunft zu planen und das große Bild zu entwerfen. Die Welt liegt in deinen Händen. Ein Entscheidungsmoment.',
down:'Angst vor Plänen, Scheu das Vertraute zu verlassen. Entscheidungen werden aufgeschoben.'},
{id:'w3',name:'Drei der Stäbe',en:'Three of Wands',emoji:'🔥',suit:'wands',num:3,
up:'Die Früchte der Arbeit werden sichtbar. Chancen auf Erweiterung und Wachstum. Gute Nachrichten kommen aus der Ferne.',
down:'Das Ergebnis enttäuscht die Erwartungen. Geduld ist gefragt.'},
{id:'w4',name:'Vier der Stäbe',en:'Four of Wands',emoji:'🔥',suit:'wands',num:4,
up:'Eine Zeit der Feier und Freude! Hochzeit, Party, Umzug – ein freudiges Ereignis steht an. Ein stabiles Fundament wurde geschaffen.',
down:'Instabile häusliche Umgebung, Freude verzögert sich. Das Fundament wackelt.'},
{id:'w5',name:'Fünf der Stäbe',en:'Five of Wands',emoji:'🔥',suit:'wands',num:5,
up:'Eine Zeit des Wettbewerbs und Konflikts. Aber das ist ein gesunder Wettbewerb für Wachstum. Behalte deine Position.',
down:'Vermeide sinnlosen Streit. Kompromiss und Zusammenarbeit sind die Antwort.'},
{id:'w6',name:'Sechs der Stäbe',en:'Six of Wands',emoji:'🔥',suit:'wands',num:6,
up:'Sieg und Anerkennung! Bemühungen werden belohnt und Lob kommt von allen Seiten. Sei selbstbewusst.',
down:'Das Gefühl, nicht anerkannt zu werden. Vorsicht vor Arroganz. Behalte Bescheidenheit.'},
{id:'w7',name:'Sieben der Stäbe',en:'Seven of Wands',emoji:'🔥',suit:'wands',num:7,
up:'Jetzt ist die Zeit, Herausforderungen standzuhalten. Halte deine Position fest. Wenn du nicht aufgibst, kannst du gewinnen.',
down:'Das Gefühl, überwältigt zu sein und aufgeben zu wollen. Ein strategischer Rückzug ist auch eine Option.'},
{id:'w8',name:'Acht der Stäbe',en:'Eight of Wands',emoji:'🔥',suit:'wands',num:8,
up:'Dinge entwickeln sich schnell! Nachrichten, Reisen, Veränderungen – alles geschieht im Nu. Reite auf der Welle.',
down:'Verzögerungen, Frustration, Warten. Dinge laufen langsamer als erwartet.'},
{id:'w9',name:'Neun der Stäbe',en:'Nine of Wands',emoji:'🔥',suit:'wands',num:9,
up:'Es ist schwer, aber du bist fast am Ziel. Halte die letzte Prüfung durch. Du bist stark genug.',
down:'Erschöpfung, Burnout. Du brauchst Ruhe. Wenn du weiter drückst, brichst du zusammen.'},
{id:'w10',name:'Zehn der Stäbe',en:'Ten of Wands',emoji:'🔥',suit:'wands',num:10,
up:'Du trägst zu viel. Verantwortungsbewusstsein ist gut, aber du musst nicht alles alleine tragen. Bitte um Hilfe.',
down:'Es ist Zeit, die Last abzulegen. Befreie dich von unnötiger Verantwortung.'},
{id:'wP',name:'Bube der Stäbe',en:'Page of Wands',emoji:'🔥',suit:'wands',num:11,
up:'Aufregende Neuigkeiten kommen! Beginn eines neuen Abenteuers. Folge deiner Neugier.',
down:'Pläne werden durchkreuzt oder Nachrichten verzögern sich.'},
{id:'wN',name:'Ritter der Stäbe',en:'Knight of Wands',emoji:'🔥',suit:'wands',num:12,
up:'Jetzt ist die Zeit, leidenschaftlich vorzupreschen! Abenteuerlust und Mut strömen über. Handle kühn.',
down:'Überstürzung, Leichtsinn. Du rennst ohne Richtung.'},
{id:'wQ',name:'Königin der Stäbe',en:'Queen of Wands',emoji:'🔥',suit:'wands',num:13,
up:'Selbstbewusste und charismatische Energie! Zeige warme und doch starke Führung.',
down:'Eifersucht, egozentriertes Verhalten. Erkenne auch das Licht anderer an.'},
{id:'wK',name:'König der Stäbe',en:'King of Wands',emoji:'🔥',suit:'wands',num:14,
up:'Mit Vision und Führungskraft erreichst du Großes. Leite andere mit Charisma.',
down:'Autoritär, tyrannisch. Missbrauche die Macht nicht.'},

// ═══════════════════════════════════════
// Kleine Arkana — Kelche (Wasser)
// ═══════════════════════════════════════
{id:'cA',name:'Ass der Kelche',en:'Ace of Cups',emoji:'💧',suit:'cups',num:1,
up:'Neue Liebe, Beginn eines Gefühls! Das Herz füllt sich. Du bist bereit, Liebe zu geben und zu empfangen.',
down:'Emotionale Leere, Unfähigkeit, Liebe anzunehmen.'},
{id:'c2',name:'Zwei der Kelche',en:'Two of Cups',emoji:'💧',suit:'cups',num:2,
up:'Tiefe Verbundenheit und Partnerschaft. Echte Liebe oder Freundschaft erblüht. Eine Beziehung auf Augenhöhe.',
down:'Ungleichgewicht in der Beziehung, Anzeichen einer Trennung.'},
{id:'c3',name:'Drei der Kelche',en:'Three of Cups',emoji:'💧',suit:'cups',num:3,
up:'Feier, Freundschaft, Zusammenkommen! Eine schöne Zeit mit Freunden. Gesellige Aktivitäten bringen Glück.',
down:'Übermäßiges Trinken, Ausschweifung. Du verpasst Wichtiges im Vergnügen.'},
{id:'c4',name:'Vier der Kelche',en:'Four of Cups',emoji:'💧',suit:'cups',num:4,
up:'Langeweile, Gleichgültigkeit. Du siehst die Chance vor dir nicht. Wende den Blick und entdecke neue Möglichkeiten.',
down:'Du beginnst, neue Chancen anzunehmen. Befreie dich aus der Apathie.'},
{id:'c5',name:'Fünf der Kelche',en:'Five of Cups',emoji:'💧',suit:'cups',num:5,
up:'Trauer und Verlustgefühl. Fixiere dich nicht auf das Verschüttete. Schau zurück – es ist noch etwas übrig.',
down:'Erholung vom Schmerz. Lass die Vergangenheit los und geh vorwärts.'},
{id:'c6',name:'Sechs der Kelche',en:'Six of Cups',emoji:'💧',suit:'cups',num:6,
up:'Nostalgie, Erinnerungen aus der Kindheit, Unschuld. Eine alte Bekanntschaft könnte zurückkehren. Schöne Erinnerungen heilen.',
down:'Gefangen in der Vergangenheit, lebst nicht im Jetzt. Geh vorwärts.'},
{id:'c7',name:'Sieben der Kelche',en:'Seven of Cups',emoji:'💧',suit:'cups',num:7,
up:'Illusionen und Optionen im Überfluss. Aber nicht alles ist echt. Urteile realistisch.',
down:'Erwache aus der Illusion und triff eine realistische Wahl.'},
{id:'c8',name:'Acht der Kelche',en:'Eight of Cups',emoji:'💧',suit:'cups',num:8,
up:'Es ist Zeit, das zu verlassen, was dich nicht mehr erfüllt. Ein mutiges Loslassen. Suche nach tieferer Bedeutung.',
down:'Du verbleibst dort, wo du gehen solltest. Lass die Sehnsucht los.'},
{id:'c9',name:'Neun der Kelche',en:'Nine of Cups',emoji:'💧',suit:'cups',num:9,
up:'Wunscherfüllung! Zufriedenheit und Glück strömen über. Genieße die Freude mit Dankbarkeit. Träume werden wahr.',
down:'Leere trotz materiellem Überfluss. Echtes Glück liegt im Innern.'},
{id:'c10',name:'Zehn der Kelche',en:'Ten of Cups',emoji:'💧',suit:'cups',num:10,
up:'Vollkommenes Glück! Familie, Liebe, Eintracht. Emotional erfüllter Zustand. Das glückliche Zuhause unter dem Regenbogen.',
down:'Familiäre Zwietracht, Beziehungen entsprechen nicht den Erwartungen. Jage nicht der Perfektion nach.'},
{id:'cP',name:'Bube der Kelche',en:'Page of Cups',emoji:'💧',suit:'cups',num:11,
up:'Eine emotionale Botschaft oder ein Angebot kommt. Vertraue der Intuition. Beginn eines neuen Gefühls.',
down:'Emotionale Unreife. Unrealistische Erwartungen.'},
{id:'cN',name:'Ritter der Kelche',en:'Knight of Cups',emoji:'💧',suit:'cups',num:12,
up:'Ein romantisches Angebot naht! Künstlerische Inspiration. Sei deinen Gefühlen treu.',
down:'Unrealistische Fantasien, Vorsicht vor emotionaler Manipulation.'},
{id:'cQ',name:'Königin der Kelche',en:'Queen of Cups',emoji:'💧',suit:'cups',num:13,
up:'Tiefes Mitgefühl und Intuition. Eine Königin, die das Meer der Emotionen beherrscht. Heile mit Liebe.',
down:'Von Emotionen überwältigt, emotionale Abhängigkeit.'},
{id:'cK',name:'König der Kelche',en:'King of Cups',emoji:'💧',suit:'cups',num:14,
up:'Weisheit und Balance der Emotionen. Ruhige und mitfühlende Führung. Harmonie von Gefühl und Verstand.',
down:'Emotionale Kälte, Unterdrückung der Gefühle.'},

// ═══════════════════════════════════════
// Kleine Arkana — Schwerter (Luft)
// ═══════════════════════════════════════
{id:'sA',name:'Ass der Schwerter',en:'Ace of Swords',emoji:'⚔️',suit:'swords',num:1,
up:'Klare Wahrheit, Durchbruch! Neue Ideen blitzen wie Blitze auf. Die Zeit der Entscheidung.',
down:'Verwirrung, Fehlinformationen. Entferne, was das Urteil trübt.'},
{id:'s2',name:'Zwei der Schwerter',en:'Two of Swords',emoji:'⚔️',suit:'swords',num:2,
up:'Eine Pattsituation, in der keine Entscheidung getroffen wird. Nimm die Augenbinde ab und sieh der Wahrheit ins Gesicht.',
down:'Mit neuen Informationen wird eine Entscheidung möglich.'},
{id:'s3',name:'Drei der Schwerter',en:'Three of Swords',emoji:'⚔️',suit:'swords',num:3,
up:'Herzschmerz, Verrat, Trennung. Es tut weh, aber dieser Schmerz lässt dich wachsen. Unterdrücke deine Gefühle nicht.',
down:'Du erholst dich von Wunden. Der Schmerz lässt allmählich nach.'},
{id:'s4',name:'Vier der Schwerter',en:'Four of Swords',emoji:'⚔️',suit:'swords',num:4,
up:'Du brauchst Ruhe. Tritt aus dem Kampf zurück und tanke Kraft. Meditation und Erholung sind die Antwort.',
down:'Du übertreibst es ohne Pause. Burnout-Gefahr.'},
{id:'s5',name:'Fünf der Schwerter',en:'Five of Swords',emoji:'⚔️',suit:'swords',num:5,
up:'Selbst ein Sieg hat seinen Preis. Denke nach, ob der Sieg es wert ist. Gemeine Methoden werden bereut.',
down:'Zeit, die Niederlage anzuerkennen und daraus zu lernen. Leg den Stolz ab.'},
{id:'s6',name:'Sechs der Schwerter',en:'Six of Swords',emoji:'⚔️',suit:'swords',num:6,
up:'Du bewegst dich aus einer schwierigen Zeit heraus an einen besseren Ort. Der Schmerz des Übergangs endet bald.',
down:'Du kannst nicht gehen und bleibst zurück. Nimm den Wandel an.'},
{id:'s7',name:'Sieben der Schwerter',en:'Seven of Swords',emoji:'⚔️',suit:'swords',num:7,
up:'Strategie ist gefragt. Gehe klug vor statt direkt zu konfrontieren. Aber Täuschung fliegt schließlich auf.',
down:'Die Täuschung wird entdeckt. Ehrlichkeit ist die beste Strategie.'},
{id:'s8',name:'Acht der Schwerter',en:'Eight of Swords',emoji:'⚔️',suit:'swords',num:8,
up:'Du fühlst dich gefangen, aber die Fesseln hast du dir selbst angelegt. Nimm die Augenbinde ab und du kannst entkommen.',
down:'Du beginnst, dich aus den Beschränkungen zu befreien. Gehe in Richtung Freiheit.'},
{id:'s9',name:'Neun der Schwerter',en:'Nine of Swords',emoji:'⚔️',suit:'swords',num:9,
up:'Angst, Albträume, Sorgen. Schlaflose Nächte voller Schmerz. Aber die meisten Ängste sind nicht real.',
down:'Die schlimmste Zeit geht vorbei. Leg die Sorgen nieder.'},
{id:'s10',name:'Zehn der Schwerter',en:'Ten of Swords',emoji:'⚔️',suit:'swords',num:10,
up:'Du hast den Tiefpunkt erreicht. Es kann nicht schlimmer werden. Aber das ist ein Ende und gleichzeitig ein neuer Anfang. Die Sonne geht auf.',
down:'Die schlimmste Phase ist überstanden, Anzeichen der Erholung zeigen sich. Neue Kraft wächst.'},
{id:'sP',name:'Bube der Schwerter',en:'Page of Swords',emoji:'⚔️',suit:'swords',num:11,
up:'Neugier und scharfe Beobachtungsgabe. Neue Informationen oder Neuigkeiten. Forsche nach der Wahrheit.',
down:'Klatsch, Gerüchte, unreife Kommunikation.'},
{id:'sN',name:'Ritter der Schwerter',en:'Knight of Swords',emoji:'⚔️',suit:'swords',num:12,
up:'Schnelles und entschlossenes Handeln! Schreite ungehindert voran. Kämpfe für Gerechtigkeit.',
down:'Überstürzung, blindes Vorpreschen. Erst denken, dann handeln.'},
{id:'sQ',name:'Königin der Schwerter',en:'Queen of Swords',emoji:'⚔️',suit:'swords',num:13,
up:'Klare Urteilskraft und Unabhängigkeit. Weisheit, die sich nicht von Emotionen leiten lässt. Sieh der Wahrheit ins Gesicht.',
down:'Zu viel Kühle hinterlässt einen kalten Eindruck. Empathie ist auch nötig.'},
{id:'sK',name:'König der Schwerter',en:'King of Swords',emoji:'⚔️',suit:'swords',num:14,
up:'Intellektuelle Autorität und faires Urteil. Entscheide mit Logik und Ethik.',
down:'Eigenwillig, unmenschliches Urteil. Nutze nicht nur den Kopf, sondern auch das Herz.'},

// ═══════════════════════════════════════
// Kleine Arkana — Münzen (Erde)
// ═══════════════════════════════════════
{id:'pA',name:'Ass der Münzen',en:'Ace of Pentacles',emoji:'💰',suit:'pentacles',num:1,
up:'Neue finanzielle Gelegenheit! Samen von Investment, Job oder Geschäft. Der Beginn materiellen Wohlstands.',
down:'Eine Gelegenheit wird verpasst oder finanzielle Verluste drohen.'},
{id:'p2',name:'Zwei der Münzen',en:'Two of Pentacles',emoji:'💰',suit:'pentacles',num:2,
up:'Jonglieren. Mehrere Dinge gleichzeitig erledigen. Bleib flexibel.',
down:'Das Gleichgewicht kippt fast. Setze Prioritäten.'},
{id:'p3',name:'Drei der Münzen',en:'Three of Pentacles',emoji:'💰',suit:'pentacles',num:3,
up:'Teamarbeit und Zusammenarbeit zahlen sich aus. Fachwissen wird anerkannt. Gemeinsam bessere Ergebnisse.',
down:'Alleine versucht und gescheitert. Erkenne den Wert der Zusammenarbeit.'},
{id:'p4',name:'Vier der Münzen',en:'Four of Pentacles',emoji:'💰',suit:'pentacles',num:4,
up:'Stabilität und Sicherheit. Finanziell sicher, aber zu starkes Festhalten lässt neue Chancen entgehen.',
down:'Geiz, übermäßige Fixierung auf Materielles. Wer teilt, bekommt mehr zurück.'},
{id:'p5',name:'Fünf der Münzen',en:'Five of Pentacles',emoji:'💰',suit:'pentacles',num:5,
up:'Finanzielle Schwierigkeiten, Isolation. Eine schwere Zeit, aber Hilfe ist in der Nähe. Schau auf.',
down:'Die schlimmste Situation geht vorbei. Das Licht der Erholung ist sichtbar.'},
{id:'p6',name:'Sechs der Münzen',en:'Six of Pentacles',emoji:'💰',suit:'pentacles',num:6,
up:'Balance von Geben und Nehmen. Großzügigkeit bringt Segen. Zeit zu geben oder zu empfangen.',
down:'Ungleichgewicht im Geben und Nehmen. Vorsicht vor einseitigen Beziehungen.'},
{id:'p7',name:'Sieben der Münzen',en:'Seven of Pentacles',emoji:'💰',suit:'pentacles',num:7,
up:'Samen säen und auf Ergebnisse warten. Geduld ist gefragt. Mühe trägt sicher Früchte.',
down:'Ungeduld, frustrierendes Ausbleiben sichtbarer Ergebnisse. Gib nicht auf – du bist fast am Ziel.'},
{id:'p8',name:'Acht der Münzen',en:'Eight of Pentacles',emoji:'💰',suit:'pentacles',num:8,
up:'Handwerksgeist! Eine Zeit des Schleifens von Fähigkeiten. Beständige Mühe macht den Meister.',
down:'Erschöpft von der Wiederholung, Motivationsverlust. Erinnere dich an dein Ziel.'},
{id:'p9',name:'Neun der Münzen',en:'Nine of Pentacles',emoji:'💰',suit:'pentacles',num:9,
up:'Unabhängigkeit und Überfluss! Genieße die Früchte deines Aufstiegs. Ein würdevolles Leben. Du hast es verdient.',
down:'Angst vor Unabhängigkeit, Abhängigkeit von anderen.'},
{id:'p10',name:'Zehn der Münzen',en:'Ten of Pentacles',emoji:'💰',suit:'pentacles',num:10,
up:'Materielle Vollendung! Familiärer Wohlstand, Erbe, langfristige Stabilität. Generationenübergreifender Reichtum und Glück.',
down:'Finanzieller Konflikt in der Familie, Erbschaftsprobleme. Beziehungen sind wichtiger als Materielles.'},
{id:'pP',name:'Bube der Münzen',en:'Page of Pentacles',emoji:'💰',suit:'pentacles',num:11,
up:'Neue Lernmöglichkeit oder finanzielle Gelegenheit. Fleißiges Lernen trägt Früchte.',
down:'Unrealistische Pläne, Faulheit.'},
{id:'pN',name:'Ritter der Münzen',en:'Knight of Pentacles',emoji:'💰',suit:'pentacles',num:12,
up:'Solide und zuverlässige Vorwärtsbewegung. Langsam aber sicher. Beständigkeit siegt.',
down:'Zu langsam, zu konservativ. Manchmal ist auch Kühnheit gefragt.'},
{id:'pQ',name:'Königin der Münzen',en:'Queen of Pentacles',emoji:'💰',suit:'pentacles',num:13,
up:'Praktische Weisheit und warmer Überfluss. Pragmatische und gleichzeitig großzügige Energie. Balance von Heim und Finanzen.',
down:'Mangelnde Selbstfürsorge, Workaholic.'},
{id:'pK',name:'König der Münzen',en:'King of Pentacles',emoji:'💰',suit:'pentacles',num:14,
up:'Finanzieller Erfolg und Stabilität! Geschäftssinn und pragmatische Führung. Reiche Früchte werden geerntet.',
down:'Gier, Materialismus. Geld ist nicht alles.'}
];
