// 78 Tarot Cards (Major 22 + Minor 56)
const TAROT_CARDS = [
// ═══════════════════════════════════════
// Major Arcana (0~21)
// ═══════════════════════════════════════
{id:'m0',name:'The Fool',en:'The Fool',emoji:'🃏',suit:'major',num:0,
up:'A new beginning stands before you. Let go of fear and take that first step. Now is the time to follow your instincts rather than calculate. Leap into the world with a pure heart. An unexpected adventure awaits you. Do not fear failure — the Fool is one who smiles and leaps even at the edge of a cliff.',
down:'You are acting too recklessly right now. Jumping in without preparation can lead to a serious mistake. Think it through once more and listen to the advice of those around you. Freedom and recklessness are not the same. Be wary of careless judgment.'},
{id:'m1',name:'The Magician',en:'The Magician',emoji:'🪄',suit:'major',num:1,
up:'All the tools and talents you need are already in place. Now is the time to focus and act. With willpower and creativity, you can achieve anything you desire. Like the Magician who bridges heaven and earth, turn your ideas into reality. Your words and actions carry power.',
down:'You are wasting your talents or using your abilities in the wrong place. Lack of confidence may be causing you to miss opportunities. Or your words and actions do not align. Reclaim your authenticity.'},
{id:'m2',name:'The High Priestess',en:'The High Priestess',emoji:'🌙',suit:'major',num:2,
up:'The answer is already within you. Trust intuition over logic. If you listen quietly to your inner voice, hidden truths will reveal themselves. Now is a time for observation rather than action. Read what lies beneath the surface. Mysterious wisdom is guiding you.',
down:'You are ignoring your intuition and relying only on appearances. Or there is a truth you know but are looking away from. Identify hidden motives. You need to look deeper.'},
{id:'m3',name:'The Empress',en:'The Empress',emoji:'🌺',suit:'major',num:3,
up:'A time of abundance and overflowing love. Enjoy your senses and take care of yourself. Creative energy is rising, making this a great time to create something new. Connecting with nature recharges your energy. Embrace those around you with motherly love. Pursuing beauty is not extravagance.',
down:'You are neglecting self-care or depending too much on others. If you feel a creative block, seek inspiration in nature. Be careful of jealousy or possessiveness.'},
{id:'m4',name:'The Emperor',en:'The Emperor',emoji:'👑',suit:'major',num:4,
up:'This is a time that calls for a systematic and decisive approach. Establishing discipline and order brings stability. Exercise leadership and act with responsibility. Reason must take precedence over emotion. The rules you set also give others a sense of security.',
down:'You are being too rigid or controlling. Enforcing rules without flexibility can invite backlash. Reflect on whether you are abusing authority. Sometimes stepping back is true strength.'},
{id:'m5',name:'The Hierophant',en:'The Hierophant',emoji:'🙏',suit:'major',num:5,
up:'You can find answers in traditional values or from a mentor. This is a time of learning, and spiritual growth is taking place. Feel a sense of belonging within your community. Following proven methods is safe. Giving and receiving teachings helps both grow.',
down:'The existing way of doing things no longer fits. It is time to break free from conventional thinking and find your own path. Rather than following blindly, judge for yourself. An unconventional approach may be the answer.'},
{id:'m6',name:'The Lovers',en:'The Lovers',emoji:'💕',suit:'major',num:6,
up:'Love is arriving, or you stand at an important crossroads. Follow where your heart leads. A genuine bond and harmony are being created. Meeting someone whose values align with yours can change your life. Be honest about love.',
down:'There is discord in a relationship or a clash of values is occurring. If you are being swayed by temptation, think about what you truly want. Take a step back before making the wrong choice.'},
{id:'m7',name:'The Chariot',en:'The Chariot',emoji:'⚡',suit:'major',num:7,
up:'Now is the time to break through obstacles with strong willpower! Do not stop — press forward. Decisiveness and focus bring victory. Harmoniously managing opposing forces allows you to reach your goal. You can win this.',
down:'You are losing direction and wavering. You are being carried away by emotions and losing control, or you are exhausting yourself by trying to do too many things at once. Stop for a moment and reset your direction.'},
{id:'m8',name:'Strength',en:'Strength',emoji:'🦁',suit:'major',num:8,
up:'Gentle strength overcomes brute force. Manage the situation with patience and courage. Do not suppress anger or fear — embrace them softly. Taming the inner beast is not violence but love. You are far stronger than you think.',
down:'You have lost confidence and become weak. You are being overwhelmed by emotions or falling into self-doubt. Reawaken your inner strength. Do not give up — there is a lion within you.'},
{id:'m9',name:'The Hermit',en:'The Hermit',emoji:'🔦',suit:'major',num:9,
up:'You need time alone. Step away from the noise and explore within. The answer is not outside but inside. This is a time when you can gain deep wisdom through meditation and reflection. Solitude is not loneliness — it is self-discovery.',
down:'You have been isolated for too long. You are trapped in your own thoughts, cut off from the world. It is time to reconnect with people. Asking for help is not weakness.'},
{id:'m10',name:'Wheel of Fortune',en:'Wheel of Fortune',emoji:'🎡',suit:'major',num:10,
up:'The wheel of fate is turning! Great change and good fortune are approaching. Do not miss the opportunity. This is a turning point where the cycle of life shifts. Go with the flow. Good things may happen in a chain reaction.',
down:'Misfortune is striking or you are resisting change. But remember — the wheel always turns. Bad times will always pass. Go with the flow and be patient.'},
{id:'m11',name:'Justice',en:'Justice',emoji:'⚖️',suit:'major',num:11,
up:'A fair outcome is coming. Acting truthfully and honestly leads to good results. If there is a legal matter, it may be resolved in your favor. The law of cause and effect is at work. Make the right choice.',
down:'You are in an unfair situation or avoiding responsibility. A lie may be exposed, so face the truth. Reflect on whether you are making a biased judgment.'},
{id:'m12',name:'The Hanged Man',en:'The Hanged Man',emoji:'🙃',suit:'major',num:12,
up:'Look at things from a different angle and the answer becomes clear. Now is a time for observation and waiting rather than action. This is not giving up — it is a pause to gain a new perspective. Paradoxically, you can gain more by letting go. Sacrifice ultimately returns as great reward.',
down:'You are exhausted by meaningless waiting. If the situation is stagnant, you need to change your perspective or take action. Stop the martyr act.'},
{id:'m13',name:'Death',en:'Death',emoji:'💀',suit:'major',num:13,
up:'An ending is a new beginning. Do not be afraid — this is not physical death but transformation. The old must be released for the new to come. A relationship, career, or habit is ending, but it is a necessary process. To become a butterfly, the caterpillar must die.',
down:'You are resisting necessary change. You are holding on to what needs to end. Let go. The longer you refuse change, the longer the pain lasts.'},
{id:'m14',name:'Temperance',en:'Temperance',emoji:'🌊',suit:'major',num:14,
up:'A time of balance and harmony. Avoid extremes and seek the middle path. Proceeding slowly and patiently brings good results. The ability to blend different elements harmoniously shines now. Pay attention to your physical and mental health as well.',
down:'You have lost balance and tilted to one side. Be careful of excess — drinking, eating, overworking. Impatience can ruin things. Restore your balance.'},
{id:'m15',name:'The Devil',en:'The Devil',emoji:'😈',suit:'major',num:15,
up:'You are obsessed or addicted to something. Bound by material things, pleasure, or a relationship. But those chains were put on by yourself and can be removed by yourself. Look your shadow in the eye. You must acknowledge it before you can escape.',
down:'You are breaking free from bondage! You are being liberated from bad habits or toxic relationships. Reclaim your freedom. There is nothing left to fear now.'},
{id:'m16',name:'The Tower',en:'The Tower',emoji:'🗼',suit:'major',num:16,
up:'A sudden change or shock may be coming. What you have built up may crumble, but this is something built on a wrong foundation falling apart. After the destruction, you can build something more solid. Truth is revealed like lightning.',
down:'You are trying to avoid an inevitable collapse. But if what must fall does not fall, a greater disaster comes. Accept the change.'},
{id:'m17',name:'The Star',en:'The Star',emoji:'⭐',suit:'major',num:17,
up:'The quiet starlight after the storm has passed. Hope is returning. Wounds are healing and inspiration is rising. The universe is helping you, so do not give up on your dreams. Show your true self as you are. You are shining.',
down:'You have lost hope and feel discouraged. But the stars are always there behind the clouds. Reclaim your faith in yourself. It is too early to give up.'},
{id:'m18',name:'The Moon',en:'The Moon',emoji:'🌙',suit:'major',num:18,
up:'It is a time like being in a fog where nothing is clear. Trust your intuition but do not fall into illusions. Pay attention to the messages of your unconscious. Dreams may give you important clues. Fears disappear when you face them.',
down:'The fog is lifting and the truth is beginning to show. Confusion resolves and things become clear. Something hidden is about to be revealed — be ready.'},
{id:'m19',name:'The Sun',en:'The Sun',emoji:'☀️',suit:'major',num:19,
up:'Bright, warm energy overflows! A time of success, joy, and vitality. Shine with confidence. Enjoy joy purely like a child. The darkness has passed and the sun has risen. A celebration is coming soon!',
down:'Success is coming but may be slightly delayed. You lack confidence or are not feeling joy fully. Maintain a positive mindset. The sun will always rise.'},
{id:'m20',name:'Judgement',en:'Judgement',emoji:'📯',suit:'major',num:20,
up:'You stand at a turning point in life. It is time to look back and settle the past. Discover your calling and be reborn. Forgiveness and liberation are occurring. Answer the inner call. You are ready to rise to a higher level.',
down:'You are stuck in the past, unable to escape due to self-doubt. Do not stay trapped in regret. Forgive yourself and move forward. There are second chances.'},
{id:'m21',name:'The World',en:'The World',emoji:'🌍',suit:'major',num:21,
up:'One great cycle is complete! You have achieved your goal and reached a state of integration. Congratulations! Travel, expansion, and new possibilities are opening up. One chapter ends and a new one begins.',
down:'You are almost there but the final step is missing. A finishing touch is needed for completion. Do not give up — the end is in sight. Shake off the regret of incompletion and do your best.'},

// ═══════════════════════════════════════
// Minor Arcana — Wands (Fire)
// ═══════════════════════════════════════
{id:'wA',name:'Ace of Wands',en:'Ace of Wands',emoji:'🔥',suit:'wands',num:1,
up:'New passion and inspiration surge up! A time of explosive creative energy. Perfect for starting a new project.',
down:'Loss of motivation, unable to get started. You have ideas but cannot turn them into action.'},
{id:'w2',name:'Two of Wands',en:'Two of Wands',emoji:'🔥',suit:'wands',num:2,
up:'Time to plan for the future and paint a big picture. The world is in your hands. A moment of decision.',
down:'Fear of planning, reluctance to leave the familiar. You are putting off a decision.'},
{id:'w3',name:'Three of Wands',en:'Three of Wands',emoji:'🔥',suit:'wands',num:3,
up:'The results of your efforts are beginning to show. Opportunity for expansion and growth. Good news comes from abroad or far away.',
down:'Disappointment that results are not as expected. Patience is needed.'},
{id:'w4',name:'Four of Wands',en:'Four of Wands',emoji:'🔥',suit:'wands',num:4,
up:'A time of celebration and joy! There is something to celebrate — a wedding, party, or move. A stable foundation has been created.',
down:'Unstable home environment, a celebration is delayed. The foundation is shaking.'},
{id:'w5',name:'Five of Wands',en:'Five of Wands',emoji:'🔥',suit:'wands',num:5,
up:'A time of competition and conflict. But this is healthy competition for growth. Hold your ground.',
down:'Avoid pointless fights. Compromise and cooperation are the answer.'},
{id:'w6',name:'Six of Wands',en:'Six of Wands',emoji:'🔥',suit:'wands',num:6,
up:'Victory and recognition! Your efforts are rewarded and praise pours in from those around you. Be confident.',
down:'Feeling unrecognized, watch out for arrogance. Stay humble.'},
{id:'w7',name:'Seven of Wands',en:'Seven of Wands',emoji:'🔥',suit:'wands',num:7,
up:'Time to stand and fight against challenges. Hold your position firmly. If you do not give up, you can win.',
down:'Feeling overwhelmed, an urge to quit. A strategic retreat is also an option.'},
{id:'w8',name:'Eight of Wands',en:'Eight of Wands',emoji:'🔥',suit:'wands',num:8,
up:'Things are moving quickly! News, travel, and change happen in an instant. Ride the wave.',
down:'Delays, frustration, waiting. Things are progressing slower than expected.'},
{id:'w9',name:'Nine of Wands',en:'Nine of Wands',emoji:'🔥',suit:'wands',num:9,
up:'It is hard but you are almost there. Endure the final trial. You are strong enough.',
down:'Exhaustion, burnout. You need to rest. Pushing too hard will cause a collapse.'},
{id:'w10',name:'Ten of Wands',en:'Ten of Wands',emoji:'🔥',suit:'wands',num:10,
up:'You are carrying too much. A sense of responsibility is good, but you do not need to do everything alone. Ask for help.',
down:'It is time to put down the burden. Free yourself from unnecessary responsibilities.'},
{id:'wP',name:'Page of Wands',en:'Page of Wands',emoji:'🔥',suit:'wands',num:11,
up:'Exciting news is coming! The beginning of a new adventure. Follow your curiosity.',
down:'Plans fall through or news is delayed.'},
{id:'wN',name:'Knight of Wands',en:'Knight of Wands',emoji:'🔥',suit:'wands',num:12,
up:'Time to charge forward with passion! Full of adventurous spirit and courage. Act boldly.',
down:'Watch out for impulsiveness and reckless action. You are running without direction.'},
{id:'wQ',name:'Queen of Wands',en:'Queen of Wands',emoji:'🔥',suit:'wands',num:13,
up:'Confident and charismatic energy! Exercise warm yet powerful leadership.',
down:'Jealousy, self-centered behavior. Recognize the light of others too.'},
{id:'wK',name:'King of Wands',en:'King of Wands',emoji:'🔥',suit:'wands',num:14,
up:'Vision and leadership accomplish great things. Lead people with charisma.',
down:'Authoritarian, tyrannical. Do not abuse power.'},

// ═══════════════════════════════════════
// Minor Arcana — Cups (Water)
// ═══════════════════════════════════════
{id:'cA',name:'Ace of Cups',en:'Ace of Cups',emoji:'💧',suit:'cups',num:1,
up:'New love, the beginning of emotion! A time when the heart overflows. You are ready to give and receive love.',
down:'Emotional emptiness, unable to accept love.'},
{id:'c2',name:'Two of Cups',en:'Two of Cups',emoji:'💧',suit:'cups',num:2,
up:'Deep bond and partnership. True love or friendship blossoms. A relationship of mutual respect.',
down:'Imbalance in a relationship, signs of separation.'},
{id:'c3',name:'Three of Cups',en:'Three of Cups',emoji:'💧',suit:'cups',num:3,
up:'Celebration, friendship, gathering! A joyful time spent with friends. Social activities bring good fortune.',
down:'Overindulgence, excess. You are missing important things while lost in pleasure.'},
{id:'c4',name:'Four of Cups',en:'Four of Cups',emoji:'💧',suit:'cups',num:4,
up:'Boredom, indifference. You are not seeing the opportunity right in front of you. Turn your gaze and discover new possibilities.',
down:'Beginning to accept new opportunities. Break free from lethargy.'},
{id:'c5',name:'Five of Cups',en:'Five of Cups',emoji:'💧',suit:'cups',num:5,
up:'Sadness and a sense of loss. Do not fixate on what has been spilled. Look back and you will find there is still something remaining.',
down:'Recovering from sorrow. Let go of the past and move forward.'},
{id:'c6',name:'Six of Cups',en:'Six of Cups',emoji:'💧',suit:'cups',num:6,
up:'Nostalgia, childhood memories, innocence. An old connection may return. Good memories from the past bring healing.',
down:'Clinging to the past, unable to live in the present. Move forward.'},
{id:'c7',name:'Seven of Cups',en:'Seven of Cups',emoji:'💧',suit:'cups',num:7,
up:'Overflowing with fantasies and options. But not everything is real. Judge realistically.',
down:'Waking from fantasy and making realistic choices.'},
{id:'c8',name:'Eight of Cups',en:'Eight of Cups',emoji:'💧',suit:'cups',num:8,
up:'It is time to leave what no longer fills you. A courageous letting go. Depart in search of deeper meaning.',
down:'You are staying where you should leave. Let go of your attachment.'},
{id:'c9',name:'Nine of Cups',en:'Nine of Cups',emoji:'💧',suit:'cups',num:9,
up:'Wish fulfilled! Overflowing with satisfaction and happiness. Enjoy joy with gratitude. Dreams come true.',
down:'Emptiness despite material abundance. True happiness lies within.'},
{id:'c10',name:'Ten of Cups',en:'Ten of Cups',emoji:'💧',suit:'cups',num:10,
up:'Perfect happiness! Family, love, harmony. A state of emotional fullness. A happy home under the rainbow.',
down:'Family discord, relationships falling short of expectations. Do not chase perfection.'},
{id:'cP',name:'Page of Cups',en:'Page of Cups',emoji:'💧',suit:'cups',num:11,
up:'An emotional message or proposal is coming. Trust your intuition. The beginning of a new emotion.',
down:'Emotional immaturity. Unrealistic expectations.'},
{id:'cN',name:'Knight of Cups',en:'Knight of Cups',emoji:'💧',suit:'cups',num:12,
up:'A romantic proposal is approaching! Artistic inspiration. Be true to your emotions.',
down:'Unrealistic fantasy, watch out for emotional manipulation.'},
{id:'cQ',name:'Queen of Cups',en:'Queen of Cups',emoji:'💧',suit:'cups',num:13,
up:'Deep empathy and intuition. The queen who rules the sea of emotion. Heal with love.',
down:'Overwhelmed by emotions, emotional dependency.'},
{id:'cK',name:'King of Cups',en:'King of Cups',emoji:'💧',suit:'cups',num:14,
up:'Wisdom and balance of emotion. Calm and compassionate leadership. The harmony of emotion and reason.',
down:'Emotional coldness, suppressing feelings.'},

// ═══════════════════════════════════════
// Minor Arcana — Swords (Air)
// ═══════════════════════════════════════
{id:'sA',name:'Ace of Swords',en:'Ace of Swords',emoji:'⚔️',suit:'swords',num:1,
up:'Clear truth, a breakthrough! A new idea strikes like lightning. Time for a decision.',
down:'Confusion, misinformation. Remove what clouds your judgment.'},
{id:'s2',name:'Two of Swords',en:'Two of Swords',emoji:'⚔️',suit:'swords',num:2,
up:'A deadlock unable to make a decision. Stop covering your eyes and face the truth.',
down:'As information emerges, a decision becomes possible.'},
{id:'s3',name:'Three of Swords',en:'Three of Swords',emoji:'⚔️',suit:'swords',num:3,
up:'Heartbreak, betrayal, separation. It hurts, but you grow through this pain. Do not suppress your emotions.',
down:'Recovering from a wound. The pain is slowly fading.'},
{id:'s4',name:'Four of Swords',en:'Four of Swords',emoji:'⚔️',suit:'swords',num:4,
up:'You need rest. Step back from the battle for a while and recharge. Meditation and rest are the answer.',
down:'You are overworking without rest. Risk of burnout.'},
{id:'s5',name:'Five of Swords',en:'Five of Swords',emoji:'⚔️',suit:'swords',num:5,
up:'Even winning comes at a high cost. Think about whether the victory is worth it. Using underhanded tactics will lead to regret.',
down:'Time to admit defeat and learn the lesson. Set aside your pride.'},
{id:'s6',name:'Six of Swords',en:'Six of Swords',emoji:'⚔️',suit:'swords',num:6,
up:'You are moving through a difficult period toward a better place. The pain of transition will soon be over.',
down:'Unable to leave, staying put. Accept the change.'},
{id:'s7',name:'Seven of Swords',en:'Seven of Swords',emoji:'⚔️',suit:'swords',num:7,
up:'Strategy is needed. Approach wisely rather than head-on. But deception will eventually be exposed.',
down:'The deception is uncovered. Honesty is the best strategy.'},
{id:'s8',name:'Eight of Swords',en:'Eight of Swords',emoji:'⚔️',suit:'swords',num:8,
up:'You feel trapped, but the bondage is actually something you created. Remove the blindfold and you can escape.',
down:'Beginning to break free from limitations. Move toward freedom.'},
{id:'s9',name:'Nine of Swords',en:'Nine of Swords',emoji:'⚔️',suit:'swords',num:9,
up:'Anxiety, nightmares, worry. The agony of sleepless nights. But most of what you fear is not reality.',
down:'The worst period is passing. Let go of worry.'},
{id:'s10',name:'Ten of Swords',en:'Ten of Swords',emoji:'⚔️',suit:'swords',num:10,
up:'You have hit rock bottom. Things cannot get any worse. But this is both an ending and a new beginning. The sun is rising.',
down:'Signs of recovery past the worst. The strength to rise again is growing.'},
{id:'sP',name:'Page of Swords',en:'Page of Swords',emoji:'⚔️',suit:'swords',num:11,
up:'Curiosity and sharp observation. New information or news. Uncover the truth.',
down:'Gossip, rumor, immature communication.'},
{id:'sN',name:'Knight of Swords',en:'Knight of Swords',emoji:'⚔️',suit:'swords',num:12,
up:'Fast and decisive action! Advance without hesitation. Fight for justice.',
down:'Impulsiveness, reckless charging. Think before you act.'},
{id:'sQ',name:'Queen of Swords',en:'Queen of Swords',emoji:'⚔️',suit:'swords',num:13,
up:'Clear judgment and independence. Wisdom that is not swayed by emotion. Face the truth.',
down:'Too cold, leaving a chilling impression. Empathy is also needed.'},
{id:'sK',name:'King of Swords',en:'King of Swords',emoji:'⚔️',suit:'swords',num:14,
up:'Intellectual authority and fair judgment. Make decisions with logic and ethics.',
down:'Dogmatic, inhumane judgment. Use your heart as well as your head.'},

// ═══════════════════════════════════════
// Minor Arcana — Pentacles (Earth)
// ═══════════════════════════════════════
{id:'pA',name:'Ace of Pentacles',en:'Ace of Pentacles',emoji:'💰',suit:'pentacles',num:1,
up:'A new financial opportunity! The seed of investment, employment, or business. The start of material abundance.',
down:'Watch out for missing an opportunity or financial loss.'},
{id:'p2',name:'Two of Pentacles',en:'Two of Pentacles',emoji:'💰',suit:'pentacles',num:2,
up:'Finding balance. Managing multiple things at once. Respond flexibly.',
down:'About to collapse from losing balance. Set your priorities.'},
{id:'p3',name:'Three of Pentacles',en:'Three of Pentacles',emoji:'💰',suit:'pentacles',num:3,
up:'Achieving results through teamwork and cooperation. Expertise is recognized. Working together brings better results.',
down:'Failed trying to do it alone. Recognize the value of cooperation.'},
{id:'p4',name:'Four of Pentacles',en:'Four of Pentacles',emoji:'💰',suit:'pentacles',num:4,
up:'Stability and security. Financially safe, but holding on too tightly can cause you to miss new opportunities.',
down:'Stinginess, excessive attachment to material things. Giving brings more in return.'},
{id:'p5',name:'Five of Pentacles',en:'Five of Pentacles',emoji:'💰',suit:'pentacles',num:5,
up:'Financial difficulty, a sense of isolation. It is a hard time, but help is nearby. Look up.',
down:'The worst situation is passing. The light of recovery is visible.'},
{id:'p6',name:'Six of Pentacles',en:'Six of Pentacles',emoji:'💰',suit:'pentacles',num:6,
up:'The balance of giving and receiving. Generosity brings blessings. It is a time to give or receive help.',
down:'Imbalance in giving and receiving. Watch out for a lopsided relationship.'},
{id:'p7',name:'Seven of Pentacles',en:'Seven of Pentacles',emoji:'💰',suit:'pentacles',num:7,
up:'Planting seeds and waiting for results. Patience is needed. Effort will always bear fruit.',
down:'Impatience, frustration at not seeing results. Do not give up — you are almost there.'},
{id:'p8',name:'Eight of Pentacles',en:'Eight of Pentacles',emoji:'💰',suit:'pentacles',num:8,
up:'Mastery! A time to hone your skills. Consistent effort creates an expert.',
down:'Tired of repetition, loss of motivation. Remind yourself of your goal.'},
{id:'p9',name:'Nine of Pentacles',en:'Nine of Pentacles',emoji:'💰',suit:'pentacles',num:9,
up:'Independence and abundance! Enjoy the fruits of your self-reliance. A life of refinement. You deserve it.',
down:'Anxiety about independence, depending on others.'},
{id:'p10',name:'Ten of Pentacles',en:'Ten of Pentacles',emoji:'💰',suit:'pentacles',num:10,
up:'Material completion! Family prosperity, legacy, long-term stability. Wealth and happiness passed down through generations.',
down:'Financial conflict within the family, inheritance issues. Relationships matter more than material things.'},
{id:'pP',name:'Page of Pentacles',en:'Page of Pentacles',emoji:'💰',suit:'pentacles',num:11,
up:'News of new learning or a financial opportunity. Studying diligently brings results.',
down:'Unrealistic plans, laziness.'},
{id:'pN',name:'Knight of Pentacles',en:'Knight of Pentacles',emoji:'💰',suit:'pentacles',num:12,
up:'Steady and diligent progress. Slow but certain advancement. Consistency wins.',
down:'Too slow, overly conservative. Sometimes boldness is also needed.'},
{id:'pQ',name:'Queen of Pentacles',en:'Queen of Pentacles',emoji:'💰',suit:'pentacles',num:13,
up:'Practical wisdom and warm abundance. A practical yet generous energy. Balance of home and finances.',
down:'Lack of self-care, workaholic tendencies.'},
{id:'pK',name:'King of Pentacles',en:'King of Pentacles',emoji:'💰',suit:'pentacles',num:14,
up:'Financial success and stability! Business acumen and practical leadership. Reaping abundant results.',
down:'Greed, worship of money. Money is not everything.'}
];
