// 78 Tarot Cards (Major 22 + Minor 56)
const TAROT_CARDS = [
// ═══════════════════════════════════════
// Major Arcana (0~21)
// ═══════════════════════════════════════
{id:'m0',name:'The Fool',en:'The Fool',emoji:'🃏',suit:'major',num:0,
up:'A new beginning stands before you. Let go of fear and take that first step. Now is the time to follow your instincts rather than calculate. Leap into the world with a pure heart. An unexpected adventure awaits you. Do not fear failure — the Fool is one who smiles and leaps even at the edge of a cliff.',
down:'You are acting too recklessly right now. Jumping in without preparation can lead to a serious mistake. Think it through once more and listen to the advice of those around you. Freedom and recklessness are not the same. Be wary of careless judgment.'},
{id:'m1',name:'The Magician',en:'The Magician',emoji:'🪄',suit:'major',num:1,
up:'All the tools and talents you need are already in place. Now is the time to focus and act. With willpower and creativity, you can achieve anything you desire. Like the Magician who bridges heaven and earth, turn your ideas into reality. Your words and actions carry power.',
down:'You are wasting your talents or using your abilities in the wrong place. Lack of confidence may be causing you to miss opportunities. Or your words and actions do not align. Reclaim your authenticity.'},
{id:'m2',name:'The High Priestess',en:'The High Priestess',emoji:'🌙',suit:'major',num:2,
up:'The answer is already within you. Trust intuition over logic. If you listen quietly to your inner voice, hidden truths will reveal themselves. Now is a time for observation rather than action. Read what lies beneath the surface. Mysterious wisdom is guiding you.',
down:'You are ignoring your intuition and relying only on appearances. Or there is a truth you know but are looking away from. Identify hidden motives. You need to look deeper.'},
{id:'m3',name:'The Empress',en:'The Empress',emoji:'🌺',suit:'major',num:3,
up:'A time of abundance and overflowing love. Enjoy your senses and take care of yourself. Creative energy is rising, making this a great time to create something new. Connecting with nature recharges your energy. Embrace those around you with motherly love. Pursuing beauty is not extravagance.',
down:'You are neglecting self-care or depending too much on others. If you feel a creative block, seek inspiration in nature. Be careful of jealousy or possessiveness.'},
{id:'m4',name:'The Emperor',en:'The Emperor',emoji:'👑',suit:'major',num:4,
up:'This is a time that calls for a systematic and decisive approach. Establishing discipline and order brings stability. Exercise leadership and act with responsibility. Reason must take precedence over emotion. The rules you set also give others a sense of security.',
down:'You are being too rigid or controlling. Enforcing rules without flexibility can invite backlash. Reflect on whether you are abusing authority. Sometimes stepping back is true strength.'},
{id:'m5',name:'The Hierophant',en:'The Hierophant',emoji:'🙏',suit:'major',num:5,
up:'You can find answers in traditional values or from a mentor. This is a time of learning, and spiritual growth is taking place. Feel a sense of belonging within your community. Following proven methods is safe. Giving and receiving teachings helps both grow.',
down:'The existing way of doing things no longer fits. It is time to break free from conventional thinking and find your own path. Rather than following blindly, judge for yourself. An unconventional approach may be the answer.'},
{id:'m6',name:'The Lovers',en:'The Lovers',emoji:'💕',suit:'major',num:6,
up:'Love is arriving, or you stand at an important crossroads. Follow where your heart leads. A genuine bond and harmony are being created. Meeting someone whose values align with yours can change your life. Be honest about love.',
down:'There is discord in a relationship or a clash of values is occurring. If you are being swayed by temptation, think about what you truly want. Take a step back before making the wrong choice.'},
{id:'m7',name:'The Chariot',en:'The Chariot',emoji:'⚡',suit:'major',num:7,
up:'Now is the time to break through obstacles with strong willpower! Do not stop — press forward. Decisiveness and focus bring victory. Harmoniously managing opposing forces allows you to reach your goal. You can win this.',
down:'You are losing direction and wavering. You are being carried away by emotions and losing control, or you are exhausting yourself by trying to do too many things at once. Stop for a moment and reset your direction.'},
{id:'m8',name:'Strength',en:'Strength',emoji:'🦁',suit:'major',num:8,
up:'Gentle strength overcomes brute force. Manage the situation with patience and courage. Do not suppress anger or fear — embrace them softly. Taming the inner beast is not violence but love. You are far stronger than you think.',
down:'You have lost confidence and become weak. You are being overwhelmed by emotions or falling into self-doubt. Reawaken your inner strength. Do not give up — there is a lion within you.'},
{id:'m9',name:'The Hermit',en:'The Hermit',emoji:'🔦',suit:'major',num:9,
up:'You need time alone. Step away from the noise and explore within. The answer is not outside but inside. This is a time when you can gain deep wisdom through meditation and reflection. Solitude is not loneliness — it is self-discovery.',
down:'You have been isolated for too long. You are trapped in your own thoughts, cut off from the world. It is time to reconnect with people. Asking for help is not weakness.'},
{id:'m10',name:'Wheel of Fortune',en:'Wheel of Fortune',emoji:'🎡',suit:'major',num:10,
up:'The wheel of fate is turning! Great change and good fortune are approaching. Do not miss the opportunity. This is a turning point where the cycle of life shifts. Go with the flow. Good things may happen in a chain reaction.',
down:'Misfortune is striking or you are resisting change. But remember — the wheel always turns. Bad times will always pass. Go with the flow and be patient.'},
{id:'m11',name:'Justice',en:'Justice',emoji:'⚖️',suit:'major',num:11,
up:'A fair outcome is coming. Acting truthfully and honestly leads to good results. If there is a legal matter, it may be resolved in your favor. The law of cause and effect is at work. Make the right choice.',
down:'You are in an unfair situation or avoiding responsibility. A lie may be exposed, so face the truth. Reflect on whether you are making a biased judgment.'},
{id:'m12',name:'The Hanged Man',en:'The Hanged Man',emoji:'🙃',suit:'major',num:12,
up:'Look at things from a different angle and the answer becomes clear. Now is a time for observation and waiting rather than action. This is not giving up — it is a pause to gain a new perspective. Paradoxically, you can gain more by letting go. Sacrifice ultimately returns as great reward.',
down:'You are exhausted by meaningless waiting. If the situation is stagnant, you need to change your perspective or take action. Stop the martyr act.'},
{id:'m13',name:'Death',en:'Death',emoji:'💀',suit:'major',num:13,
up:'An ending is a new beginning. Do not be afraid — this is not physical death but transformation. The old must be released for the new to come. A relationship, career, or habit is ending, but it is a necessary process. To become a butterfly, the caterpillar must die.',
down:'You are resisting necessary change. You are holding on to what needs to end. Let go. The longer you refuse change, the longer the pain lasts.'},
{id:'m14',name:'Temperance',en:'Temperance',emoji:'🌊',suit:'major',num:14,
up:'A time of balance and harmony. Avoid extremes and seek the middle path. Proceeding slowly and patiently brings good results. The ability to blend different elements harmoniously shines now. Pay attention to your physical and mental health as well.',
down:'You have lost balance and tilted to one side. Be careful of excess — drinking, eating, overworking. Impatience can ruin things. Restore your balance.'},
{id:'m15',name:'The Devil',en:'The Devil',emoji:'😈',suit:'major',num:15,
up:'You are obsessed or addicted to something. Bound by material things, pleasure, or a relationship. But those chains were put on by yourself and can be removed by yourself. Look your shadow in the eye. You must acknowledge it before you can escape.',
down:'You are breaking free from bondage! You are being liberated from bad habits or toxic relationships. Reclaim your freedom. There is nothing left to fear now.'},
{id:'m16',name:'The Tower',en:'The Tower',emoji:'🗼',suit:'major',num:16,
up:'A sudden change or shock may be coming. What you have built up may crumble, but this is something built on a wrong foundation falling apart. After the destruction, you can build something more solid. Truth is revealed like lightning.',
down:'You are trying to avoid an inevitable collapse. But if what must fall does not fall, a greater disaster comes. Accept the change.'},
{id:'m17',name:'The Star',en:'The Star',emoji:'⭐',suit:'major',num:17,
up:'The quiet starlight after the storm has passed. Hope is returning. Wounds are healing and inspiration is rising. The universe is helping you, so do not give up on your dreams. Show your true self as you are. You are shining.',
down:'You have lost hope and feel discouraged. But the stars are always there behind the clouds. Reclaim your faith in yourself. It is too early to give up.'},
{id:'m18',name:'The Moon',en:'The Moon',emoji:'🌙',suit:'major',num:18,
up:'It is a time like being in a fog where nothing is clear. Trust your intuition but do not fall into illusions. Pay attention to the messages of your unconscious. Dreams may give you important clues. Fears disappear when you face them.',
down:'The fog is lifting and the truth is beginning to show. Confusion resolves and things become clear. Something hidden is about to be revealed — be ready.'},
{id:'m19',name:'The Sun',en:'The Sun',emoji:'☀️',suit:'major',num:19,
up:'Bright, warm energy overflows! A time of success, joy, and vitality. Shine with confidence. Enjoy joy purely like a child. The darkness has passed and the sun has risen. A celebration is coming soon!',
down:'Success is coming but may be slightly delayed. You lack confidence or are not feeling joy fully. Maintain a positive mindset. The sun will always rise.'},
{id:'m20',name:'Judgement',en:'Judgement',emoji:'📯',suit:'major',num:20,
up:'You stand at a turning point in life. It is time to look back and settle the past. Discover your calling and be reborn. Forgiveness and liberation are occurring. Answer the inner call. You are ready to rise to a higher level.',
down:'You are stuck in the past, unable to escape due to self-doubt. Do not stay trapped in regret. Forgive yourself and move forward. There are second chances.'},
{id:'m21',name:'The World',en:'The World',emoji:'🌍',suit:'major',num:21,
up:'One great cycle is complete! You have achieved your goal and reached a state of integration. Congratulations! Travel, expansion, and new possibilities are opening up. One chapter ends and a new one begins.',
down:'You are almost there but the final step is missing. A finishing touch is needed for completion. Do not give up — the end is in sight. Shake off the regret of incompletion and do your best.'},

// ═══════════════════════════════════════
// Minor Arcana — Wands (Fire)
// ═══════════════════════════════════════
{id:'wA',name:'Ace of Wands',en:'Ace of Wands',emoji:'🔥',suit:'wands',num:1,
up:'New passion and inspiration surge up! A time of explosive creative energy. Perfect for starting a new project.',
down:'Loss of motivation, unable to get started. You have ideas but cannot turn them into action.'},
{id:'w2',name:'Two of Wands',en:'Two of Wands',emoji:'🔥',suit:'wands',num:2,
up:'Time to plan for the future and paint a big picture. The world is in your hands. A moment of decision.',
down:'Fear of planning, reluctance to leave the familiar. You are putting off a decision.'},
{id:'w3',name:'Three of Wands',en:'Three of Wands',emoji:'🔥',suit:'wands',num:3,
up:'The results of your efforts are beginning to show. Opportunity for expansion and growth. Good news comes from abroad or far away.',
down:'Disappointment that results are not as expected. Patience is needed.'},
{id:'w4',name:'Four of Wands',en:'Four of Wands',emoji:'🔥',suit:'wands',num:4,
up:'A time of celebration and joy! There is something to celebrate — a wedding, party, or move. A stable foundation has been created.',
down:'Unstable home environment, a celebration is delayed. The foundation is shaking.'},
{id:'w5',name:'Five of Wands',en:'Five of Wands',emoji:'🔥',suit:'wands',num:5,
up:'A time of competition and conflict. But this is healthy competition for growth. Hold your ground.',
down:'Avoid pointless fights. Compromise and cooperation are the answer.'},
{id:'w6',name:'Six of Wands',en:'Six of Wands',emoji:'🔥',suit:'wands',num:6,
up:'Victory and recognition! Your efforts are rewarded and praise pours in from those around you. Be confident.',
down:'Feeling unrecognized, watch out for arrogance. Stay humble.'},
{id:'w7',name:'Seven of Wands',en:'Seven of Wands',emoji:'🔥',suit:'wands',num:7,
up:'Time to stand and fight against challenges. Hold your position firmly. If you do not give up, you can win.',
down:'Feeling overwhelmed, an urge to quit. A strategic retreat is also an option.'},
{id:'w8',name:'Eight of Wands',en:'Eight of Wands',emoji:'🔥',suit:'wands',num:8,
up:'Things are moving quickly! News, travel, and change happen in an instant. Ride the wave.',
down:'Delays, frustration, waiting. Things are progressing slower than expected.'},
{id:'w9',name:'Nine of Wands',en:'Nine of Wands',emoji:'🔥',suit:'wands',num:9,
up:'It is hard but you are almost there. Endure the final trial. You are strong enough.',
down:'Exhaustion, burnout. You need to rest. Pushing too hard will cause a collapse.'},
{id:'w10',name:'Ten of Wands',en:'Ten of Wands',emoji:'🔥',suit:'wands',num:10,
up:'You are carrying too much. A sense of responsibility is good, but you do not need to do everything alone. Ask for help.',
down:'It is time to put down the burden. Free yourself from unnecessary responsibilities.'},
{id:'wP',name:'Page of Wands',en:'Page of Wands',emoji:'🔥',suit:'wands',num:11,
up:'Exciting news is coming! The beginning of a new adventure. Follow your curiosity.',
down:'Plans fall through or news is delayed.'},
{id:'wN',name:'Knight of Wands',en:'Knight of Wands',emoji:'🔥',suit:'wands',num:12,
up:'Time to charge forward with passion! Full of adventurous spirit and courage. Act boldly.',
down:'Watch out for impulsiveness and reckless action. You are running without direction.'},
{id:'wQ',name:'Queen of Wands',en:'Queen of Wands',emoji:'🔥',suit:'wands',num:13,
up:'Confident and charismatic energy! Exercise warm yet powerful leadership.',
down:'Jealousy, self-centered behavior. Recognize the light of others too.'},
{id:'wK',name:'King of Wands',en:'King of Wands',emoji:'🔥',suit:'wands',num:14,
up:'Vision and leadership accomplish great things. Lead people with charisma.',
down:'Authoritarian, tyrannical. Do not abuse power.'},

// ═══════════════════════════════════════
// Minor Arcana — Cups (Water)
// ═══════════════════════════════════════
{id:'cA',name:'Ace of Cups',en:'Ace of Cups',emoji:'💧',suit:'cups',num:1,
up:'New love, the beginning of emotion! A time when the heart overflows. You are ready to give and receive love.',
down:'Emotional emptiness, unable to accept love.'},
{id:'c2',name:'Two of Cups',en:'Two of Cups',emoji:'💧',suit:'cups',num:2,
up:'Deep bond and partnership. True love or friendship blossoms. A relationship of mutual respect.',
down:'Imbalance in a relationship, signs of separation.'},
{id:'c3',name:'Three of Cups',en:'Three of Cups',emoji:'💧',suit:'cups',num:3,
up:'Celebration, friendship, gathering! A joyful time spent with friends. Social activities bring good fortune.',
down:'Overindulgence, excess. You are missing important things while lost in pleasure.'},
{id:'c4',name:'Four of Cups',en:'Four of Cups',emoji:'💧',suit:'cups',num:4,
up:'Boredom, indifference. You are not seeing the opportunity right in front of you. Turn your gaze and discover new possibilities.',
down:'Beginning to accept new opportunities. Break free from lethargy.'},
{id:'c5',name:'Five of Cups',en:'Five of Cups',emoji:'💧',suit:'cups',num:5,
up:'Sadness and a sense of loss. Do not fixate on what has been spilled. Look back and you will find there is still something remaining.',
down:'Recovering from sorrow. Let go of the past and move forward.'},
{id:'c6',name:'Six of Cups',en:'Six of Cups',emoji:'💧',suit:'cups',num:6,
up:'Nostalgia, childhood memories, innocence. An old connection may return. Good memories from the past bring healing.',
down:'Clinging to the past, unable to live in the present. Move forward.'},
{id:'c7',name:'Seven of Cups',en:'Seven of Cups',emoji:'💧',suit:'cups',num:7,
up:'Overflowing with fantasies and options. But not everything is real. Judge realistically.',
down:'Waking from fantasy and making realistic choices.'},
{id:'c8',name:'Eight of Cups',en:'Eight of Cups',emoji:'💧',suit:'cups',num:8,
up:'It is time to leave what no longer fills you. A courageous letting go. Depart in search of deeper meaning.',
down:'You are staying where you should leave. Let go of your attachment.'},
{id:'c9',name:'Nine of Cups',en:'Nine of Cups',emoji:'💧',suit:'cups',num:9,
up:'Wish fulfilled! Overflowing with satisfaction and happiness. Enjoy joy with gratitude. Dreams come true.',
down:'Emptiness despite material abundance. True happiness lies within.'},
{id:'c10',name:'Ten of Cups',en:'Ten of Cups',emoji:'💧',suit:'cups',num:10,
up:'Perfect happiness! Family, love, harmony. A state of emotional fullness. A happy home under the rainbow.',
down:'Family discord, relationships falling short of expectations. Do not chase perfection.'},
{id:'cP',name:'Page of Cups',en:'Page of Cups',emoji:'💧',suit:'cups',num:11,
up:'An emotional message or proposal is coming. Trust your intuition. The beginning of a new emotion.',
down:'Emotional immaturity. Unrealistic expectations.'},
{id:'cN',name:'Knight of Cups',en:'Knight of Cups',emoji:'💧',suit:'cups',num:12,
up:'A romantic proposal is approaching! Artistic inspiration. Be true to your emotions.',
down:'Unrealistic fantasy, watch out for emotional manipulation.'},
{id:'cQ',name:'Queen of Cups',en:'Queen of Cups',emoji:'💧',suit:'cups',num:13,
up:'Deep empathy and intuition. The queen who rules the sea of emotion. Heal with love.',
down:'Overwhelmed by emotions, emotional dependency.'},
{id:'cK',name:'King of Cups',en:'King of Cups',emoji:'💧',suit:'cups',num:14,
up:'Wisdom and balance of emotion. Calm and compassionate leadership. The harmony of emotion and reason.',
down:'Emotional coldness, suppressing feelings.'},

// ═══════════════════════════════════════
// Minor Arcana — Swords (Air)
// ═══════════════════════════════════════
{id:'sA',name:'Ace of Swords',en:'Ace of Swords',emoji:'⚔️',suit:'swords',num:1,
up:'Clear truth, a breakthrough! A new idea strikes like lightning. Time for a decision.',
down:'Confusion, misinformation. Remove what clouds your judgment.'},
{id:'s2',name:'Two of Swords',en:'Two of Swords',emoji:'⚔️',suit:'swords',num:2,
up:'A deadlock unable to make a decision. Stop covering your eyes and face the truth.',
down:'As information emerges, a decision becomes possible.'},
{id:'s3',name:'Three of Swords',en:'Three of Swords',emoji:'⚔️',suit:'swords',num:3,
up:'Heartbreak, betrayal, separation. It hurts, but you grow through this pain. Do not suppress your emotions.',
down:'Recovering from a wound. The pain is slowly fading.'},
{id:'s4',name:'Four of Swords',en:'Four of Swords',emoji:'⚔️',suit:'swords',num:4,
up:'You need rest. Step back from the battle for a while and recharge. Meditation and rest are the answer.',
down:'You are overworking without rest. Risk of burnout.'},
{id:'s5',name:'Five of Swords',en:'Five of Swords',emoji:'⚔️',suit:'swords',num:5,
up:'Even winning comes at a high cost. Think about whether the victory is worth it. Using underhanded tactics will lead to regret.',
down:'Time to admit defeat and learn the lesson. Set aside your pride.'},
{id:'s6',name:'Six of Swords',en:'Six of Swords',emoji:'⚔️',suit:'swords',num:6,
up:'You are moving through a difficult period toward a better place. The pain of transition will soon be over.',
down:'Unable to leave, staying put. Accept the change.'},
{id:'s7',name:'Seven of Swords',en:'Seven of Swords',emoji:'⚔️',suit:'swords',num:7,
up:'Strategy is needed. Approach wisely rather than head-on. But deception will eventually be exposed.',
down:'The deception is uncovered. Honesty is the best strategy.'},
{id:'s8',name:'Eight of Swords',en:'Eight of Swords',emoji:'⚔️',suit:'swords',num:8,
up:'You feel trapped, but the bondage is actually something you created. Remove the blindfold and you can escape.',
down:'Beginning to break free from limitations. Move toward freedom.'},
{id:'s9',name:'Nine of Swords',en:'Nine of Swords',emoji:'⚔️',suit:'swords',num:9,
up:'Anxiety, nightmares, worry. The agony of sleepless nights. But most of what you fear is not reality.',
down:'The worst period is passing. Let go of worry.'},
{id:'s10',name:'Ten of Swords',en:'Ten of Swords',emoji:'⚔️',suit:'swords',num:10,
up:'You have hit rock bottom. Things cannot get any worse. But this is both an ending and a new beginning. The sun is rising.',
down:'Signs of recovery past the worst. The strength to rise again is growing.'},
{id:'sP',name:'Page of Swords',en:'Page of Swords',emoji:'⚔️',suit:'swords',num:11,
up:'Curiosity and sharp observation. New information or news. Uncover the truth.',
down:'Gossip, rumor, immature communication.'},
{id:'sN',name:'Knight of Swords',en:'Knight of Swords',emoji:'⚔️',suit:'swords',num:12,
up:'Fast and decisive action! Advance without hesitation. Fight for justice.',
down:'Impulsiveness, reckless charging. Think before you act.'},
{id:'sQ',name:'Queen of Swords',en:'Queen of Swords',emoji:'⚔️',suit:'swords',num:13,
up:'Clear judgment and independence. Wisdom that is not swayed by emotion. Face the truth.',
down:'Too cold, leaving a chilling impression. Empathy is also needed.'},
{id:'sK',name:'King of Swords',en:'King of Swords',emoji:'⚔️',suit:'swords',num:14,
up:'Intellectual authority and fair judgment. Make decisions with logic and ethics.',
down:'Dogmatic, inhumane judgment. Use your heart as well as your head.'},

// ═══════════════════════════════════════
// Minor Arcana — Pentacles (Earth)
// ═══════════════════════════════════════
{id:'pA',name:'Ace of Pentacles',en:'Ace of Pentacles',emoji:'💰',suit:'pentacles',num:1,
up:'A new financial opportunity! The seed of investment, employment, or business. The start of material abundance.',
down:'Watch out for missing an opportunity or financial loss.'},
{id:'p2',name:'Two of Pentacles',en:'Two of Pentacles',emoji:'💰',suit:'pentacles',num:2,
up:'Finding balance. Managing multiple things at once. Respond flexibly.',
down:'About to collapse from losing balance. Set your priorities.'},
{id:'p3',name:'Three of Pentacles',en:'Three of Pentacles',emoji:'💰',suit:'pentacles',num:3,
up:'Achieving results through teamwork and cooperation. Expertise is recognized. Working together brings better results.',
down:'Failed trying to do it alone. Recognize the value of cooperation.'},
{id:'p4',name:'Four of Pentacles',en:'Four of Pentacles',emoji:'💰',suit:'pentacles',num:4,
up:'Stability and security. Financially safe, but holding on too tightly can cause you to miss new opportunities.',
down:'Stinginess, excessive attachment to material things. Giving brings more in return.'},
{id:'p5',name:'Five of Pentacles',en:'Five of Pentacles',emoji:'💰',suit:'pentacles',num:5,
up:'Financial difficulty, a sense of isolation. It is a hard time, but help is nearby. Look up.',
down:'The worst situation is passing. The light of recovery is visible.'},
{id:'p6',name:'Six of Pentacles',en:'Six of Pentacles',emoji:'💰',suit:'pentacles',num:6,
up:'The balance of giving and receiving. Generosity brings blessings. It is a time to give or receive help.',
down:'Imbalance in giving and receiving. Watch out for a lopsided relationship.'},
{id:'p7',name:'Seven of Pentacles',en:'Seven of Pentacles',emoji:'💰',suit:'pentacles',num:7,
up:'Planting seeds and waiting for results. Patience is needed. Effort will always bear fruit.',
down:'Impatience, frustration at not seeing results. Do not give up — you are almost there.'},
{id:'p8',name:'Eight of Pentacles',en:'Eight of Pentacles',emoji:'💰',suit:'pentacles',num:8,
up:'Mastery! A time to hone your skills. Consistent effort creates an expert.',
down:'Tired of repetition, loss of motivation. Remind yourself of your goal.'},
{id:'p9',name:'Nine of Pentacles',en:'Nine of Pentacles',emoji:'💰',suit:'pentacles',num:9,
up:'Independence and abundance! Enjoy the fruits of your self-reliance. A life of refinement. You deserve it.',
down:'Anxiety about independence, depending on others.'},
{id:'p10',name:'Ten of Pentacles',en:'Ten of Pentacles',emoji:'💰',suit:'pentacles',num:10,
up:'Material completion! Family prosperity, legacy, long-term stability. Wealth and happiness passed down through generations.',
down:'Financial conflict within the family, inheritance issues. Relationships matter more than material things.'},
{id:'pP',name:'Page of Pentacles',en:'Page of Pentacles',emoji:'💰',suit:'pentacles',num:11,
up:'News of new learning or a financial opportunity. Studying diligently brings results.',
down:'Unrealistic plans, laziness.'},
{id:'pN',name:'Knight of Pentacles',en:'Knight of Pentacles',emoji:'💰',suit:'pentacles',num:12,
up:'Steady and diligent progress. Slow but certain advancement. Consistency wins.',
down:'Too slow, overly conservative. Sometimes boldness is also needed.'},
{id:'pQ',name:'Queen of Pentacles',en:'Queen of Pentacles',emoji:'💰',suit:'pentacles',num:13,
up:'Practical wisdom and warm abundance. A practical yet generous energy. Balance of home and finances.',
down:'Lack of self-care, workaholic tendencies.'},
{id:'pK',name:'King of Pentacles',en:'King of Pentacles',emoji:'💰',suit:'pentacles',num:14,
up:'Financial success and stability! Business acumen and practical leadership. Reaping abundant results.',
down:'Greed, worship of money. Money is not everything.'}
];

// ═══════════════════════════════════════
// UI Text
// ═══════════════════════════════════════
const TAROT_UI = {
    pageTitle: "🃏 Tarot Cards",
    pageSubtitle: "Draw a card and read your destiny",
    modeNormal: "🃏 Normal Tarot",
    modeOshi: "💜 Oshi Tarot",
    spreadOne: '💫 <strong>One Card</strong> <span style="font-size:12px;color:#888;margin-left:8px;">Quick answer · 1 card</span>',
    spreadThree: '⏳ <strong>Past · Present · Future</strong> <span style="font-size:12px;color:#888;margin-left:8px;">Flow of time · 3 cards</span>',
    spreadFive: '⭐ <strong>In-Depth Reading</strong> <span style="font-size:12px;color:#888;margin-left:8px;">Detailed analysis · 5 cards</span>',
    questionText: "✨ Hold your question in mind<br>and choose your cards ✨",
    questionSub: "The cards are chosen by your subconscious",
    oshiTitle: "💜 Enter your oshi's name",
    oshiPlaceholder: "e.g. Gojo Satoru, Levi, Kamina...",
    oshiHint: "Anime / manga / game / idol — anyone is OK!",
    oshiQuestionText: "✨ Picture that person in your mind<br>and choose your cards ✨",
    oshiQuestionSub: "The cards reveal your oshi's hidden feelings",
    btnShuffle: "🃏 Shuffle Cards",
    btnShuffleOshi: "💜 Shuffle Cards",
    btnReshuffle: "🔄 Shuffle Again",
    pickInstruction: "Choose <strong>{n} cards</strong>",
    pickMore: "Choose <strong>{n} more</strong>",
    pickDone: "✨ All cards have been selected!",
    disclaimer: "🃏 Tarot is a tool for fun and self-reflection. For important decisions, consult a professional.",
    positions3: ["Past", "Present", "Future"],
    positions5: ["Current Situation", "Challenge / Obstacle", "Past Influence", "Near Future", "Final Outcome"],
    oshiPositions3: ["When they first saw you", "How they feel about you now", "What they'll do for you"],
    oshiPositions5: ["First impression", "What they're hiding", "Their true feelings", "What they want from you", "Where you two are headed"],
    todayCard: "Today's Card",
    oshiOneCard: "{name}'s Message",
    reversed: "Reversed ↓",
    upright: "Upright ↑",
    summaryTitle: "🃏 Overall Reading",
    oshiSummaryTitle: "💜 {name}'s Overall Feelings",
    summaryPositive: "Positive energy is dominant. Have confidence in yourself.",
    summaryChallenge: "It's a challenging time, but reversed cards can also signify inner growth.",
    summaryMainCard: "The key card of this reading is <strong>{emoji} {card}</strong>.",
    summaryReversed: "It appeared reversed, so be mindful of {text}.",
    summaryUpright: "The energy of {text} is strong.",
    summaryOverall: "{up} cards are upright and {down} cards are reversed overall.",
    oshiMainCard: "The key card is <strong>{emoji} {card}</strong>.",
    oshiCount: "{up} upright, {down} reversed.",
    oshiPositive: "According to {name}, they hold positive feelings toward you overall. It seems like a good time to open your heart and reach out.",
    oshiChallenge: "According to {name}, they're in the midst of complex emotions. But deep down, they hold you dear. They just need a little more time.",
    defaultOshiName: "That Person",
    suitLabels: {major:"Major",wands:"Wands",cups:"Cups",swords:"Swords",pentacles:"Pentacles"},
    share: "Share:",
    copyUrl: "Copy URL",
};

// ═══════════════════════════════════════
// Oshi Mode Readings — Major Arcana
// ═══════════════════════════════════════
const OSHI_READINGS = {
    0: {up:"According to {name}, they could set off on any adventure as long as you're with them. They feel a pure curiosity toward you and are approaching without fear.",down:"According to {name}, they want to get closer to you but aren't ready yet. The feelings are there, but they're waiting for the right timing."},
    1: {up:"According to {name}, they felt something special about you. Your very presence is an inspiration to them.",down:"According to {name}, they want to show you their true self but don't know how."},
    2: {up:"According to {name}, they don't say it out loud, but they think about you a lot. They're watching over you quietly.",down:"According to {name}, there are feelings they're hiding from you. They're just not ready to reveal them yet."},
    3: {up:"According to {name}, they feel most at ease when they're with you. You're like a sanctuary to them.",down:"According to {name}, they want to lean on you but their pride keeps them from saying it first."},
    4: {up:"According to {name}, they want to protect you. Behind their strong exterior, they're hiding a warm heart for you.",down:"According to {name}, they regret having been too hard on you."},
    5: {up:"According to {name}, they're sincerely rooting for your growth.",down:"According to {name}, they've realized the old way of doing things can't reach you."},
    6: {up:"According to {name}, they hold special feelings for you. They feel an attraction unlike anything they've felt for anyone else.",down:"According to {name}, they feel conflicted about your relationship. But deep in their heart, they want you."},
    7: {up:"According to {name}, they'd do anything for you. You're the driving force that keeps them moving forward.",down:"According to {name}, they've lost their direction and are wandering. A single word from you could make all the difference."},
    8: {up:"According to {name}, they're drawn to your strength combined with your gentleness.",down:"According to {name}, they're afraid of showing their weak side in front of you."},
    9: {up:"According to {name}, they think of you during their time alone. They feel a deep longing.",down:"According to {name}, they're keeping their distance on purpose — but it's not because they dislike you. They just need time to sort themselves out."},
    10: {up:"According to {name}, they feel that meeting you was fate.",down:"According to {name}, they feel the timing isn't right just now. But the thread of fate between you hasn't been cut."},
    11: {up:"According to {name}, they hold nothing but an honest heart toward you.",down:"According to {name}, they're sorry for not being fair to you in the past."},
    12: {up:"According to {name}, they'd willingly sacrifice for you. That's how precious you are to them.",down:"According to {name}, they're waiting for you to reach out your hand first."},
    13: {up:"According to {name}, the relationship with you is moving into a new phase.",down:"According to {name}, they want to put the old dynamic behind them. It's a change that leads to something better."},
    14: {up:"According to {name}, their heart feels calm when they're with you. They sense a balance that's just right for both of you.",down:"According to {name}, they're working to find their emotional balance."},
    15: {up:"According to {name}, they're strongly drawn to you. They feel an attraction they can't resist.",down:"According to {name}, they tried to sort out their feelings for you, but it's not easy."},
    16: {up:"According to {name}, you've changed their entire worldview.",down:"According to {name}, they've realized their feelings for you were completely different from what they expected."},
    17: {up:"According to {name}, you're like a star in the darkness to them.",down:"According to {name}, they lost hope for a moment — but thinking of you gives them the strength to keep going."},
    18: {up:"According to {name}, they feel something about you that they can't put into words.",down:"According to {name}, the confusion they felt has started to clear. They've realized their true feelings for you."},
    19: {up:"According to {name}, they're happiest when they're with you. You're like the sun to them.",down:"According to {name}, they want to bring you happiness but they're not good at showing it."},
    20: {up:"According to {name}, they feel that everything in the past was a journey leading them to you.",down:"According to {name}, they regret not treating you better in the past."},
    21: {up:"According to {name}, they feel like their relationship with you is perfect. You're each other's greatest presence.",down:"According to {name}, they still feel something is lacking in your relationship. But they say it's almost complete."}
};

// ═══════════════════════════════════════
// Oshi Mode Readings — Minor Arcana (by suit)
// ═══════════════════════════════════════
const OSHI_MINOR = {
    wands: {
        up: [
            "According to {name}, a new passion for you has begun to burn.",
            "According to {name}, they're seriously picturing a future with you.",
            "According to {name}, the time you've shared together is bearing fruit.",
            "According to {name}, being with you feels like a celebration.",
            "According to {name}, you make them want to become a better person.",
            "According to {name}, they want to be recognized by you.",
            "According to {name}, they'd take on any challenge for you.",
            "According to {name}, their feelings for you are deepening rapidly.",
            "According to {name}, they're exhausted from protecting their heart for you — but they won't give up.",
            "According to {name}, they're carrying a lot for you — but because it's you, it's okay.",
            "According to {name}, they want to share some exciting news about you.",
            "According to {name}, they want to boldly tell you how they feel.",
            "According to {name}, they feel full of confidence when they're around you.",
            "According to {name}, they want to achieve great things together with you.",
        ],
        down: [
            "According to {name}, their passion for you hasn't faded — they just don't know how to express it.",
            "According to {name}, the future with you frightens them. They're afraid of losing you.",
            "According to {name}, things aren't going as well as hoped, but they have no intention of giving up.",
            "According to {name}, they feel a sense of instability in your relationship.",
            "According to {name}, they want to avoid unnecessary conflict.",
            "According to {name}, they're hurt by the feeling that you don't recognize them.",
            "According to {name}, they're tired and need a break. Their feelings haven't changed.",
            "According to {name}, they're frustrated that things are moving slowly.",
            "According to {name}, they're on the verge of burnout. They need a word from you.",
            "According to {name}, it's hard to handle alone. They want to lean on you.",
            "According to {name}, there's something they want to tell you, but the time isn't right yet.",
            "According to {name}, they regret acting too hastily.",
            "According to {name}, they've lost confidence around you. They want to find it again.",
            "According to {name}, they want to approach you more gently.",
        ]
    },
    cups: {
        up: [
            "According to {name}, new feelings for you are blossoming.",
            "According to {name}, they feel a deep bond with you.",
            "According to {name}, the time they spend with you is the most enjoyable.",
            "According to {name}, they've finally realized how precious you are.",
            "According to {name}, you hurt them — but that's how they learned how precious you are.",
            "According to {name}, they cherish every memory they have with you.",
            "According to {name}, the real you is better than any fantasy.",
            "According to {name}, they want to take things to a deeper level.",
            "According to {name}, they feel like their wish about you is coming true.",
            "According to {name}, being with you is perfect happiness.",
            "According to {name}, they want to make a heartfelt confession to you.",
            "According to {name}, they want to approach you in a romantic way.",
            "According to {name}, they know what you're feeling without you having to say it.",
            "According to {name}, they want to grow alongside you.",
        ],
        down: [
            "According to {name}, they feel emotionally empty. They say you could fill that void.",
            "According to {name}, it feels like the balance in the relationship has broken down.",
            "According to {name}, they were so caught up in having fun that they missed something important.",
            "According to {name}, they've started to accept new opportunities.",
            "According to {name}, they're moving past the sadness of the past. They say you helped heal them.",
            "According to {name}, they were clinging to the past. They say they'll look forward now.",
            "According to {name}, they've woken from a fantasy and started seeing the real you.",
            "According to {name}, they know they should let go, but they still have lingering feelings.",
            "According to {name}, they've realized your heart matters more than material things.",
            "According to {name}, they almost lost you by chasing perfection.",
            "According to {name}, they're reflecting on how emotionally immature they were.",
            "According to {name}, they're going to see you as you truly are.",
            "According to {name}, they're overwhelmed by their emotions. They need your steadiness.",
            "According to {name}, they want to be honest with you.",
        ]
    },
    swords: {
        up: [
            "According to {name}, they've reached a definite conclusion about you.",
            "According to {name}, an answer is coming soon.",
            "According to {name}, you hurt them — but that pain became their growth.",
            "According to {name}, they're resting while thinking of you.",
            "According to {name}, they don't want any unnecessary arguments with you.",
            "According to {name}, they're making their way through a hard period to reach you.",
            "According to {name}, they're going to approach you honestly from now on.",
            "According to {name}, they're trying to tear down the walls they built and get closer to you.",
            "According to {name}, they're losing sleep worrying about you.",
            "According to {name}, they hit rock bottom but they're getting back up. You're the reason why.",
            "According to {name}, they want to know more about you.",
            "According to {name}, they won't hesitate any longer.",
            "According to {name}, they're seeing your true worth.",
            "According to {name}, they want to guide your relationship with wisdom.",
        ],
        down: [
            "According to {name}, they're feeling confused.",
            "According to {name}, they're starting to see an answer.",
            "According to {name}, they're recovering from a wound.",
            "According to {name}, they want you to let them rest.",
            "According to {name}, it's okay to be vulnerable in front of you.",
            "According to {name}, they'll accept change as long as you're with them.",
            "According to {name}, they're going to approach you honestly from now on.",
            "According to {name}, they've started breaking free from the limits they set for themselves.",
            "According to {name}, they've started letting go of worry. They say it's thanks to you.",
            "According to {name}, the worst period is passing.",
            "According to {name}, you shouldn't worry about idle rumors.",
            "According to {name}, they're going to take things slowly.",
            "According to {name}, they want to be warmer.",
            "According to {name}, they want to hear your thoughts too.",
        ]
    },
    pentacles: {
        up: [
            "According to {name}, they want to invest seriously in the relationship with you.",
            "According to {name}, they're busy — but you come first.",
            "According to {name}, working with you brings out the best results.",
            "According to {name}, they want to keep your relationship safe and secure.",
            "According to {name}, it's a tough time, but having you nearby is a comfort.",
            "According to {name}, they want to give to you without holding back.",
            "According to {name}, a good outcome will definitely come.",
            "According to {name}, they're working to become a better person for you.",
            "According to {name}, they want to build a rich and fulfilling relationship with you.",
            "According to {name}, they want to be with you for a long, long time.",
            "According to {name}, they want to get to know you slowly.",
            "According to {name}, they're making their way toward you slowly but surely.",
            "According to {name}, they want to find a balance that's both practical and warm.",
            "According to {name}, they want to achieve great success together with you.",
        ],
        down: [
            "According to {name}, they're sad about the opportunity they feel they missed.",
            "According to {name}, they say you caught them.",
            "According to {name}, they're going to stay by your side.",
            "According to {name}, they're going to learn how to let go.",
            "According to {name}, they can see the light of recovery.",
            "According to {name}, they want to restore the balance.",
            "According to {name}, they're almost there. They say don't give up.",
            "According to {name}, you've become a new source of inspiration for them.",
            "According to {name}, they'll be okay if you're by their side.",
            "According to {name}, your relationship matters more to them than anything material.",
            "According to {name}, they're going to keep their feet on the ground.",
            "According to {name}, they're sorry for being slow — but their feelings are certain.",
            "According to {name}, they're going to get healthy and come back to you.",
            "According to {name}, they're going to approach you with a sincere heart.",
        ]
    }
};

function convertToOshi(card, name) {
    const suitData = OSHI_MINOR[card.suit];
    if (!suitData) return card.reversed ? card.down : card.up;
    const idx = Math.min(card.num - 1, 13);
    const texts = card.reversed ? suitData.down : suitData.up;
    return (texts[idx] || texts[0]).replace(/\{name\}/g, name);
}
